import type{FoodMineralValue}from'./food-mineral-intake.calculator';
export type CalciumPhosphorusPortion={foodKey:string;massG:number};
export type CalciumPhosphorusCard={foodKey:string;displayName:string;calcium?:FoodMineralValue;phosphorus?:FoodMineralValue;processingClass?:string|null;labelText?:string|null};
const round=(n:number,d=1)=>Number(n.toFixed(d));
const known=(v?:FoodMineralValue)=>Boolean(v&&v.status!=='missing'&&(v.status==='trace'||Number.isFinite(Number(v.valuePer100g))));
const amount=(v:FoodMineralValue,massG:number)=>v.status==='trace'?0:Number(v.valuePer100g)*(v.unit==='ug'?.001:1)*massG/100;
const codePattern=/\bE\s*[-–—]?\s*(338|339|340|341|342|343|450|451|452)(?!\d)/giu;
const foodKind=(card:CalciumPhosphorusCard):'beverage'|'processed_food'|'unspecified'=>/напит|кола|лимонад|сок|нектар|газиров|энергетик/i.test(card.displayName)?'beverage':card.processingClass&&card.processingClass!=='minimally_processed'?'processed_food':'unspecified';
const inferredCategory=(name:string)=>/(плавлен[а-яіїєґ]*\s+(сыр|сир)|сыр(ок)?\s+плавлен|сир(ок)?\s+плавлен)/i.test(name)?{category:'processed_cheese',label:'Плавленый сыр',basis:'Для этой категории фосфатные соли высоковероятны; этикетка не предоставлена.'}:/(выпеч|печень|кекс|маффин|бисквит|вафл|круассан|булоч|пирож|торт|пончик|донат)/i.test(name)?{category:'industrial_bakery',label:'Выпечка',basis:'Для промышленной выпечки фосфатные разрыхлители вероятны; этикетка не предоставлена.'}:null;
export function calculateCalciumPhosphorusAdditives(portions:CalciumPhosphorusPortion[],cards:CalciumPhosphorusCard[],minimumCoveragePercent=70){
 const byKey=new Map(cards.map(x=>[x.foodKey,x])),lines:any[]=[],unresolved:any[]=[],additiveFindings:any[]=[],inferredFindings:any[]=[];let calciumMg=0,phosphorusMg=0,validMassG=0,resolvedMassG=0;
 for(const portion of portions){if(!Number.isFinite(portion.massG)||portion.massG<=0||portion.massG>5000){unresolved.push({...portion,reason:'MASS_INVALID'});continue;}validMassG+=portion.massG;const card=byKey.get(portion.foodKey);if(!card){unresolved.push({...portion,reason:'CARD_NOT_FOUND'});continue;}const searchable=[card.displayName,card.labelText].filter(Boolean).join(' '),codes=[...new Set([...searchable.matchAll(codePattern)].map(x=>`E${x[1]}`))];if(codes.length)additiveFindings.push({foodKey:portion.foodKey,displayName:card.displayName,massG:round(portion.massG,3),foodKind:foodKind(card),codes});else{const inferred=inferredCategory(card.displayName);if(inferred)inferredFindings.push({foodKey:portion.foodKey,displayName:card.displayName,massG:round(portion.massG,3),...inferred,evidence:'category_default',quantitativeAdditiveEstimateGenerated:false});}const missingComponents=(['calcium','phosphorus']as const).filter(key=>!known(card[key]));if(missingComponents.length){unresolved.push({...portion,displayName:card.displayName,reason:'MINERAL_DATA_MISSING',missingComponents});continue;}const lineCalcium=amount(card.calcium!,portion.massG),linePhosphorus=amount(card.phosphorus!,portion.massG);calciumMg+=lineCalcium;phosphorusMg+=linePhosphorus;resolvedMassG+=portion.massG;lines.push({foodKey:portion.foodKey,displayName:card.displayName,massG:round(portion.massG,3),calciumMg:round(lineCalcium,3),phosphorusMg:round(linePhosphorus,3)});}
 const rowCoveragePercent=portions.length?round(lines.length/portions.length*100):0,massCoveragePercent=validMassG?round(resolvedMassG/validMassG*100):0,qualityPassed=portions.length>0&&rowCoveragePercent>=minimumCoveragePercent&&massCoveragePercent>=minimumCoveragePercent,calciumTotalMg=round(calciumMg),phosphorusTotalMg=round(phosphorusMg),caToPRatio=qualityPassed&&phosphorusTotalMg>0?round(calciumTotalMg/phosphorusTotalMg,2):null;
 return{calciumTotalMg,phosphorusTotalMg,caToPRatio,ratioDisplay:caToPRatio===null?'Недостаточно данных':`${String(caToPRatio).replace('.',',')}:1`,ratioInterpretation:'Информационное отношение рассчитанного пищевого кальция к фосфору; цветовой порог и автоматическая оценка не применяются.',phosphateAdditives:{status:additiveFindings.length?'detected':inferredFindings.length?'probable_by_category':'not_detected_in_available_text',codes:[...new Set(additiveFindings.flatMap(x=>x.codes))],findings:additiveFindings,inferredFindings,screenedCodes:['E338','E339','E340','E341','E342','E343','E450','E451','E452']},qualityGate:{status:qualityPassed?'passed':'blocked',rowCoveragePercent,massCoveragePercent,minimumCoveragePercent,reasons:qualityPassed?[]:['Недостаточно совместных данных по кальцию и фосфору.']},lines,unresolved,limitations:['Отношение Ca:P является описательным показателем рациона и не используется как диагностический или цветовой порог.','Категорийный сигнал не подтверждает конкретную добавку и не создаёт отдельную количественную прибавку к общему фосфору.','Отсутствие найденного E-кода не подтверждает отсутствие фосфатной добавки.'],diagnosisGenerated:false,clientRecommendationGenerated:false};
}
