export type CarbohydrateProductSnapshot={id:string;name:string;carbohydratePer100g:number|null;fibrePer100g:number|null;totalSugarsPer100g:number|null;freeSugarsPer100g:number|null;carbohydrateSourceClass:string|null;version:number;starchPer100g?:number|null;polyolsPer100g?:number|null;resistantStarchPer100g?:number|null;sugarOriginClass?:string|null;carbohydrateFoodGroup?:string|null;foodMatrixClass?:string|null;processingClass?:string|null;carbohydrateFlags?:string[];carbohydrateDataReliability?:string|null};
export type CarbohydrateIntakeInput={mealKey:string;productCardId:string;massG:number;massMinG?:number;massMaxG?:number;measurementType?:'grams'|'tablespoon'|'ladle'|'cup'|'other';preparationAssumed?:boolean;consumptionForm?:'solid'|'liquid';durationMinutes?:number};
const round=(n:number,d=2)=>Number(n.toFixed(d));
const eveningKeys=new Set(['dinner','evening','after_dinner','late_snack','before_sleep','bedtime']),refinedClasses=new Set(['refined_source','refined','sweet_refined']),preferredClasses=new Set(['preferred_source','whole_food','minimally_processed']);
const betweenMealKeys=new Set(['morning_snack','afternoon_snack','snack','snack_1','snack_2','between_meal','late_snack']),beforeSleepKeys=new Set(['before_sleep','late_snack','bedtime']);
const fibreStatus=(n:number)=>n<20?'markedly_insufficient':n<25?'below_minimum':n<30?'minimum_sufficient':n<=35?'optimal_working':n<=40?'high_target':'individual_assessment';
const freeSugarStatus=(n:number)=>n<5?'low':n<10?'within_main_limit':'above_recommended';
const eveningStatus=(n:number)=>n<30?'no_marked_concentration':n<40?'noticeable':n<50?'significant':'majority';
const carbohydrateStatus=(n:number)=>n<45?'below_reference_range':n>60?'above_reference_range':'within_reference_range';
const refinedStatus=(n:number)=>n>50?'refined_dominant':n>0?'mixed_quality':'not_detected';
export function calculateCarbohydrateIntake(inputs:CarbohydrateIntakeInput[],products:Map<string,CarbohydrateProductSnapshot>,energyKcal:number|null,weightLossGoal=false){
  const lines:any[]=[],unresolved:any[]=[];let carbohydrateG=0,fibreG=0,totalSugarsG=0,freeSugarsG=0,eveningCarbohydrateG=0,refinedCarbohydrateG=0,preferredCarbohydrateG=0,starchG=0,polyolsG=0,resistantStarchG=0,carbohydrateMinG=0,carbohydrateMaxG=0,fibreMinG=0,fibreMaxG=0,freeSugarsMinG=0,freeSugarsMaxG=0,eveningMinG=0,eveningMaxG=0,nonEveningMinG=0,nonEveningMaxG=0,refinedMinG=0,refinedMaxG=0,nonRefinedMinG=0,nonRefinedMaxG=0;
  let carbohydrateKnown=0,fibreKnown=0,totalSugarsKnown=0,freeSugarsKnown=0,sourceClassKnown=0,starchKnown=0,polyolsKnown=0,resistantStarchKnown=0,structureKnown=0,processingKnown=0,sugarOriginKnown=0,reliabilityKnown=0;let hasEstimatedRange=false;
  const foodGroups:Record<string,number>={},matrices:Record<string,number>={},processing:Record<string,number>={};
  inputs.forEach((input,index)=>{const product=products.get(input.productCardId);if(!product){unresolved.push({index,reason:'PRODUCT_NOT_VERIFIED'});return;}const min=input.massMinG??input.massG,max=input.massMaxG??input.massG;if(!Number.isFinite(input.massG)||!Number.isFinite(min)||!Number.isFinite(max)||min<=0||min>input.massG||input.massG>max||max>5000){unresolved.push({index,reason:'MASS_RANGE_INVALID'});return;}if(min!==input.massG||max!==input.massG)hasEstimatedRange=true;const value=(per100g:number|null|undefined,mass=input.massG)=>per100g==null?null:mass*per100g/100;const carbohydrate=value(product.carbohydratePer100g),carbohydrateMin=value(product.carbohydratePer100g,min),carbohydrateMax=value(product.carbohydratePer100g,max),fibre=value(product.fibrePer100g),fibreMin=value(product.fibrePer100g,min),fibreMax=value(product.fibrePer100g,max),totalSugars=value(product.totalSugarsPer100g),freeSugars=value(product.freeSugarsPer100g),freeSugarsMin=value(product.freeSugarsPer100g,min),freeSugarsMax=value(product.freeSugarsPer100g,max),starch=value(product.starchPer100g),polyols=value(product.polyolsPer100g),resistantStarch=value(product.resistantStarchPer100g);
    if(carbohydrate!==null&&carbohydrateMin!==null&&carbohydrateMax!==null){carbohydrateG+=carbohydrate;carbohydrateMinG+=carbohydrateMin;carbohydrateMaxG+=carbohydrateMax;carbohydrateKnown++;if(eveningKeys.has(input.mealKey)){eveningCarbohydrateG+=carbohydrate;eveningMinG+=carbohydrateMin;eveningMaxG+=carbohydrateMax;}else{nonEveningMinG+=carbohydrateMin;nonEveningMaxG+=carbohydrateMax;}}if(fibre!==null&&fibreMin!==null&&fibreMax!==null){fibreG+=fibre;fibreMinG+=fibreMin;fibreMaxG+=fibreMax;fibreKnown++;}if(totalSugars!==null){totalSugarsG+=totalSugars;totalSugarsKnown++;}if(freeSugars!==null&&freeSugarsMin!==null&&freeSugarsMax!==null){freeSugarsG+=freeSugars;freeSugarsMinG+=freeSugarsMin;freeSugarsMaxG+=freeSugarsMax;freeSugarsKnown++;}if(starch!==null){starchG+=starch;starchKnown++;}if(polyols!==null){polyolsG+=polyols;polyolsKnown++;}if(resistantStarch!==null){resistantStarchG+=resistantStarch;resistantStarchKnown++;}
    if(product.carbohydrateSourceClass){sourceClassKnown++;if(carbohydrate!==null&&carbohydrateMin!==null&&carbohydrateMax!==null){if(refinedClasses.has(product.carbohydrateSourceClass)){refinedCarbohydrateG+=carbohydrate;refinedMinG+=carbohydrateMin;refinedMaxG+=carbohydrateMax;}else{nonRefinedMinG+=carbohydrateMin;nonRefinedMaxG+=carbohydrateMax;}if(preferredClasses.has(product.carbohydrateSourceClass))preferredCarbohydrateG+=carbohydrate;}}if(product.carbohydrateFoodGroup){structureKnown++;if(carbohydrate!==null)foodGroups[product.carbohydrateFoodGroup]=(foodGroups[product.carbohydrateFoodGroup]||0)+carbohydrate;}else if(product.foodMatrixClass)structureKnown++;if(product.foodMatrixClass&&carbohydrate!==null)matrices[product.foodMatrixClass]=(matrices[product.foodMatrixClass]||0)+carbohydrate;if(product.processingClass){processingKnown++;if(carbohydrate!==null)processing[product.processingClass]=(processing[product.processingClass]||0)+carbohydrate;}if(product.sugarOriginClass)sugarOriginKnown++;if(product.carbohydrateDataReliability)reliabilityKnown++;
    lines.push({...input,massMinG:min,massMaxG:max,product,nutrients:{carbohydrateG:carbohydrate,fibreG:fibre,totalSugarsG:totalSugars,freeSugarsG:freeSugars,starchG:starch,polyolsG:polyols,resistantStarchG:resistantStarch}});
  });
  const relevant=lines.length,coverage=(known:number)=>relevant?Math.round(known/relevant*100):0,quantitativeCoverage=coverage(carbohydrateKnown),sugarCoverage=coverage(freeSugarsKnown),classificationCoverage=coverage(sourceClassKnown);const carbohydrateEnergyPercent=energyKcal&&quantitativeCoverage===100?carbohydrateG*4/energyKcal*100:null,freeSugarsEnergyPercent=energyKcal&&sugarCoverage===100?freeSugarsG*4/energyKcal*100:null,eveningSharePercent=quantitativeCoverage===100&&carbohydrateG?eveningCarbohydrateG/carbohydrateG*100:null,refinedSharePercent=quantitativeCoverage===100&&classificationCoverage===100&&carbohydrateG?refinedCarbohydrateG/carbohydrateG*100:null,preferredSharePercent=quantitativeCoverage===100&&classificationCoverage===100&&carbohydrateG?preferredCarbohydrateG/carbohydrateG*100:null;
  const range={carbohydrateG:quantitativeCoverage===100?{min:round(carbohydrateMinG),max:round(carbohydrateMaxG)}:null,fibreG:fibreKnown===relevant?{min:round(fibreMinG),max:round(fibreMaxG)}:null,freeSugarsG:sugarCoverage===100?{min:round(freeSugarsMinG),max:round(freeSugarsMaxG)}:null,carbohydrateEnergyPercent:energyKcal&&quantitativeCoverage===100?{min:round(carbohydrateMinG*4/energyKcal*100),max:round(carbohydrateMaxG*4/energyKcal*100)}:null,freeSugarsEnergyPercent:energyKcal&&sugarCoverage===100?{min:round(freeSugarsMinG*4/energyKcal*100),max:round(freeSugarsMaxG*4/energyKcal*100)}:null,eveningSharePercent:quantitativeCoverage===100&&(eveningMinG+nonEveningMaxG)>0?{min:round(eveningMinG/(eveningMinG+nonEveningMaxG)*100),max:round(eveningMaxG/(eveningMaxG+nonEveningMinG)*100)}:null,refinedSharePercent:quantitativeCoverage===100&&classificationCoverage===100&&(refinedMinG+nonRefinedMaxG)>0?{min:round(refinedMinG/(refinedMinG+nonRefinedMaxG)*100),max:round(refinedMaxG/(refinedMaxG+nonRefinedMinG)*100)}:null};
  const boundarySignals:string[]=[];const crosses=(key:string,r:{min:number;max:number}|null,status:(n:number)=>string)=>{if(r&&status(r.min)!==status(r.max))boundarySignals.push(key);};crosses('carbohydrate',range.carbohydrateEnergyPercent,carbohydrateStatus);crosses('fibre',range.fibreG,fibreStatus);crosses('free_sugars',range.freeSugarsEnergyPercent,freeSugarStatus);crosses('evening',range.eveningSharePercent,eveningStatus);crosses('refined',range.refinedSharePercent,refinedStatus);
  const episodeGroups=new Map<string,any[]>();for(const line of lines)episodeGroups.set(line.mealKey,[...(episodeGroups.get(line.mealKey)||[]),line]);
  const episodes=[...episodeGroups].map(([mealKey,mealLines])=>{const carbohydrateValues=mealLines.map(line=>line.nutrients.carbohydrateG),freeSugarValues=mealLines.map(line=>line.nutrients.freeSugarsG),carbohydrateComplete=carbohydrateValues.every(value=>value!==null),freeSugarComplete=freeSugarValues.every(value=>value!==null),carbohydrateTotal=carbohydrateComplete?carbohydrateValues.reduce((sum,value)=>sum+value,0):null,freeSugarTotal=freeSugarComplete?freeSugarValues.reduce((sum,value)=>sum+value,0):freeSugarValues.some(value=>value!==null&&value>0)?freeSugarValues.filter(value=>value!==null).reduce((sum,value)=>sum+value,0):null,classificationComplete=mealLines.every(line=>line.product.carbohydrateSourceClass),refinedTotal=carbohydrateComplete&&classificationComplete?mealLines.reduce((sum,line)=>sum+(refinedClasses.has(line.product.carbohydrateSourceClass)?line.nutrients.carbohydrateG:0),0):null,refinedShare=carbohydrateTotal&&refinedTotal!==null?refinedTotal/carbohydrateTotal*100:null,liquid=mealLines.some(line=>line.consumptionForm==='liquid'||line.product.carbohydrateFlags?.includes('liquid')),prolonged=mealLines.some(line=>(line.durationMinutes??0)>=30||line.product.carbohydrateFlags?.includes('prolonged_consumption')),driedFruit=mealLines.some(line=>line.product.carbohydrateFlags?.includes('concentrated_dried_fruit'));const freeSugarEpisode=freeSugarTotal===null?null:freeSugarTotal>0,flags:string[]=[];if(freeSugarEpisode&&betweenMealKeys.has(mealKey))flags.push('between_meal_free_sugar');if(freeSugarEpisode&&beforeSleepKeys.has(mealKey))flags.push('free_sugar_before_sleep');if(freeSugarEpisode&&liquid)flags.push('liquid_free_sugar');if(freeSugarEpisode&&liquid&&prolonged)flags.push('prolonged_sugary_drink');if(driedFruit&&betweenMealKeys.has(mealKey))flags.push('concentrated_dried_fruit_episode');return{assessmentUnit:'typical_day',mealKey,lineCount:mealLines.length,freeSugarEpisode,freeSugarsG:freeSugarTotal===null?null:round(freeSugarTotal),refinedClassification:refinedShare===null?'unknown':refinedStatus(refinedShare),refinedSharePercent:refinedShare===null?null:round(refinedShare),flags};});
  const betweenMealFreeSugarCount=episodes.filter(episode=>episode.flags.includes('between_meal_free_sugar')).length,episodeSignals={repeatedBetweenMealFreeSugar:betweenMealFreeSugarCount>=2,freeSugarBeforeSleep:episodes.some(episode=>episode.flags.includes('free_sugar_before_sleep')),liquidFreeSugar:episodes.some(episode=>episode.flags.includes('liquid_free_sugar')),prolongedSugaryDrink:episodes.some(episode=>episode.flags.includes('prolonged_sugary_drink')),freeSugarAmountHigh:freeSugarsEnergyPercent!==null&&freeSugarsEnergyPercent>=10,concentratedDriedFruitEpisode:episodes.some(episode=>episode.flags.includes('concentrated_dried_fruit_episode'))};
  const dataStatus=unresolved.length||quantitativeCoverage<80?'insufficient_data':boundarySignals.length?'uncertain_boundary':hasEstimatedRange||quantitativeCoverage<100||sugarCoverage<100||classificationCoverage<100||coverage(structureKnown)<100||coverage(processingKnown)<100||coverage(sugarOriginKnown)<100||coverage(reliabilityKnown)<100?'usable_with_caveat':'reliable',shares=(values:Record<string,number>)=>Object.fromEntries(Object.entries(values).map(([key,value])=>[key,carbohydrateG?round(value/carbohydrateG*100):0]));
  return {episodeAnalysis:{assessmentBasis:'typical_day',limitation:'declared_typical_pattern_not_multiday_observation',episodes,signals:episodeSignals,betweenMealFreeSugarCount},lines,unresolved,range:{...range,hasEstimatedRange,boundarySignals},totals:{carbohydrateG:round(carbohydrateG),fibreG:round(fibreG),totalSugarsG:round(totalSugarsG),freeSugarsG:sugarCoverage===100?round(freeSugarsG):null,starchG:starchKnown===relevant?round(starchG):null,polyolsG:polyolsKnown===relevant?round(polyolsG):null,resistantStarchG:resistantStarchKnown===relevant?round(resistantStarchG):null},completeness:{diary:inputs.length?Math.round(relevant/inputs.length*100):0,quantitative:quantitativeCoverage,sugar:sugarCoverage,classification:classificationCoverage,structure:coverage(structureKnown),processing:coverage(processingKnown),sugarOrigin:coverage(sugarOriginKnown),reliability:coverage(reliabilityKnown),timing:quantitativeCoverage},qualityProfile:{foodGroupSharePercent:shares(foodGroups),matrixSharePercent:shares(matrices),processingSharePercent:shares(processing)},dataStatus,carbohydrateEnergyPercent:carbohydrateEnergyPercent===null?null:round(carbohydrateEnergyPercent),freeSugarsEnergyPercent:freeSugarsEnergyPercent===null?null:round(freeSugarsEnergyPercent),eveningSharePercent:eveningSharePercent===null?null:round(eveningSharePercent),refinedSharePercent:refinedSharePercent===null?null:round(refinedSharePercent),preferredSharePercent:preferredSharePercent===null?null:round(preferredSharePercent),signals:{carbohydrate:carbohydrateEnergyPercent===null?'insufficient_data':carbohydrateStatus(carbohydrateEnergyPercent),fibre:fibreKnown!==relevant?'insufficient_data':fibreStatus(fibreG),freeSugars:freeSugarsEnergyPercent===null?'insufficient_data':freeSugarStatus(freeSugarsEnergyPercent),evening:eveningSharePercent===null?'insufficient_data':eveningStatus(eveningSharePercent),eveningWeightLossSignal:weightLossGoal&&eveningSharePercent!==null&&eveningSharePercent>=40?'professional_signal':'not_detected',refined:refinedSharePercent===null?'insufficient_data':refinedStatus(refinedSharePercent)}};
}
