import {describe,expect,it} from 'vitest';import {calculateCarbohydrateClientExplanation,isCarbohydrateExplanationApprovalCurrent} from './carbohydrate-client-explanation.calculator';
const base:any={signals:{carbohydrate:'within_reference_range',fibre:'high_target',freeSugars:'low',evening:'no_marked_concentration',refined:'mixed_quality'},dataStatus:'reliable'};
describe('carbohydrate client explanation',()=>{it('uses neutral typical-ration language and approved high-target wording',()=>{const x=calculateCarbohydrateClientExplanation(base),text=JSON.stringify(x);expect(text).toContain('высоком целевом уровне');expect(text).toContain('описанном типичном рационе');expect(x.disclaimer).toBe('');});it('does not expose product-level or professional recommendation fields',()=>{const x=calculateCarbohydrateClientExplanation({...base,lines:[{product:{name:'hidden'}}]});const text=JSON.stringify(x);expect(text).not.toContain('hidden');expect(Object.keys(x)).toEqual(['title','summary','points','next_step','disclaimer']);});it('invalidates approval when calculation versions or text change',()=>{const a={sourceIntakeVersion:2,targetVersion:3,explanationHash:'h'};expect(isCarbohydrateExplanationApprovalCurrent(a,2,3,'h')).toBe(true);expect(isCarbohydrateExplanationApprovalCurrent(a,3,3,'h')).toBe(false);expect(isCarbohydrateExplanationApprovalCurrent(a,2,4,'h')).toBe(false);expect(isCarbohydrateExplanationApprovalCurrent(a,2,3,'x')).toBe(false);});});
describe('carbohydrate client explanation scenarios',()=>{
  it('describes low fibre without prescribing a correction',()=>{const x=calculateCarbohydrateClientExplanation({...base,signals:{...base.signals,fibre:'below_minimum'}});expect(JSON.stringify(x)).toContain('ниже минимального уровня');expect(JSON.stringify(x)).not.toContain('добавьте');});
  it('describes free sugars, evening concentration and refined dominance as separate facts',()=>{const x=calculateCarbohydrateClientExplanation({...base,signals:{...base.signals,fibre:'insufficient_data',freeSugars:'above_recommended',evening:'significant',refined:'refined_dominant'}});expect(x.points.join(' ')).toContain('10% или более');expect(x.points.join(' ')).toContain('ужин');expect(x.points.join(' ')).toContain('рафинированные');});
  it('always retains a material data limitation when findings are numerous',()=>{const x=calculateCarbohydrateClientExplanation({...base,dataStatus:'uncertain_boundary',signals:{...base.signals,freeSugars:'above_recommended',evening:'majority',refined:'refined_dominant'}});expect(x.points.at(-1)).toContain('Погрешность оценки');expect(x.points.length).toBeLessThanOrEqual(3);});
  it('uses the data limitation as the summary when no nutrient conclusion exists',()=>{const x=calculateCarbohydrateClientExplanation({dataStatus:'insufficient_data',signals:{carbohydrate:'insufficient_data',fibre:'insufficient_data',freeSugars:'insufficient_data',evening:'insufficient_data',refined:'insufficient_data'}});expect(x.summary).toBe('Для части углеводных показателей недостаточно данных.');});
  it('contains no client directive or concrete food prescription',()=>{const text=JSON.stringify(calculateCarbohydrateClientExplanation(base)).toLowerCase();for(const forbidden of ['вам нужно','рекомендуем','добавьте','исключите','замените','порция 100'])expect(text).not.toContain(forbidden);});
});
