import {describe,expect,it} from 'vitest';import {calculateCarbohydrateProfessionalFacts} from './carbohydrate-professional-facts.calculator';
const base:any={dataStatus:'reliable',carbohydrateEnergyPercent:50,freeSugarsEnergyPercent:3,eveningSharePercent:25,refinedSharePercent:20,totals:{carbohydrateG:250,fibreG:32},signals:{carbohydrate:'within_reference_range',fibre:'optimal_working',freeSugars:'low',evening:'no_marked_concentration',refined:'mixed_quality'},range:{boundarySignals:[],hasEstimatedRange:false},episodeAnalysis:{betweenMealFreeSugarCount:0,signals:{repeatedBetweenMealFreeSugar:false,liquidFreeSugar:false}}};
describe('carbohydrate professional facts',()=>{
  it('produces a compact typical-day card without recommendations',()=>{const x=calculateCarbohydrateProfessionalFacts(base);expect(x).toMatchObject({assessment_basis:'typical_day',main_additional_code:null,client_recommendations_generated:false});expect(x.facts).toHaveLength(2);expect(JSON.stringify(x)).toContain('типичн');});
  it('selects only one additional fact by approved priority',()=>{const x=calculateCarbohydrateProfessionalFacts({...base,freeSugarsEnergyPercent:12,eveningSharePercent:55,refinedSharePercent:70,signals:{...base.signals,freeSugars:'above_recommended',evening:'majority',refined:'refined_dominant'}});expect(x.main_additional_code).toBe('free_sugars_high');expect(x.facts).toHaveLength(3);});
  it('uses the approved compact wording for a balanced profile',()=>{const x=calculateCarbohydrateProfessionalFacts(base);expect(x.facts.map(f=>f.text)).toEqual(['В описанном типичном рационе углеводы обеспечивают 50% энергии — в рабочем диапазоне.','Пищевые волокна: 32 г — оптимальный рабочий диапазон.']);expect(x.basis_text).toBe('Основание оценки — заявленный клиентом типичный рацион; это не многодневный пищевой дневник.');});
  it('states boundary uncertainty in Russian without discarding stable facts',()=>{const x=calculateCarbohydrateProfessionalFacts({...base,dataStatus:'uncertain_boundary',range:{hasEstimatedRange:true,boundarySignals:['fibre']}});expect(x.data_quality.limitation).toContain('пищевых волокон');expect(x.data_quality.limitation).not.toContain('fibre');expect(x.facts).toHaveLength(2);});
  it.each([['markedly_insufficient',18,'выраженно ниже минимального'],['below_minimum',22,'ниже минимального'],['minimum_sufficient',27,'минимально достаточный'],['optimal_working',32,'оптимальный рабочий'],['high_target',38,'высокий целевой уровень'],['individual_assessment',42,'выше 40 г']])('renders fibre status %s neutrally',(status,grams,fragment)=>{const x=calculateCarbohydrateProfessionalFacts({...base,totals:{...base.totals,fibreG:grams},signals:{...base.signals,fibre:status}});expect(x.facts[1].text).toContain(fragment);});
  it('contains no directive language addressed to the client',()=>{const text=JSON.stringify(calculateCarbohydrateProfessionalFacts(base)).toLowerCase();for(const forbidden of ['вам нужно','следует есть','рекомендуем','замените','исключите'])expect(text).not.toContain(forbidden);});
});
