type CarbohydrateResult={dataStatus:string;carbohydrateEnergyPercent:number|null;freeSugarsEnergyPercent:number|null;eveningSharePercent:number|null;refinedSharePercent:number|null;totals:{carbohydrateG:number;fibreG:number};signals:Record<string,string>;range:{boundarySignals:string[];hasEstimatedRange:boolean};episodeAnalysis:{betweenMealFreeSugarCount:number;signals:Record<string,boolean>}};
const n=(value:number|null,suffix='')=>value===null?'нет надёжной числовой оценки':`${value}${suffix}`;
const episodeWord=(count:number)=>count%10===1&&count%100!==11?'эпизод':count%10>=2&&count%10<=4&&(count%100<12||count%100>14)?'эпизода':'эпизодов';
const boundaryNames:Record<string,string>={carbohydrate:'общего количества углеводов',fibre:'пищевых волокон',free_sugars:'свободных сахаров',evening:'вечерней доли углеводов',refined:'доли рафинированных источников'};
const quantityText=(c:CarbohydrateResult)=>c.signals.carbohydrate==='below_reference_range'?`В описанном типичном рационе углеводы обеспечивают ${n(c.carbohydrateEnergyPercent,'%')} энергии — ниже рабочего диапазона.`:c.signals.carbohydrate==='above_reference_range'?`В описанном типичном рационе углеводы обеспечивают ${n(c.carbohydrateEnergyPercent,'%')} энергии — выше рабочего диапазона.`:c.signals.carbohydrate==='within_reference_range'?`В описанном типичном рационе углеводы обеспечивают ${n(c.carbohydrateEnergyPercent,'%')} энергии — в рабочем диапазоне.`:'Надёжная оценка общего количества углеводов не сформирована.';
const fibreText=(c:CarbohydrateResult)=>({markedly_insufficient:`Пищевые волокна: ${c.totals.fibreG} г — выраженно ниже минимального уровня.`,below_minimum:`Пищевые волокна: ${c.totals.fibreG} г — ниже минимального уровня.`,minimum_sufficient:`Пищевые волокна: ${c.totals.fibreG} г — минимально достаточный уровень.`,optimal_working:`Пищевые волокна: ${c.totals.fibreG} г — оптимальный рабочий диапазон.`,high_target:`Пищевые волокна: ${c.totals.fibreG} г — высокий целевой уровень в пределах 35–40 г.`,individual_assessment:`Пищевые волокна: ${c.totals.fibreG} г — выше 40 г; необходима индивидуальная профессиональная интерпретация.`,insufficient_data:'Надёжная оценка пищевых волокон не сформирована.'} as Record<string,string>)[c.signals.fibre];
export function calculateCarbohydrateProfessionalFacts(c:CarbohydrateResult){
  const facts:{code:string;text:string;evidence:Record<string,unknown>}[]=[{code:'carbohydrate_quantity',text:quantityText(c),evidence:{carbohydrate_g:c.totals.carbohydrateG,energy_percent:c.carbohydrateEnergyPercent}},{code:'fibre',text:fibreText(c),evidence:{fibre_g:c.totals.fibreG,status:c.signals.fibre}}];
  let mainAdditional:{code:string;text:string;evidence:Record<string,unknown>}|null=null;
  if(c.signals.freeSugars==='above_recommended')mainAdditional={code:'free_sugars_high',text:`Свободные сахара: ${n(c.freeSugarsEnergyPercent,'%')} энергии — уровень 10% или выше.`,evidence:{energy_percent:c.freeSugarsEnergyPercent}};
  else if(['significant','majority'].includes(c.signals.evening))mainAdditional={code:'evening_concentration',text:`На ужин и последующие эпизоды приходится ${n(c.eveningSharePercent,'%')} углеводов описанного типичного рациона.`,evidence:{evening_share_percent:c.eveningSharePercent,status:c.signals.evening}};
  else if(c.signals.refined==='refined_dominant')mainAdditional={code:'refined_dominant',text:`Рафинированные источники формируют ${n(c.refinedSharePercent,'%')} доступных углеводов описанного типичного рациона — более половины.`,evidence:{refined_share_percent:c.refinedSharePercent}};
  else if(c.episodeAnalysis.signals.repeatedBetweenMealFreeSugar)mainAdditional={code:'repeated_between_meal_free_sugar',text:`В описанном типичном рационе отмечены ${c.episodeAnalysis.betweenMealFreeSugarCount} межприёмных ${episodeWord(c.episodeAnalysis.betweenMealFreeSugarCount)} со свободными сахарами.`,evidence:{episode_count:c.episodeAnalysis.betweenMealFreeSugarCount}};
  else if(c.episodeAnalysis.signals.liquidFreeSugar)mainAdditional={code:'liquid_free_sugar',text:'В описанном типичном рационе присутствует жидкий источник свободных сахаров.',evidence:{present:true}};
  if(mainAdditional)facts.push(mainAdditional);
  const boundaries=c.range.boundarySignals.map(key=>boundaryNames[key]??key).join(', '),limitation=c.dataStatus==='insufficient_data'?'Часть значимых данных отсутствует; зависимые выводы не сформированы.':c.dataStatus==='uncertain_boundary'?`Диапазон оценки пересекает значимую границу для показателя: ${boundaries}.`:c.dataStatus==='usable_with_caveat'?'Часть порций оценена диапазоном; показанные категории устойчивы в его пределах.':null;
  return{assessment_basis:'typical_day',basis_text:'Основание оценки — заявленный клиентом типичный рацион; это не многодневный пищевой дневник.',facts,main_additional_code:mainAdditional?.code??null,data_quality:{status:c.dataStatus,limitation},client_recommendations_generated:false};
}
