import {Injectable} from '@nestjs/common';
import {HttpStatus} from '@nestjs/common';
import {createHash} from 'node:crypto';
import type {AuthenticatedUser} from '../auth/auth.types';
import {AuthorizationPolicy} from '../authorization/authorization.policy';
import {AppError,unavailable} from '../common/app-error';
import {AssignmentRepository} from './assignment.repository';
import {calculateCarbohydrateIntake,type CarbohydrateIntakeInput,type CarbohydrateProductSnapshot} from './carbohydrate-intake.calculator';
import {calculateCarbohydrateProfessionalFacts} from './carbohydrate-professional-facts.calculator';
import {calculateCarbohydrateClientExplanation,isCarbohydrateExplanationApprovalCurrent} from './carbohydrate-client-explanation.calculator';
import {NutrientClientPublicationRepository} from './nutrient-client-publication.repository';
import {FatTargetRepository} from './fat-target.repository';import {FoodProductRepository} from './food-product.repository';import {PayloadCryptoService} from './payload-crypto.service';import {ProteinIntakeRepository} from './protein-intake.repository';import {SubmissionStore} from './submission.store';
@Injectable() export class CarbohydrateIntakeService{
  constructor(private readonly store:SubmissionStore,private readonly assignments:AssignmentRepository,private readonly policy:AuthorizationPolicy,private readonly intake:ProteinIntakeRepository,private readonly products:FoodProductRepository,private readonly target:FatTargetRepository,private readonly crypto:PayloadCryptoService,private readonly approvals:NutrientClientPublicationRepository){}
  async get(submissionId:string,clientId:string,user:AuthenticatedUser){
    this.policy.requireRole(user,'consultant');const submission=await this.store.findById(submissionId);if(!submission||submission.clientId!==clientId)throw unavailable('SUBMISSION_NOT_FOUND');this.policy.requireActiveAssignment(user,await this.assignments.activeConsultant(clientId));if(submission.status!=='accepted')throw unavailable('SUBMISSION_NOT_ACCEPTED');
    const assessment=await this.intake.findBySubmission(submissionId),target=await this.target.findBySubmission(submissionId);if(!assessment)return{submission_id:submissionId,source_intake_version:0,summary:null};let payload:any;try{payload=JSON.parse(Buffer.from(await this.crypto.decrypt(assessment.payloadCiphertext)).toString('utf8'));}catch{throw new AppError('CARBOHYDRATE_INTAKE_INTEGRITY_FAILED',409);}
    const inputs:CarbohydrateIntakeInput[]=payload.items||[],cards=await this.products.verifiedByIds([...new Set(inputs.map(i=>i.productCardId))]);
    const carbohydrateCards=new Map<string,CarbohydrateProductSnapshot>([...cards].map(([id,p])=>[id,{id,name:p.name,carbohydratePer100g:p.carbohydratePer100g??null,fibrePer100g:p.fibrePer100g??null,totalSugarsPer100g:p.totalSugarsPer100g??null,freeSugarsPer100g:p.freeSugarsPer100g??null,carbohydrateSourceClass:p.carbohydrateSourceClass??null,starchPer100g:p.starchPer100g,polyolsPer100g:p.polyolsPer100g,resistantStarchPer100g:p.resistantStarchPer100g,sugarOriginClass:p.sugarOriginClass,carbohydrateFoodGroup:p.carbohydrateFoodGroup,foodMatrixClass:p.foodMatrixClass,processingClass:p.processingClass,carbohydrateFlags:p.carbohydrateFlags,carbohydrateDataReliability:p.carbohydrateDataReliability,version:p.version}]));
    const c=calculateCarbohydrateIntake(inputs,carbohydrateCards,target?.energyKcal??null,false);
    const professionalFacts=calculateCarbohydrateProfessionalFacts(c);
    const clientExplanation=calculateCarbohydrateClientExplanation(c),explanationHash=createHash('sha256').update(JSON.stringify(clientExplanation)).digest('hex'),approval=await this.approvals.find(submissionId,'carbohydrate'),approvalCurrent=isCarbohydrateExplanationApprovalCurrent(approval,assessment.version,target?.version??0,explanationHash);
    return{submission_id:submissionId,source_intake_version:assessment.version,target_version:target?.version??0,client_publication_status:approvalCurrent?'approved':'draft',client_explanation:clientExplanation,client_approval:{status:approvalCurrent?'approved':'draft',version:approval?.version??0,approved_at:approvalCurrent?approval?.approvedAt.toISOString():null},professional_facts:professionalFacts,summary:{total_carbohydrate_g:c.totals.carbohydrateG,carbohydrate_energy_percent:c.carbohydrateEnergyPercent,fibre_g:c.totals.fibreG,total_sugars_g:c.totals.totalSugarsG,free_sugars_g:c.totals.freeSugarsG,starch_g:c.totals.starchG,polyols_g:c.totals.polyolsG,resistant_starch_g:c.totals.resistantStarchG,free_sugars_energy_percent:c.freeSugarsEnergyPercent,evening_share_percent:c.eveningSharePercent,refined_share_percent:c.refinedSharePercent,preferred_share_percent:c.preferredSharePercent,quality_profile:c.qualityProfile,uncertainty_range:c.range,data_status:c.dataStatus,completeness:c.completeness,signals:c.signals},episode_analysis:c.episodeAnalysis,lines:c.lines,unresolved:c.unresolved};
  }
  async approveClientExplanation(submissionId:string,clientId:string,user:AuthenticatedUser,requestId:string,expectedVersion:number){const current=await this.get(submissionId,clientId,user);if(!current.client_explanation||current.source_intake_version<1)throw new AppError('CARBOHYDRATE_CLIENT_EXPLANATION_UNAVAILABLE',HttpStatus.CONFLICT);const serialized=JSON.stringify(current.client_explanation),explanationHash=createHash('sha256').update(serialized).digest('hex'),explanationCiphertext=await this.crypto.encrypt(Buffer.from(serialized)),saved=await this.approvals.approve({clientId,submissionId,nutrientKey:'carbohydrate',sourceIntakeVersion:current.source_intake_version,targetVersion:current.target_version,explanationHash,explanationCiphertext,approvedBy:user.id,expectedVersion,requestId});if(!saved)throw new AppError('CARBOHYDRATE_CLIENT_EXPLANATION_VERSION_CONFLICT',HttpStatus.CONFLICT);return{status:'approved',version:saved.version,approved_at:saved.approvedAt.toISOString()};}
}
