import { describe,expect,it } from 'vitest';
import type { AuthenticatedUser } from '../auth/auth.types';import { AuthorizationPolicy } from '../authorization/authorization.policy';import { ConsultationBookingService } from './consultation-booking.service';
const user:AuthenticatedUser={id:'00000000-0000-0000-0000-000000000001',authSubject:'synthetic',role:'consultant',status:'active',sessionIssuedAt:new Date(),sessionRevokedAt:null};
const clientId='00000000-0000-0000-0000-000000000099',submissionId='00000000-0000-0000-0000-000000000020';
function setup(o:{existing?:boolean;save?:boolean;assigned?:string|null;submissionStatus?:string}={}){const saved:unknown[]=[];const record={id:'00000000-0000-0000-0000-000000000030',clientId,submissionId,updatedBy:user.id,status:'scheduled' as const,scheduledAt:new Date('2026-09-01T10:00:00Z'),contactNoteCiphertext:Buffer.from('cipher'),version:2,updatedAt:new Date('2026-08-16T10:00:00Z')};const service=new ConsultationBookingService({findById:async()=>({id:submissionId,clientId,status:o.submissionStatus??'accepted'})} as never,{activeConsultant:async()=>o.assigned===undefined?user.id:o.assigned} as never,new AuthorizationPolicy(),{findBySubmission:async()=>o.existing===false?null:record,save:async(i:unknown)=>{saved.push(i);return o.save===false?null:{...record,version:3};}} as never,{encrypt:async(v:Uint8Array)=>v,decrypt:async()=>Buffer.from('Telegram, время подтверждено')} as never);return {service,saved};}
describe('consultation booking',()=>{
  it('returns pending version zero when absent',async()=>expect(await setup({existing:false}).service.get(submissionId,clientId,user)).toMatchObject({status:'pending',scheduled_at:null,version:0}));
  it('returns decrypted booking state',async()=>expect((await setup().service.get(submissionId,clientId,user)).contact_note).toBe('Telegram, время подтверждено'));
  it('saves scheduled date with optimistic version',async()=>{const {service,saved}=setup();const out=await service.save(submissionId,clientId,user,'req',2,{status:'scheduled',scheduled_at:'2026-09-05T12:30:00.000Z',contact_note:' Telegram '});expect(out.version).toBe(3);expect(JSON.stringify(saved)).not.toContain('Telegram');});
  it('rejects scheduled without a date',async()=>await expect(setup().service.save(submissionId,clientId,user,'req',0,{status:'scheduled',scheduled_at:null,contact_note:''})).rejects.toThrow('CONSULTATION_BOOKING_INVALID'));
  it('rejects a date for reminder state',async()=>await expect(setup().service.save(submissionId,clientId,user,'req',0,{status:'needs_reminder',scheduled_at:'2026-09-05',contact_note:''})).rejects.toThrow('CONSULTATION_BOOKING_INVALID'));
  it('reports a version conflict',async()=>await expect(setup({save:false}).service.save(submissionId,clientId,user,'req',2,{status:'pending',scheduled_at:null,contact_note:''})).rejects.toThrow('CONSULTATION_BOOKING_VERSION_CONFLICT'));
  it('requires accepted submission and assignment',async()=>{await expect(setup({submissionStatus:'verified'}).service.get(submissionId,clientId,user)).rejects.toThrow('RESOURCE_UNAVAILABLE');await expect(setup({assigned:null}).service.get(submissionId,clientId,user)).rejects.toThrow('RESOURCE_UNAVAILABLE');});
});
