import {Injectable} from '@nestjs/common';
import {PrismaService} from '../database/prisma.service';
import type {FatActivity,FatGoal} from './fat-target.calculator';
export type FatTargetRecord={id:string;clientId:string;submissionId:string;updatedBy:string;energyKcal:number;weightKg:number;goal:FatGoal;activity:FatActivity;energyPercentMin:number;energyPercentMax:number;targetMinG:number;targetMaxG:number;gramsPerKgMin:number;gramsPerKgMax:number;reasonCiphertext:Uint8Array;version:number;updatedAt:Date};
type Row={id:string;client_id:string;submission_id:string;updated_by:string;energy_kcal:number;weight_kg:unknown;goal:FatGoal;activity:FatActivity;energy_percent_min:number;energy_percent_max:number;target_min_g:unknown;target_max_g:unknown;grams_per_kg_min:unknown;grams_per_kg_max:unknown;reason_ciphertext:Uint8Array;version:number;updated_at:Date};
const map=(r:Row):FatTargetRecord=>({id:r.id,clientId:r.client_id,submissionId:r.submission_id,updatedBy:r.updated_by,energyKcal:r.energy_kcal,weightKg:Number(r.weight_kg),goal:r.goal,activity:r.activity,energyPercentMin:r.energy_percent_min,energyPercentMax:r.energy_percent_max,targetMinG:Number(r.target_min_g),targetMaxG:Number(r.target_max_g),gramsPerKgMin:Number(r.grams_per_kg_min),gramsPerKgMax:Number(r.grams_per_kg_max),reasonCiphertext:r.reason_ciphertext,version:r.version,updatedAt:r.updated_at});
@Injectable() export class FatTargetRepository {constructor(private readonly prisma:PrismaService){}
  async findBySubmission(submissionId:string){const rows=await this.prisma.$queryRaw<Row[]>`SELECT * FROM fat_targets WHERE submission_id=${submissionId}::uuid LIMIT 1`;return rows[0]?map(rows[0]):null;}
  async save(input:Omit<FatTargetRecord,'id'|'version'|'updatedAt'> & {expectedVersion:number;requestId:string}){return this.prisma.$transaction(async tx=>{let rows:Row[];if(input.expectedVersion===0)rows=await tx.$queryRaw<Row[]>`INSERT INTO fat_targets(client_id,submission_id,updated_by,energy_kcal,weight_kg,goal,activity,energy_percent_min,energy_percent_max,target_min_g,target_max_g,grams_per_kg_min,grams_per_kg_max,reason_ciphertext,version) VALUES(${input.clientId}::uuid,${input.submissionId}::uuid,${input.updatedBy}::uuid,${input.energyKcal},${input.weightKg},${input.goal}::fat_goal,${input.activity}::fat_activity,${input.energyPercentMin},${input.energyPercentMax},${input.targetMinG},${input.targetMaxG},${input.gramsPerKgMin},${input.gramsPerKgMax},${Buffer.from(input.reasonCiphertext)},1) ON CONFLICT(submission_id) DO NOTHING RETURNING *`;else rows=await tx.$queryRaw<Row[]>`UPDATE fat_targets SET updated_by=${input.updatedBy}::uuid,energy_kcal=${input.energyKcal},weight_kg=${input.weightKg},goal=${input.goal}::fat_goal,activity=${input.activity}::fat_activity,energy_percent_min=${input.energyPercentMin},energy_percent_max=${input.energyPercentMax},target_min_g=${input.targetMinG},target_max_g=${input.targetMaxG},grams_per_kg_min=${input.gramsPerKgMin},grams_per_kg_max=${input.gramsPerKgMax},reason_ciphertext=${Buffer.from(input.reasonCiphertext)},version=version+1,updated_at=now() WHERE submission_id=${input.submissionId}::uuid AND version=${input.expectedVersion} RETURNING *`;if(!rows[0])return null;const target=map(rows[0]);await tx.$executeRaw`INSERT INTO fat_target_versions(target_id,client_id,submission_id,updated_by,energy_kcal,weight_kg,goal,activity,energy_percent_min,energy_percent_max,target_min_g,target_max_g,grams_per_kg_min,grams_per_kg_max,reason_ciphertext,version) VALUES(${target.id}::uuid,${target.clientId}::uuid,${target.submissionId}::uuid,${target.updatedBy}::uuid,${target.energyKcal},${target.weightKg},${target.goal}::fat_goal,${target.activity}::fat_activity,${target.energyPercentMin},${target.energyPercentMax},${target.targetMinG},${target.targetMaxG},${target.gramsPerKgMin},${target.gramsPerKgMax},${Buffer.from(target.reasonCiphertext)},${target.version})`;await tx.$executeRaw`INSERT INTO audit_events(request_id,actor_user_id,actor_role,action,resource_type,resource_id,client_id,decision,reason_code) VALUES(${input.requestId},${input.updatedBy}::uuid,'consultant','fat_target.save','fat_target',${target.id}::uuid,${target.clientId}::uuid,'SUCCESS','FAT_TARGET_SAVED')`;return target;},{maxWait:5000});}
}
