type Card={id:string;name:string;totalFatPer100g?:number|null;saturatedFatPer100g?:number|null;transFatPer100g?:number|null;monounsaturatedFatPer100g?:number|null;polyunsaturatedFatPer100g?:number|null;omega3AlaPer100g?:number|null;epaPer100g?:number|null;dhaPer100g?:number|null};
const topLines=(lines:any[],field:string)=>lines.filter(l=>typeof l.nutrients?.[field]==='number'&&l.nutrients[field]>0).sort((a,b)=>b.nutrients[field]-a.nutrients[field]).slice(0,3).map(l=>({product_card_id:l.product.id,name:l.product.name,amount_g:Number(l.nutrients[field].toFixed(2))}));
const candidates=(cards:Card[],score:(c:Card)=>number)=>cards.map(c=>({c,score:score(c)})).filter(x=>Number.isFinite(x.score)&&x.score>0).sort((a,b)=>b.score-a.score).slice(0,3).map(x=>({product_card_id:x.c.id,name:x.c.name,basis_per_100g:Number(x.score.toFixed(2))}));
export function calculateFatRecommendations(calculation:any,allCards:Card[]){
  const out:any[]=[],balance=calculation.fatBalance,signals=calculation.signals,lines=calculation.lines;
  const unsaturated=candidates(allCards,c=>{const fat=c.totalFatPer100g??0,sfa=c.saturatedFatPer100g;if(!fat||sfa===null||sfa===undefined||sfa/fat>.34)return 0;return (c.monounsaturatedFatPer100g??0)+(c.polyunsaturatedFatPer100g??0);});
  if(balance.status==='insufficient_data')out.push({id:'complete_fat_data',priority:'data',action:'review',title:'Уточнить карточки продуктов',explanation:'Общий баланс жиров нельзя оценить, пока хотя бы в одной позиции неизвестно общее количество жира.',contributors:[],options:[]});
  if(balance.status==='below_range')out.push({id:'increase_total_fat',priority:'balance',action:'add_or_replace',title:'Мягко повысить количество жиров',explanation:`До нижней границы не хватает ${balance.differenceG} г. Рассмотрите ненасыщенные источники с учётом калорийности и общей структуры рациона.`,contributors:[],options:unsaturated});
  if(balance.status==='above_range')out.push({id:'reduce_total_fat',priority:'balance',action:'reduce_or_replace',title:'Снизить общее количество жиров',explanation:`Превышение верхней границы составляет ${balance.differenceG} г. Начните с проверки порций продуктов, которые внесли наибольший вклад.`,contributors:topLines(lines,'totalFatPer100g'),options:unsaturated});
  if(signals.saturated==='red_flag')out.push({id:'replace_saturated',priority:'quality',action:'replace',title:'Заменить часть насыщенных жиров',explanation:'Предпочтительна замена на полиненасыщенные жиры или мононенасыщенные жиры из растительных источников, а не простое добавление новых калорий.',contributors:topLines(lines,'saturatedFatPer100g'),options:unsaturated});
  if(signals.trans==='red_flag')out.push({id:'reduce_trans',priority:'quality',action:'reduce_or_replace',title:'Сократить источники трансжиров',explanation:'Проверьте маркировку и способ приготовления у ведущих источников; замену не следует выполнять насыщенным жиром.',contributors:topLines(lines,'transFatPer100g'),options:unsaturated});
  if(signals.omega3Ala==='below_guide')out.push({id:'improve_ala',priority:'quality',action:balance.status==='above_range'?'replace':'add_or_replace',title:'Улучшить поступление АЛК омега‑3',explanation:balance.status==='above_range'?'Используйте замену внутри текущего количества жира, не добавление сверх ориентира.':'Рассмотрите подходящий источник АЛК в структуре рациона.',contributors:[],options:candidates(allCards,c=>c.omega3AlaPer100g??0)});
  if(signals.epaDha==='below_guide')out.push({id:'improve_epa_dha',priority:'quality',action:balance.status==='above_range'?'replace':'add_or_replace',title:'Улучшить поступление EPA и DHA',explanation:balance.status==='above_range'?'Выбирайте замену существующего источника жира, чтобы не усиливать превышение.':'Рассмотрите подходящие пищевые источники EPA и DHA; индивидуальную порцию определяет консультант.',contributors:[],options:candidates(allCards,c=>(c.epaPer100g??0)+(c.dhaPer100g??0))});
  if(signals.palmitic==='research_attention')out.push({id:'review_palmitic',priority:'research',action:'review',title:'Проверить источники пальмитиновой кислоты',explanation:'Это исследовательский сигнал, не диагноз. Оцените его вместе с общей калорийностью и качеством углеводов.',contributors:topLines(lines,'palmiticAcidPer100g'),options:[]});
  return out.slice(0,6);
}
