import {HttpStatus,Injectable} from '@nestjs/common';
import type {AuthenticatedUser} from '../auth/auth.types';
import {AuthorizationPolicy} from '../authorization/authorization.policy';
import {AppError,unavailable} from '../common/app-error';
import {AssignmentRepository} from './assignment.repository';
import {calculateFatTarget,type FatActivity,type FatGoal} from './fat-target.calculator';
import {FatTargetRepository,type FatTargetRecord} from './fat-target.repository';
import {PayloadCryptoService} from './payload-crypto.service';
import {SubmissionStore} from './submission.store';
@Injectable() export class FatTargetService {constructor(private readonly store:SubmissionStore,private readonly assignments:AssignmentRepository,private readonly policy:AuthorizationPolicy,private readonly targets:FatTargetRepository,private readonly crypto:PayloadCryptoService){}
  private async requireSubmission(submissionId:string,clientId:string,user:AuthenticatedUser){this.policy.requireRole(user,'consultant');const s=await this.store.findById(submissionId);if(!s||s.clientId!==clientId)throw unavailable('SUBMISSION_NOT_FOUND');this.policy.requireActiveAssignment(user,await this.assignments.activeConsultant(clientId));if(s.status!=='accepted')throw unavailable('SUBMISSION_NOT_ACCEPTED');}
  async get(submissionId:string,clientId:string,user:AuthenticatedUser){await this.requireSubmission(submissionId,clientId,user);const target=await this.targets.findBySubmission(submissionId);if(!target)return {submission_id:submissionId,energy_kcal:null,weight_kg:null,goal:'maintain',activity:'moderate',energy_percent_min:null,energy_percent_max:null,target_min_g:null,target_max_g:null,grams_per_kg_min:null,grams_per_kg_max:null,weight_loss_guide_status:'not_applicable',reason:'',version:0,updated_at:null};return this.dto(target,await this.decryptReason(target));}
  async save(submissionId:string,clientId:string,user:AuthenticatedUser,requestId:string,expectedVersion:number,input:{energy_kcal?:unknown;weight_kg?:unknown;goal?:unknown;activity?:unknown;reason?:unknown}){await this.requireSubmission(submissionId,clientId,user);const energyKcal=Number(input.energy_kcal),weightKg=Number(input.weight_kg),goal=String(input.goal) as FatGoal,activity=String(input.activity) as FatActivity;if(typeof input.reason!=='string'||input.reason.length>1000)throw this.invalid();const calculated=calculateFatTarget(energyKcal,weightKg,goal,activity);if(!calculated)throw this.invalid();const reason=input.reason.replace(/\r\n/g,'\n').trim();const saved=await this.targets.save({clientId,submissionId,updatedBy:user.id,...calculated,reasonCiphertext:await this.crypto.encrypt(Buffer.from(reason,'utf8')),expectedVersion,requestId});if(!saved)throw new AppError('FAT_TARGET_VERSION_CONFLICT',HttpStatus.CONFLICT);return this.dto(saved,reason);}
  private invalid(){return new AppError('FAT_TARGET_INVALID',HttpStatus.BAD_REQUEST);}
  private dto(t:FatTargetRecord,reason:string){const midpoint=(t.targetMinG+t.targetMaxG)/2;return {submission_id:t.submissionId,energy_kcal:t.energyKcal,weight_kg:t.weightKg,goal:t.goal,activity:t.activity,energy_percent_min:t.energyPercentMin,energy_percent_max:t.energyPercentMax,target_min_g:t.targetMinG,target_max_g:t.targetMaxG,grams_per_kg_min:t.gramsPerKgMin,grams_per_kg_max:t.gramsPerKgMax,weight_loss_guide_status:t.goal!=='weight_loss'?'not_applicable':midpoint<50?'below_50':midpoint>60?'above_60':'within_50_60',reason,version:t.version,updated_at:t.updatedAt.toISOString()};}
  private async decryptReason(t:FatTargetRecord){try{return Buffer.from(await this.crypto.decrypt(t.reasonCiphertext)).toString('utf8');}catch{throw new AppError('FAT_TARGET_INTEGRITY_FAILED',HttpStatus.CONFLICT);}}
}
