import {Injectable} from '@nestjs/common';
import {PrismaService} from '../database/prisma.service';
import type {ProductSnapshot,ProteinOrigin} from './protein-intake.calculator';
import type {FoodMineralKey,FoodMineralValue} from './food-mineral-intake.calculator';
import {parseFoodEnrichmentProfile,type FoodEnrichmentProfile} from './food-enrichment-profile';
export type FoodMineralProfile=Partial<Record<FoodMineralKey,FoodMineralValue>>;
export type ExtendedProductSnapshot=ProductSnapshot&{starchPer100g:number|null;polyolsPer100g:number|null;resistantStarchPer100g:number|null;sugarOriginClass:string|null;carbohydrateFoodGroup:string|null;foodMatrixClass:string|null;processingClass:string|null;carbohydrateFlags:string[];carbohydrateDataReliability:string|null;mineralProfile:FoodMineralProfile;enrichmentProfile:FoodEnrichmentProfile;vitaminProfile:Record<string,unknown>};
type Row={id:string;canonical_name:string;protein_per_100g:unknown;energy_kcal_per_100g:unknown;carbohydrate_per_100g:unknown;fibre_per_100g:unknown;total_sugars_per_100g:unknown;free_sugars_per_100g:unknown;carbohydrate_source_class:string|null;carbohydrate_quality_source:string|null;starch_per_100g:unknown;polyols_per_100g:unknown;resistant_starch_per_100g:unknown;sugar_origin_class:string|null;carbohydrate_food_group:string|null;food_matrix_class:string|null;processing_class:string|null;carbohydrate_flags:string[];carbohydrate_data_reliability:string|null;origin:ProteinOrigin;plant_share_percent:number;source_label:string;source_reference:string|null;version:number;total_fat_per_100g:unknown;saturated_fat_per_100g:unknown;monounsaturated_fat_per_100g:unknown;polyunsaturated_fat_per_100g:unknown;trans_fat_per_100g:unknown;omega6_total_per_100g:unknown;omega3_total_per_100g:unknown;omega6_la_per_100g:unknown;omega3_ala_per_100g:unknown;epa_per_100g:unknown;dha_per_100g:unknown;palmitic_acid_per_100g:unknown;fat_profile_source:string|null;fat_profile_quality:string|null;fat_detail_source:string|null;fat_detail_quality:string|null;mineral_profile:unknown;enrichment_profile:unknown;vitamin_profile:unknown};
const n=(value:unknown)=>value===null?null:Number(value);
const mineralProfile=(value:unknown):FoodMineralProfile=>value&&typeof value==='object'&&!Array.isArray(value)?value as FoodMineralProfile:{};
const object=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};
const map=(r:Row):ExtendedProductSnapshot=>({id:r.id,name:r.canonical_name,proteinPer100g:Number(r.protein_per_100g),energyKcalPer100g:n(r.energy_kcal_per_100g),carbohydratePer100g:n(r.carbohydrate_per_100g),fibrePer100g:n(r.fibre_per_100g),totalSugarsPer100g:n(r.total_sugars_per_100g),freeSugarsPer100g:n(r.free_sugars_per_100g),carbohydrateSourceClass:r.carbohydrate_source_class,carbohydrateQualitySource:r.carbohydrate_quality_source,starchPer100g:n(r.starch_per_100g),polyolsPer100g:n(r.polyols_per_100g),resistantStarchPer100g:n(r.resistant_starch_per_100g),sugarOriginClass:r.sugar_origin_class,carbohydrateFoodGroup:r.carbohydrate_food_group,foodMatrixClass:r.food_matrix_class,processingClass:r.processing_class,carbohydrateFlags:r.carbohydrate_flags||[],carbohydrateDataReliability:r.carbohydrate_data_reliability,mineralProfile:mineralProfile(r.mineral_profile),enrichmentProfile:parseFoodEnrichmentProfile(r.enrichment_profile),vitaminProfile:object(r.vitamin_profile),origin:r.origin,plantSharePercent:r.plant_share_percent,sourceLabel:r.source_label,sourceReference:r.source_reference,version:r.version,totalFatPer100g:n(r.total_fat_per_100g),saturatedFatPer100g:n(r.saturated_fat_per_100g),monounsaturatedFatPer100g:n(r.monounsaturated_fat_per_100g),polyunsaturatedFatPer100g:n(r.polyunsaturated_fat_per_100g),transFatPer100g:n(r.trans_fat_per_100g),omega6TotalPer100g:n(r.omega6_total_per_100g),omega3TotalPer100g:n(r.omega3_total_per_100g),omega6LaPer100g:n(r.omega6_la_per_100g),omega3AlaPer100g:n(r.omega3_ala_per_100g),epaPer100g:n(r.epa_per_100g),dhaPer100g:n(r.dha_per_100g),palmiticAcidPer100g:n(r.palmitic_acid_per_100g),fatProfileSource:r.fat_profile_source,fatProfileQuality:r.fat_profile_quality,fatDetailSource:r.fat_detail_source,fatDetailQuality:r.fat_detail_quality});
const columns='id,canonical_name,protein_per_100g,energy_kcal_per_100g,carbohydrate_per_100g,fibre_per_100g,total_sugars_per_100g,free_sugars_per_100g,carbohydrate_source_class,carbohydrate_quality_source,starch_per_100g,polyols_per_100g,resistant_starch_per_100g,sugar_origin_class,carbohydrate_food_group,food_matrix_class,processing_class,carbohydrate_flags,carbohydrate_data_reliability,mineral_profile,enrichment_profile,vitamin_profile,origin::text,plant_share_percent,source_label,source_reference,version,total_fat_per_100g,saturated_fat_per_100g,monounsaturated_fat_per_100g,polyunsaturated_fat_per_100g,trans_fat_per_100g,omega6_total_per_100g,omega3_total_per_100g,omega6_la_per_100g,omega3_ala_per_100g,epa_per_100g,dha_per_100g,palmitic_acid_per_100g,fat_profile_source,fat_profile_quality,fat_detail_source,fat_detail_quality';
const resolvedColumns=columns.split(',').map(column=>column==='id'?'requested.id AS id':`resolved.${column}`).join(',');
@Injectable() export class FoodProductRepository{constructor(private readonly prisma:PrismaService){}async listVerified(){const rows=await this.prisma.$queryRawUnsafe<Row[]>(`SELECT ${columns} FROM food_product_cards WHERE status='verified' ORDER BY canonical_name`);return rows.map(map);}async verifiedByIds(ids:string[]){if(!ids.length)return new Map<string,ExtendedProductSnapshot>();const rows=await this.prisma.$queryRawUnsafe<Row[]>(`SELECT ${resolvedColumns} FROM food_product_cards requested JOIN food_product_cards resolved ON resolved.id=COALESCE(requested.replacement_card_id,requested.id) WHERE resolved.status='verified' AND requested.id=ANY($1::uuid[])`,ids);return new Map(rows.map(row=>[row.id,map(row)]));}}
