import {Injectable} from '@nestjs/common';
import type {FoodProductStatus,ProteinOrigin} from '@prisma/client';
import type {AuthenticatedUser} from '../auth/auth.types';
import {AuthorizationPolicy} from '../authorization/authorization.policy';
import {AuditService} from '../audit/audit.service';
import {AppError,unavailable} from '../common/app-error';
import {parseFoodEnrichmentProfile} from './food-enrichment-profile';
import {FoodProductManagementRepository,type FoodProductDraftInput} from './food-product-management.repository';
const statuses=new Set<FoodProductStatus>(['draft','verified','retired']);
const origins=new Set<ProteinOrigin>(['plant','animal','mixed']);
export const normalizeFoodProductName=(value:string)=>value.normalize('NFKC').toLocaleLowerCase('uk-UA').replace(/[’ʼ`´]/g,"'").replace(/[^a-zа-яёєіїґ'0-9]+/giu,' ').trim().replace(/\s+/g,' ');
function finite(value:unknown,field:string):number;
function finite(value:unknown,field:string,nullable:true):number|null;
function finite(value:unknown,field:string,nullable=false){if(nullable&&(value===null||value===''))return null;const result=Number(value);if(!Number.isFinite(result)||result<0||result>1000)throw new AppError(`FOOD_PRODUCT_${field}_INVALID`,400);return result;}
function text(value:unknown,field:string):string;
function text(value:unknown,field:string,nullable:true):string|null;
function text(value:unknown,field:string,nullable=false){if(nullable&&(value===null||value===undefined||value===''))return null;if(typeof value!=='string'||!value.trim())throw new AppError(`FOOD_PRODUCT_${field}_REQUIRED`,400);return value.trim();}
const profileStatuses=new Set(['analytical','calculated','borrowed','trace','missing']);
const mineralUnits={calcium:'mg',phosphorus:'mg',magnesium:'mg',iron:'mg',zinc:'mg',copper:'ug',manganese:'mg',molybdenum:'ug',sodium:'mg',potassium:'mg',selenium:'ug',iodine:'ug'} as const;
const vitaminUnits={vitamin_d:'ug',vitamin_b12:'ug',folate:'ug',vitamin_c:'mg',vitamin_a:'ug_re',vitamin_e:'mg_alpha_te',vitamin_b1:'mg',vitamin_b2:'mg',vitamin_b3:'mg_ne',vitamin_b5:'mg',vitamin_b6:'mg',vitamin_b7:'ug',vitamin_k:'ug'} as const;
const object=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==='object'&&!Array.isArray(value);
const versionFields=['canonicalName','proteinPer100g','energyKcalPer100g','carbohydratePer100g','fibrePer100g','totalFatPer100g','origin','plantSharePercent','sourceLabel','sourceReference','status','replacementCardId','verifiedBy','verifiedAt'] as const;
const same=(left:unknown,right:unknown)=>JSON.stringify(left)===JSON.stringify(right);
type VersionChange={field:string;before:unknown;after:unknown};
const profileChanges=(prefix:string,before:unknown,after:unknown):VersionChange[]=>{const left=object(before)?before:{},right=object(after)?after:{},keys=[...new Set([...Object.keys(left),...Object.keys(right)])].sort();return keys.filter(key=>!same(left[key],right[key])).map(key=>({field:`${prefix}.${key}`,before:left[key]??null,after:right[key]??null}));};
const enrichmentChanges=(before:unknown,after:unknown):VersionChange[]=>{const left=object(before)?before:{},right=object(after)?after:{},changes:VersionChange[]=[];for(const key of ['status','evidenceBasis','identityScope','marketCountries','limitation'])if(!same(left[key],right[key]))changes.push({field:`enrichmentProfile.${key}`,before:left[key]??null,after:right[key]??null});changes.push(...profileChanges('enrichmentProfile.nutrients',left.nutrients,right.nutrients));return changes;};
function nutrientProfile(value:unknown,units:Record<string,string>,code:string):Record<string,unknown>|null{
  if(value===null||value===undefined)return null;
  if(!object(value))throw new AppError(`FOOD_PRODUCT_${code}_INVALID`,400);
  for(const [key,raw] of Object.entries(value)){
    if(!(key in units)||!object(raw)||raw.unit!==units[key]||!profileStatuses.has(String(raw.status))||typeof raw.sourceName!=='string'||!raw.sourceName.trim()||typeof raw.sourceVersion!=='string'||!raw.sourceVersion.trim())throw new AppError(`FOOD_PRODUCT_${code}_INVALID`,400);
    const amount=raw.valuePer100g;
    if(raw.status==='missing'){if(amount!==null)throw new AppError(`FOOD_PRODUCT_${code}_INVALID`,400);}
    else if(raw.status==='trace'){if(amount!==null&&(typeof amount!=='number'||!Number.isFinite(amount)||amount<0))throw new AppError(`FOOD_PRODUCT_${code}_INVALID`,400);}
    else if(typeof amount!=='number'||!Number.isFinite(amount)||amount<0)throw new AppError(`FOOD_PRODUCT_${code}_INVALID`,400);
  }
  return value;
}
function enrichmentProfile(value:unknown):Record<string,unknown>|null{
  if(value===null||value===undefined)return null;
  if(!object(value))throw new AppError('FOOD_PRODUCT_ENRICHMENT_PROFILE_INVALID',400);
  const parsed=parseFoodEnrichmentProfile(value);
  if(value.status!=='unknown'&&parsed.status==='unknown')throw new AppError('FOOD_PRODUCT_ENRICHMENT_PROFILE_INVALID',400);
  return parsed as unknown as Record<string,unknown>;
}
@Injectable()
export class FoodProductManagementService{
  constructor(private readonly repository:FoodProductManagementRepository,private readonly policy:AuthorizationPolicy,private readonly audit:AuditService){}
  private requireAdmin(user:AuthenticatedUser){this.policy.requireRole(user,'admin');}
  private input(body:Record<string,unknown>):FoodProductDraftInput{const origin=body.origin;if(typeof origin!=='string'||!origins.has(origin as ProteinOrigin))throw new AppError('FOOD_PRODUCT_ORIGIN_INVALID',400);const plantSharePercent=finite(body.plant_share_percent,'PLANT_SHARE_PERCENT');if(!Number.isInteger(plantSharePercent)||plantSharePercent>100)throw new AppError('FOOD_PRODUCT_PLANT_SHARE_PERCENT_INVALID',400);if((origin==='plant'&&plantSharePercent!==100)||(origin==='animal'&&plantSharePercent!==0))throw new AppError('FOOD_PRODUCT_ORIGIN_SHARE_MISMATCH',400);return{canonicalName:text(body.canonical_name,'NAME'),proteinPer100g:finite(body.protein_per_100g,'PROTEIN'),energyKcalPer100g:finite(body.energy_kcal_per_100g,'ENERGY',true),carbohydratePer100g:finite(body.carbohydrate_per_100g,'CARBOHYDRATE',true),fibrePer100g:finite(body.fibre_per_100g,'FIBRE',true),totalFatPer100g:finite(body.total_fat_per_100g,'TOTAL_FAT',true),origin:origin as ProteinOrigin,plantSharePercent,sourceLabel:text(body.source_label,'SOURCE_LABEL'),sourceReference:text(body.source_reference,'SOURCE_REFERENCE',true),mineralProfile:nutrientProfile(body.mineral_profile,mineralUnits,'MINERAL_PROFILE'),vitaminProfile:nutrientProfile(body.vitamin_profile,vitaminUnits,'VITAMIN_PROFILE'),enrichmentProfile:enrichmentProfile(body.enrichment_profile)};}
  private async duplicateMatches(name:string,exceptId?:string){const normalized=normalizeFoodProductName(name);return (await this.repository.list()).filter(card=>card.id!==exceptId&&normalizeFoodProductName(card.canonicalName)===normalized);}
  private async ensureUnique(name:string,exceptId?:string){if((await this.duplicateMatches(name,exceptId)).length)throw new AppError('FOOD_PRODUCT_DUPLICATE_NAME',409);}
  async list(user:AuthenticatedUser,status?:string,search?:string){this.requireAdmin(user);if(status&&!statuses.has(status as FoodProductStatus))throw new AppError('FOOD_PRODUCT_STATUS_INVALID',400);return this.repository.list(status as FoodProductStatus|undefined,search?.trim()||undefined);}
  async duplicates(user:AuthenticatedUser){this.requireAdmin(user);const cards=(await this.repository.list()).filter(card=>card.status!=='retired');const groups=new Map<string,typeof cards>();for(const card of cards){const key=normalizeFoodProductName(card.canonicalName);const group=groups.get(key)??[];group.push(card);groups.set(key,group);}return{groups:[...groups.entries()].filter(([,items])=>items.length>1).map(([normalized_name,items])=>({normalized_name,items})).sort((a,b)=>a.normalized_name.localeCompare(b.normalized_name,'uk'))};}
  async syncRuns(user:AuthenticatedUser){this.requireAdmin(user);return{items:await this.repository.syncRuns()};}
  async get(user:AuthenticatedUser,id:string){this.requireAdmin(user);const result=await this.repository.find(id);if(!result)throw unavailable('FOOD_PRODUCT_NOT_FOUND');return result;}
  async history(user:AuthenticatedUser,id:string){this.requireAdmin(user);if(!await this.repository.find(id))throw unavailable('FOOD_PRODUCT_NOT_FOUND');const [events,rows]=await Promise.all([this.repository.history(id),this.repository.versions(id)]);let previous:Record<string,unknown>|null=null;const versions=rows.map(row=>{const current=object(row.snapshot)?row.snapshot:{};const changes:VersionChange[]=previous?[...versionFields.filter(field=>!same(previous?.[field],current[field])).map(field=>({field,before:previous?.[field]??null,after:current[field]??null})),...profileChanges('mineralProfile',previous.mineralProfile,current.mineralProfile),...profileChanges('vitaminProfile',previous.vitaminProfile,current.vitaminProfile),...enrichmentChanges(previous.enrichmentProfile,current.enrichmentProfile)]:[];previous=current;return{id:row.id,version:row.version,changeKind:row.changeKind,changedBy:row.changedBy,createdAt:row.createdAt,changes};});return{events,versions};}
  async create(user:AuthenticatedUser,requestId:string,body:Record<string,unknown>){this.requireAdmin(user);const input=this.input(body);await this.ensureUnique(input.canonicalName);const saved=await this.repository.create(input,user.id);await this.audit.record({requestId,actorUserId:user.id,actorRole:user.role,action:'CREATE',resourceType:'FOOD_PRODUCT',resourceId:saved.id,decision:'SUCCESS',reasonCode:'FOOD_PRODUCT_DRAFT_CREATED'});return saved;}
  async update(user:AuthenticatedUser,requestId:string,id:string,expectedVersion:number,body:Record<string,unknown>){this.requireAdmin(user);const current=await this.repository.find(id);if(!current)throw unavailable('FOOD_PRODUCT_NOT_FOUND');if(current.status!=='draft')throw new AppError('FOOD_PRODUCT_NOT_EDITABLE',409);const input=this.input(body);await this.ensureUnique(input.canonicalName,id);const saved=await this.repository.updateDraft(id,expectedVersion,input,user.id);if(!saved)throw new AppError('FOOD_PRODUCT_VERSION_CONFLICT',409);await this.audit.record({requestId,actorUserId:user.id,actorRole:user.role,action:'UPDATE',resourceType:'FOOD_PRODUCT',resourceId:id,decision:'SUCCESS',reasonCode:'FOOD_PRODUCT_DRAFT_UPDATED'});return saved;}
  async verify(user:AuthenticatedUser,requestId:string,id:string,expectedVersion:number){this.requireAdmin(user);const current=await this.repository.find(id);if(!current)throw unavailable('FOOD_PRODUCT_NOT_FOUND');if(current.status!=='draft')throw new AppError('FOOD_PRODUCT_NOT_VERIFIABLE',409);await this.ensureUnique(current.canonicalName,id);if(!current.sourceReference)throw new AppError('FOOD_PRODUCT_SOURCE_REFERENCE_REQUIRED',400);const saved=await this.repository.verify(id,expectedVersion,user.id);if(!saved)throw new AppError('FOOD_PRODUCT_VERSION_CONFLICT',409);await this.audit.record({requestId,actorUserId:user.id,actorRole:user.role,action:'VERIFY',resourceType:'FOOD_PRODUCT',resourceId:id,decision:'SUCCESS',reasonCode:'FOOD_PRODUCT_VERIFIED'});return saved;}
  async merge(user:AuthenticatedUser,requestId:string,duplicateId:string,duplicateVersion:number,primaryId:unknown,primaryVersion:unknown){this.requireAdmin(user);if(typeof primaryId!=='string'||primaryId===duplicateId)throw new AppError('FOOD_PRODUCT_MERGE_TARGET_INVALID',400);const targetVersion=Number(primaryVersion);if(!Number.isInteger(targetVersion)||targetVersion<1)throw new AppError('FOOD_PRODUCT_MERGE_TARGET_VERSION_INVALID',400);const [duplicate,primary]=await Promise.all([this.repository.find(duplicateId),this.repository.find(primaryId)]);if(!duplicate||!primary)throw unavailable('FOOD_PRODUCT_NOT_FOUND');if(duplicate.status==='retired')throw new AppError('FOOD_PRODUCT_ALREADY_RETIRED',409);if(primary.status!=='verified')throw new AppError('FOOD_PRODUCT_MERGE_TARGET_NOT_VERIFIED',409);if(normalizeFoodProductName(duplicate.canonicalName)!==normalizeFoodProductName(primary.canonicalName))throw new AppError('FOOD_PRODUCT_MERGE_GROUP_MISMATCH',409);const merged=await this.repository.mergeDuplicate(duplicateId,duplicateVersion,primaryId,targetVersion,user.id);if(!merged)throw new AppError('FOOD_PRODUCT_VERSION_CONFLICT',409);await this.audit.record({requestId,actorUserId:user.id,actorRole:user.role,action:'MERGE',resourceType:'FOOD_PRODUCT',resourceId:duplicateId,decision:'SUCCESS',reasonCode:'FOOD_PRODUCT_DUPLICATE_MERGED'});return merged;}
}
