import {describe,expect,it} from 'vitest';
import type {AuthenticatedUser} from '../auth/auth.types';
import {AuthorizationPolicy} from '../authorization/authorization.policy';
import {FoodProductManagementService,normalizeFoodProductName} from './food-product-management.service';
const admin:AuthenticatedUser={id:'00000000-0000-0000-0000-000000000001',authSubject:'admin',role:'admin',status:'active',sessionIssuedAt:new Date(),sessionRevokedAt:null};
const consultant={...admin,role:'consultant' as const};
const input={canonical_name:' Гречка варена ',protein_per_100g:3.4,energy_kcal_per_100g:110,carbohydrate_per_100g:21.3,fibre_per_100g:2.7,total_fat_per_100g:1,origin:'plant',plant_share_percent:100,source_label:'Джерело',source_reference:'https://example.test/source'};
const card={id:'00000000-0000-0000-0000-000000000010',canonicalName:'Гречка варена',proteinPer100g:3.4,energyKcalPer100g:110,carbohydratePer100g:21.3,fibrePer100g:2.7,totalFatPer100g:1,origin:'plant' as const,plantSharePercent:100,sourceLabel:'Джерело',sourceReference:'https://example.test/source',status:'draft' as const,createdBy:admin.id,verifiedBy:null,verifiedAt:null,createdAt:new Date(),updatedAt:new Date(),version:1};
function setup(overrides:Record<string,unknown>={}){const events:unknown[]=[];const repository={list:async()=>[],find:async()=>card,history:async()=>[{id:'event-1',action:'CREATE',reasonCode:'FOOD_PRODUCT_DRAFT_CREATED'}],versions:async()=>[{id:'version-1',version:1,changeKind:'CREATE',changedBy:admin.id,createdAt:new Date('2026-01-01'),snapshot:{canonicalName:'Гречка варена',status:'draft'}},{id:'version-2',version:2,changeKind:'UPDATE',changedBy:admin.id,createdAt:new Date('2026-01-02'),snapshot:{canonicalName:'Гречка варёная',status:'draft'}}],duplicateName:async()=>[],create:async()=>card,updateDraft:async()=>({...card,version:2}),verify:async()=>({...card,status:'verified',version:2}),mergeDuplicate:async()=>({primary:{...card,status:'verified'},duplicate:{...card,status:'retired'}}),...overrides};return{service:new FoodProductManagementService(repository as never,new AuthorizationPolicy(),{record:async(event:unknown)=>{events.push(event);}} as never),events};}
describe('food product management',()=>{
  it('normalizes Ukrainian names, spacing, punctuation and apostrophe variants',()=>expect(normalizeFoodProductName("  М’ЯСО,  куряче ")).toBe("м'ясо куряче"));
  it('creates a normalized draft and records the action',async()=>{const {service,events}=setup();await expect(service.create(admin,'req-1',input)).resolves.toMatchObject({status:'draft'});expect(events).toHaveLength(1);});
  it('only permits administrators',async()=>{await expect(setup().service.list(consultant)).rejects.toThrow('RESOURCE_UNAVAILABLE');});
  it('rejects a normalized duplicate name',async()=>{await expect(setup({list:async()=>[{...card,canonicalName:'  гречка   варена '}]}).service.create(admin,'req',input)).rejects.toThrow('FOOD_PRODUCT_DUPLICATE_NAME');});
  it('groups existing normalized duplicates for manual resolution',async()=>{const duplicate={...card,id:'00000000-0000-0000-0000-000000000011',canonicalName:' гречка  варена '};const result=await setup({list:async()=>[card,duplicate]}).service.duplicates(admin);expect(result.groups).toHaveLength(1);expect(result.groups[0].items).toHaveLength(2);});
  it('returns audit events and field-level version comparisons only to administrators',async()=>{const {service}=setup();await expect(service.history(admin,card.id)).resolves.toMatchObject({events:[{action:'CREATE'}],versions:[{version:1,changes:[]},{version:2,changes:[{field:'canonicalName',before:'Гречка варена',after:'Гречка варёная'}]}]});await expect(service.history(consultant,card.id)).rejects.toThrow('RESOURCE_UNAVAILABLE');});
  it('compares nutrients separately instead of returning whole profile JSON',async()=>{const versions=[{id:'v1',version:1,changeKind:'CREATE',changedBy:admin.id,createdAt:new Date(),snapshot:{mineralProfile:{calcium:{valuePer100g:100,unit:'mg',status:'analytical'}},vitaminProfile:{vitamin_d:{valuePer100g:1,unit:'ug',status:'analytical'}},enrichmentProfile:{status:'unknown',evidenceBasis:'none',identityScope:'generic',marketCountries:[],nutrients:{},limitation:null}}},{id:'v2',version:2,changeKind:'UPDATE',changedBy:admin.id,createdAt:new Date(),snapshot:{mineralProfile:{calcium:{valuePer100g:120,unit:'mg',status:'analytical'},iron:{valuePer100g:2,unit:'mg',status:'calculated'}},vitaminProfile:{vitamin_d:{valuePer100g:1.5,unit:'ug',status:'analytical'}},enrichmentProfile:{status:'confirmed_fortified',evidenceBasis:'label',identityScope:'exact_product',marketCountries:['UA'],nutrients:{vitamin_d:{addedPer100g:1,unit:'ug',sourceName:'Этикетка',sourceVersion:'1'}},limitation:null}}}];const result=await setup({versions:async()=>versions}).service.history(admin,card.id);const fields=result.versions[1].changes.map(change=>change.field);expect(fields).toContain('mineralProfile.calcium');expect(fields).toContain('mineralProfile.iron');expect(fields).toContain('vitaminProfile.vitamin_d');expect(fields).toContain('enrichmentProfile.nutrients.vitamin_d');expect(fields).not.toContain('mineralProfile');expect(fields).not.toContain('enrichmentProfile');});
  it('requires a source reference before verification',async()=>{await expect(setup({find:async()=>({...card,sourceReference:null})}).service.verify(admin,'req',card.id,1)).rejects.toThrow('FOOD_PRODUCT_SOURCE_REFERENCE_REQUIRED');});
  it('reports concurrent draft updates',async()=>{await expect(setup({updateDraft:async()=>null}).service.update(admin,'req',card.id,1,input)).rejects.toThrow('FOOD_PRODUCT_VERSION_CONFLICT');});
  it('validates origin and plant share together',async()=>{await expect(setup().service.create(admin,'req',{...input,plant_share_percent:50})).rejects.toThrow('FOOD_PRODUCT_ORIGIN_SHARE_MISMATCH');});
  it('accepts supported nutrient profiles without dropping explicit missing values',async()=>{let saved:Record<string,unknown>|undefined;const profile={calcium:{valuePer100g:null,unit:'mg',status:'missing',sourceName:'Джерело',sourceVersion:'2026'}};const {service}=setup({create:async(value:Record<string,unknown>)=>{saved=value;return card;}});await service.create(admin,'req',{...input,mineral_profile:profile});expect(saved?.mineralProfile).toEqual(profile);});
  it('rejects an incorrect unit in a nutrient profile',async()=>{const profile={calcium:{valuePer100g:120,unit:'ug',status:'analytical',sourceName:'Джерело',sourceVersion:'2026'}};await expect(setup().service.create(admin,'req',{...input,mineral_profile:profile})).rejects.toThrow('FOOD_PRODUCT_MINERAL_PROFILE_INVALID');});
  it('rejects an unsubstantiated confirmed enrichment profile',async()=>{const profile={status:'confirmed_fortified',evidenceBasis:'none',identityScope:'generic',marketCountries:[],nutrients:{}};await expect(setup().service.create(admin,'req',{...input,enrichment_profile:profile})).rejects.toThrow('FOOD_PRODUCT_ENRICHMENT_PROFILE_INVALID');});
  it('merges a duplicate only into a verified card from the same normalized group',async()=>{const primary={...card,id:'00000000-0000-0000-0000-000000000011',canonicalName:'Гречка  варена',status:'verified' as const,version:3};const {service,events}=setup({find:async(id:string)=>id===primary.id?primary:card});await expect(service.merge(admin,'req',card.id,1,primary.id,3)).resolves.toMatchObject({duplicate:{status:'retired'}});expect(events[0]).toMatchObject({action:'MERGE',reasonCode:'FOOD_PRODUCT_DUPLICATE_MERGED'});});
  it('rejects a merge into an unverified or unrelated card',async()=>{const other={...card,id:'00000000-0000-0000-0000-000000000012',canonicalName:'Рис',status:'verified' as const};await expect(setup({find:async(id:string)=>id===other.id?other:card}).service.merge(admin,'req',card.id,1,other.id,1)).rejects.toThrow('FOOD_PRODUCT_MERGE_GROUP_MISMATCH');});
});
