import {Injectable} from '@nestjs/common';
import {Prisma, type FoodProductStatus, type ProteinOrigin} from '@prisma/client';
import {PrismaService} from '../database/prisma.service';

export type ManagedFoodProduct={id:string;canonicalName:string;proteinPer100g:number;energyKcalPer100g:number|null;carbohydratePer100g:number|null;fibrePer100g:number|null;totalFatPer100g:number|null;origin:ProteinOrigin;plantSharePercent:number;sourceLabel:string;sourceReference:string|null;mineralProfile:unknown;vitaminProfile:unknown;enrichmentProfile:unknown;status:FoodProductStatus;replacementCardId:string|null;createdBy:string;verifiedBy:string|null;verifiedAt:Date|null;createdAt:Date;updatedAt:Date;version:number};
export type FoodProductDraftInput={canonicalName:string;proteinPer100g:number;energyKcalPer100g:number|null;carbohydratePer100g:number|null;fibrePer100g:number|null;totalFatPer100g:number|null;origin:ProteinOrigin;plantSharePercent:number;sourceLabel:string;sourceReference:string|null;mineralProfile:Record<string,unknown>|null;vitaminProfile:Record<string,unknown>|null;enrichmentProfile:Record<string,unknown>|null};
const selection={id:true,canonicalName:true,proteinPer100g:true,energyKcalPer100g:true,carbohydratePer100g:true,fibrePer100g:true,totalFatPer100g:true,origin:true,plantSharePercent:true,sourceLabel:true,sourceReference:true,mineralProfile:true,vitaminProfile:true,enrichmentProfile:true,status:true,replacementCardId:true,createdBy:true,verifiedBy:true,verifiedAt:true,createdAt:true,updatedAt:true,version:true} satisfies Prisma.FoodProductCardSelect;
type Selected=Prisma.FoodProductCardGetPayload<{select:typeof selection}>;
const number=(value:Prisma.Decimal|null)=>value===null?null:value.toNumber();
const map=(row:Selected):ManagedFoodProduct=>({...row,proteinPer100g:row.proteinPer100g.toNumber(),energyKcalPer100g:number(row.energyKcalPer100g),carbohydratePer100g:number(row.carbohydratePer100g),fibrePer100g:number(row.fibrePer100g),totalFatPer100g:number(row.totalFatPer100g)});

@Injectable()
export class FoodProductManagementRepository{
  constructor(private readonly prisma:PrismaService){}
  async list(status?:FoodProductStatus,search?:string){const rows=await this.prisma.foodProductCard.findMany({where:{...(status?{status}:{}),...(search?{canonicalName:{contains:search,mode:'insensitive'}}:{})},select:selection,orderBy:{canonicalName:'asc'}});return rows.map(map);}
  async find(id:string){const row=await this.prisma.foodProductCard.findUnique({where:{id},select:selection});return row?map(row):null;}
  async history(id:string){return this.prisma.auditEvent.findMany({where:{resourceType:'FOOD_PRODUCT',resourceId:id},select:{id:true,occurredAt:true,actorUserId:true,actorRole:true,action:true,decision:true,reasonCode:true},orderBy:{occurredAt:'desc'},take:100});}
  async versions(id:string){return this.prisma.foodProductCardVersion.findMany({where:{cardId:id},select:{id:true,version:true,changeKind:true,changedBy:true,snapshot:true,createdAt:true},orderBy:{version:'asc'},take:100});}
  async syncRuns(){return this.prisma.foodCatalogSyncRun.findMany({select:{operation:true,status:true,resultSummary:true,integritySummary:true,errorCode:true,startedAt:true,completedAt:true},orderBy:{startedAt:'desc'},take:50});}
  async duplicateName(canonicalName:string,exceptId?:string){return this.prisma.$queryRaw<{id:string;canonical_name:string;status:FoodProductStatus}[]>`SELECT id,canonical_name,status FROM food_product_cards WHERE lower(trim(canonical_name))=lower(trim(${canonicalName})) AND (${exceptId??null}::uuid IS NULL OR id<>${exceptId??null}::uuid) ORDER BY status,canonical_name`;}
  private data(input:FoodProductDraftInput){return{...input,mineralProfile:input.mineralProfile as Prisma.InputJsonObject|null??Prisma.DbNull,vitaminProfile:input.vitaminProfile as Prisma.InputJsonObject|null??Prisma.DbNull,enrichmentProfile:input.enrichmentProfile as Prisma.InputJsonObject|null??Prisma.DbNull};}
  private async metadata(tx:Prisma.TransactionClient,kind:string,actor?:string){await tx.$queryRaw`SELECT set_config('app.food_product_change_kind', ${kind}, true), set_config('app.food_product_changed_by', ${actor??''}, true)`;}
  async create(input:FoodProductDraftInput,createdBy:string){return this.prisma.$transaction(async tx=>{await this.metadata(tx,'CREATE',createdBy);return map(await tx.foodProductCard.create({data:{...this.data(input),createdBy,status:'draft'},select:selection}));});}
  async updateDraft(id:string,expectedVersion:number,input:FoodProductDraftInput,changedBy?:string){return this.prisma.$transaction(async tx=>{await this.metadata(tx,'UPDATE',changedBy);const changed=await tx.foodProductCard.updateMany({where:{id,status:'draft',version:expectedVersion},data:{...this.data(input),version:{increment:1}}});if(changed.count!==1)return null;return map(await tx.foodProductCard.findUniqueOrThrow({where:{id},select:selection}));});}
  async verify(id:string,expectedVersion:number,verifiedBy:string){return this.prisma.$transaction(async tx=>{await this.metadata(tx,'VERIFY',verifiedBy);const changed=await tx.foodProductCard.updateMany({where:{id,status:'draft',version:expectedVersion},data:{status:'verified',verifiedBy,verifiedAt:new Date(),version:{increment:1}}});if(changed.count!==1)return null;return map(await tx.foodProductCard.findUniqueOrThrow({where:{id},select:selection}));});}
  async mergeDuplicate(duplicateId:string,duplicateVersion:number,primaryId:string,primaryVersion:number,changedBy?:string){return this.prisma.$transaction(async tx=>{await this.metadata(tx,'MERGE',changedBy);const primary=await tx.foodProductCard.findFirst({where:{id:primaryId,status:'verified',version:primaryVersion},select:selection});if(!primary)return null;const changed=await tx.foodProductCard.updateMany({where:{id:duplicateId,version:duplicateVersion,status:{not:'retired'}},data:{status:'retired',replacementCardId:primaryId,version:{increment:1}}});if(changed.count!==1)return null;const duplicate=map(await tx.foodProductCard.findUniqueOrThrow({where:{id:duplicateId},select:selection}));return{primary:map(primary),duplicate};});}
}
