import { Module } from '@nestjs/common';
import { ImportPreviewController } from './import-preview.controller';
import { ImportPreviewService } from './import-preview.service';
import { PayloadCryptoService } from './payload-crypto.service';
import { PrismaSubmissionStore } from './prisma-submission.store';
import { SubmissionStore } from './submission.store';
import { AssignmentRepository } from './assignment.repository';
import { SubmissionWorkflowController } from './submission-workflow.controller';
import { SubmissionWorkflowService } from './submission-workflow.service';
import { CsvParserService } from './csv-parser.service';
import { ImportRateLimiterService } from './import-rate-limiter.service';
import { SubmissionHistoryController } from './submission-history.controller';
import { SubmissionHistoryRepository } from './submission-history.repository';
import { AuthorizationModule } from '../authorization/authorization.module';
import { AuditModule } from '../audit/audit.module';
import { SubmissionAnalysisController } from './submission-analysis.controller';
import { SubmissionAnalysisService } from './submission-analysis.service';
import { ConsultantNoteController } from './consultant-note.controller';
import { ConsultantNoteService } from './consultant-note.service';
import { ConsultantNoteRepository } from './consultant-note.repository';
import { ConsultationBookingController } from './consultation-booking.controller';
import { ConsultationBookingService } from './consultation-booking.service';
import { ConsultationBookingRepository } from './consultation-booking.repository';
import { ProteinTargetController } from './protein-target.controller';
import { ProteinTargetService } from './protein-target.service';
import { ProteinTargetRepository } from './protein-target.repository';
import { ProteinIntakeController } from './protein-intake.controller';
import { ProteinIntakeService } from './protein-intake.service';
import { ProteinIntakeRepository } from './protein-intake.repository';
import { FoodProductRepository } from './food-product.repository';
import {FatTargetController} from './fat-target.controller';
import {FatTargetService} from './fat-target.service';
import {FatTargetRepository} from './fat-target.repository';
import {FatIntakeController} from './fat-intake.controller';
import {FatIntakeService} from './fat-intake.service';
import {NutrientClientPublicationRepository} from './nutrient-client-publication.repository';
import {NutrientClientPublicationController} from './nutrient-client-publication.controller';
import {NutrientClientPublicationService} from './nutrient-client-publication.service';
import {NutritionSummaryController} from './nutrition-summary.controller';
import {NutritionSummaryService} from './nutrition-summary.service';
import {CarbohydrateIntakeController} from './carbohydrate-intake.controller';
import {CarbohydrateIntakeService} from './carbohydrate-intake.service';
import {RegionalNutrientController} from './regional-nutrient.controller';
import {RegionalNutrientService} from './regional-nutrient.service';
import {RegionalNutrientSettingsRepository} from './regional-nutrient-settings.repository';
import {FoodMineralIntakeController} from './food-mineral-intake.controller';
import {FoodMineralIntakeService} from './food-mineral-intake.service';
import {MineralTargetSettingsController} from './mineral-target-settings.controller';
import {MineralTargetSettingsService} from './mineral-target-settings.service';
import {MineralTargetSettingsRepository} from './mineral-target-settings.repository';
import {MineralClientExplanationController} from './mineral-client-explanation.controller';
import {MineralClientExplanationService} from './mineral-client-explanation.service';
import {SodiumPotassiumController} from './sodium-potassium.controller';
import {SodiumPotassiumService} from './sodium-potassium.service';
import {VitaminDIntakeController} from './vitamin-d-intake.controller';
import {VitaminDIntakeService} from './vitamin-d-intake.service';
import {VitaminDClientExplanationController} from './vitamin-d-client-explanation.controller';
import {VitaminDClientExplanationService} from './vitamin-d-client-explanation.service';
import {B12FolateIntakeController} from './b12-folate-intake.controller';
import {B12FolateIntakeService} from './b12-folate-intake.service';
import {B12FolateClientExplanationController} from './b12-folate-client-explanation.controller';
import {B12FolateClientExplanationService} from './b12-folate-client-explanation.service';
import {VitaminCIntakeController} from './vitamin-c-intake.controller';
import {VitaminCIntakeService} from './vitamin-c-intake.service';
import {VitaminCClientExplanationController} from './vitamin-c-client-explanation.controller';
import {VitaminCClientExplanationService} from './vitamin-c-client-explanation.service';
import {VitaminAIntakeController} from './vitamin-a-intake.controller';
import {VitaminAIntakeService} from './vitamin-a-intake.service';
import {VitaminAClientExplanationController} from './vitamin-a-client-explanation.controller';
import {VitaminAClientExplanationService} from './vitamin-a-client-explanation.service';
import {VitaminEIntakeController} from './vitamin-e-intake.controller';
import {VitaminEIntakeService} from './vitamin-e-intake.service';
import {VitaminEClientExplanationController} from './vitamin-e-client-explanation.controller';
import {VitaminEClientExplanationService} from './vitamin-e-client-explanation.service';
import {VitaminB1IntakeController} from './vitamin-b1-intake.controller';
import {VitaminB1IntakeService} from './vitamin-b1-intake.service';
import {VitaminB1ClientExplanationController} from './vitamin-b1-client-explanation.controller';
import {VitaminB1ClientExplanationService} from './vitamin-b1-client-explanation.service';
import {VitaminB2IntakeController} from './vitamin-b2-intake.controller';
import {VitaminB2IntakeService} from './vitamin-b2-intake.service';
import {VitaminB2ClientExplanationController} from './vitamin-b2-client-explanation.controller';
import {VitaminB2ClientExplanationService} from './vitamin-b2-client-explanation.service';
import {VitaminB3IntakeController} from './vitamin-b3-intake.controller';
import {VitaminB3IntakeService} from './vitamin-b3-intake.service';
import {VitaminB3ClientExplanationController} from './vitamin-b3-client-explanation.controller';
import {VitaminB3ClientExplanationService} from './vitamin-b3-client-explanation.service';
import {VitaminB5IntakeController} from './vitamin-b5-intake.controller';
import {VitaminB5IntakeService} from './vitamin-b5-intake.service';
import {VitaminB5ClientExplanationController} from './vitamin-b5-client-explanation.controller';
import {VitaminB5ClientExplanationService} from './vitamin-b5-client-explanation.service';
import {VitaminB6IntakeController} from './vitamin-b6-intake.controller';
import {VitaminB6IntakeService} from './vitamin-b6-intake.service';
import {VitaminB6ClientExplanationController} from './vitamin-b6-client-explanation.controller';
import {VitaminB6ClientExplanationService} from './vitamin-b6-client-explanation.service';
import {VitaminB7IntakeController} from './vitamin-b7-intake.controller';
import {VitaminB7IntakeService} from './vitamin-b7-intake.service';
import {VitaminB7ClientExplanationController} from './vitamin-b7-client-explanation.controller';
import {VitaminB7ClientExplanationService} from './vitamin-b7-client-explanation.service';
import {VitaminKIntakeController} from './vitamin-k-intake.controller';
import {VitaminKIntakeService} from './vitamin-k-intake.service';
import {VitaminKClientExplanationController} from './vitamin-k-client-explanation.controller';
import {VitaminKClientExplanationService} from './vitamin-k-client-explanation.service';
import {PralController} from './pral.controller';
import {PralService} from './pral.service';
import {OxalateCalciumController} from './oxalate-calcium.controller';
import {OxalateCalciumService} from './oxalate-calcium.service';
import {CalciumPhosphorusAdditivesController} from './calcium-phosphorus-additives.controller';
import {CalciumPhosphorusAdditivesService} from './calcium-phosphorus-additives.service';
import {PurineLoadController} from './purine-load.controller';
import {PurineLoadService} from './purine-load.service';
import{ProfessionalPriorityReviewRepository}from'./professional-priority-review.repository';
import{ProfessionalPriorityReviewService}from'./professional-priority-review.service';
import{ProfessionalConclusionDraftRepository}from'./professional-conclusion-draft.repository';
import{ProfessionalConclusionDraftService}from'./professional-conclusion-draft.service';
import{FoodProductManagementController}from'./food-product-management.controller';
import{FoodProductManagementService}from'./food-product-management.service';
import{FoodProductManagementRepository}from'./food-product-management.repository';

@Module({ imports:[AuthorizationModule,AuditModule], controllers:[FoodProductManagementController,ImportPreviewController,SubmissionWorkflowController,SubmissionHistoryController,SubmissionAnalysisController,ConsultantNoteController,ConsultationBookingController,ProteinTargetController,ProteinIntakeController,FatTargetController,FatIntakeController,CarbohydrateIntakeController,NutrientClientPublicationController,NutritionSummaryController,RegionalNutrientController,FoodMineralIntakeController,MineralTargetSettingsController,MineralClientExplanationController,SodiumPotassiumController,PralController,OxalateCalciumController,CalciumPhosphorusAdditivesController,PurineLoadController,VitaminDIntakeController,VitaminDClientExplanationController,B12FolateIntakeController,B12FolateClientExplanationController,VitaminCIntakeController,VitaminCClientExplanationController,VitaminAIntakeController,VitaminAClientExplanationController,VitaminEIntakeController,VitaminEClientExplanationController,VitaminB1IntakeController,VitaminB1ClientExplanationController,VitaminB2IntakeController,VitaminB2ClientExplanationController,VitaminB3IntakeController,VitaminB3ClientExplanationController,VitaminB5IntakeController,VitaminB5ClientExplanationController,VitaminB6IntakeController,VitaminB6ClientExplanationController,VitaminB7IntakeController,VitaminB7ClientExplanationController,VitaminKIntakeController,VitaminKClientExplanationController], providers:[ImportPreviewService,SubmissionWorkflowService,SubmissionAnalysisService,ConsultantNoteService,ConsultantNoteRepository,ConsultationBookingService,ConsultationBookingRepository,ProteinTargetService,ProteinTargetRepository,ProteinIntakeService,ProteinIntakeRepository,FoodProductRepository,FatTargetService,FatTargetRepository,FatIntakeService,CarbohydrateIntakeService,NutrientClientPublicationRepository,NutrientClientPublicationService,NutritionSummaryService,ProfessionalPriorityReviewService,ProfessionalPriorityReviewRepository,RegionalNutrientService,RegionalNutrientSettingsRepository,FoodMineralIntakeService,MineralTargetSettingsService,MineralTargetSettingsRepository,MineralClientExplanationService,SodiumPotassiumService,PralService,OxalateCalciumService,CalciumPhosphorusAdditivesService,PurineLoadService,VitaminDIntakeService,VitaminDClientExplanationService,B12FolateIntakeService,B12FolateClientExplanationService,VitaminCIntakeService,VitaminCClientExplanationService,VitaminAIntakeService,VitaminAClientExplanationService,VitaminEIntakeService,VitaminEClientExplanationService,VitaminB1IntakeService,VitaminB1ClientExplanationService,VitaminB2IntakeService,VitaminB2ClientExplanationService,VitaminB3IntakeService,VitaminB3ClientExplanationService,VitaminB5IntakeService,VitaminB5ClientExplanationService,VitaminB6IntakeService,VitaminB6ClientExplanationService,VitaminB7IntakeService,VitaminB7ClientExplanationService,VitaminKIntakeService,VitaminKClientExplanationService,CsvParserService,ImportRateLimiterService,PayloadCryptoService,AssignmentRepository,SubmissionHistoryRepository,
  FoodProductManagementService,FoodProductManagementRepository,ProfessionalConclusionDraftService,ProfessionalConclusionDraftRepository,PrismaSubmissionStore,{provide:SubmissionStore,useExisting:PrismaSubmissionStore}] })
export class ImportsModule {}
