import {describe,expect,it} from 'vitest';
import {calculateMineralClientExplanation,isMineralExplanationApprovalCurrent} from './mineral-client-explanation.calculator';

describe('mineral client explanation',()=>{
  it('includes reliable neutral facts and excludes blocked mineral conclusions',()=>{const result=calculateMineralClientExplanation({magnesium:{status:'below_target',completeness:{sufficient:true}},copper:{status:'insufficient_data',completeness:{sufficient:false}},iodine:{status:'uncertain_boundary',decisionBlockedByUncertainty:true}});const text=JSON.stringify(result);expect(text).toContain('магния');expect(text).toContain('Часть минералов не включена');expect(text).not.toContain('поступление меди');expect(text).not.toContain('поступление йода');expect(text).not.toMatch(/дефицит|лечение|принимайте/i);expect(result.disclaimer).toBe('');});
  it('includes manganese only after its quality gate passes',()=>{const reliable=JSON.stringify(calculateMineralClientExplanation({manganese:{status:'markedly_below_target',completeness:{sufficient:true}}})),blocked=JSON.stringify(calculateMineralClientExplanation({manganese:{status:'insufficient_data',completeness:{sufficient:false}}}));expect(reliable).toContain('марганца');expect(blocked).not.toContain('поступление марганца');});
  it('does not publish a molybdenum conclusion while coverage is insufficient',()=>{const text=JSON.stringify(calculateMineralClientExplanation({molybdenum:{status:'insufficient_data',completeness:{sufficient:false}}}));expect(text).not.toContain('поступление молибдена');expect(text).toContain('исходных данных недостаточно');});
  it('invalidates approval after intake, target or text changes',()=>{const approval={sourceIntakeVersion:2,targetVersion:3,explanationHash:'hash'};expect(isMineralExplanationApprovalCurrent(approval,2,3,'hash')).toBe(true);expect(isMineralExplanationApprovalCurrent(approval,3,3,'hash')).toBe(false);expect(isMineralExplanationApprovalCurrent(approval,2,4,'hash')).toBe(false);expect(isMineralExplanationApprovalCurrent(approval,2,3,'changed')).toBe(false);});
});
