import {Injectable} from '@nestjs/common';import {PrismaService} from '../database/prisma.service';
export type NutrientExplanationApproval={id:string;clientId:string;submissionId:string;nutrientKey:string;sourceIntakeVersion:number;targetVersion:number;explanationHash:string;explanationCiphertext:Uint8Array|null;approvedBy:string;approvedAt:Date;version:number;updatedAt:Date};
type Row={id:string;client_id:string;submission_id:string;nutrient_key:string;source_intake_version:number;target_version:number;explanation_hash:string;explanation_ciphertext:Uint8Array|null;approved_by:string;approved_at:Date;version:number;updated_at:Date};
const map=(r:Row):NutrientExplanationApproval=>({id:r.id,clientId:r.client_id,submissionId:r.submission_id,nutrientKey:r.nutrient_key,sourceIntakeVersion:r.source_intake_version,targetVersion:r.target_version,explanationHash:r.explanation_hash,explanationCiphertext:r.explanation_ciphertext,approvedBy:r.approved_by,approvedAt:r.approved_at,version:r.version,updatedAt:r.updated_at});
@Injectable() export class NutrientClientPublicationRepository{constructor(private readonly prisma:PrismaService){}
  async find(submissionId:string,nutrientKey:string){const rows=await this.prisma.$queryRaw<Row[]>`SELECT * FROM nutrient_client_explanation_approvals WHERE submission_id=${submissionId}::uuid AND nutrient_key=${nutrientKey} LIMIT 1`;return rows[0]?map(rows[0]):null;}
  async clientScope(submissionId:string,userId:string){const rows=await this.prisma.$queryRaw<{client_id:string}[]>`SELECT s.client_id FROM form_submissions s JOIN clients c ON c.id=s.client_id WHERE s.id=${submissionId}::uuid AND c.owner_user_id=${userId}::uuid LIMIT 1`;return rows[0]?.client_id??null;}
  async currentFoodIntakeVersion(submissionId:string){const rows=await this.prisma.$queryRaw<{intake_version:number;target_version:number}[]>`SELECT i.version intake_version,0::int target_version FROM protein_intake_assessments i WHERE i.submission_id=${submissionId}::uuid`;return rows[0]??null;}
  async currentVersions(submissionId:string,nutrientKey:string){if(nutrientKey==='protein'){const rows=await this.prisma.$queryRaw<{intake_version:number;target_version:number}[]>`SELECT i.version intake_version,COALESCE(t.version,0) target_version FROM protein_intake_assessments i LEFT JOIN protein_targets t ON t.submission_id=i.submission_id WHERE i.submission_id=${submissionId}::uuid`;return rows[0]??null;}if(nutrientKey==='fat'||nutrientKey==='carbohydrate'){const rows=await this.prisma.$queryRaw<{intake_version:number;target_version:number}[]>`SELECT i.version intake_version,COALESCE(t.version,0) target_version FROM protein_intake_assessments i LEFT JOIN fat_targets t ON t.submission_id=i.submission_id WHERE i.submission_id=${submissionId}::uuid`;return rows[0]??null;}if(nutrientKey==='b12_folate'||nutrientKey==='vitamin_c'||nutrientKey==='vitamin_a'||nutrientKey==='vitamin_e'||nutrientKey==='vitamin_b1'||nutrientKey==='vitamin_b2'||nutrientKey==='vitamin_b3'||nutrientKey==='vitamin_b5'||nutrientKey==='vitamin_b6'){const rows=await this.prisma.$queryRaw<{intake_version:number;target_version:number}[]>`SELECT i.version intake_version,0::int target_version FROM protein_intake_assessments i WHERE i.submission_id=${submissionId}::uuid`;return rows[0]??null;}if(nutrientKey==='minerals'){const rows=await this.prisma.$queryRaw<{intake_version:number;target_version:number}[]>`SELECT i.version intake_version,(COALESCE(t.version,0)*1000000+COALESCE(cr.version,0)*1000+COALESCE(sr.version,0))::int target_version FROM protein_intake_assessments i JOIN form_submissions s ON s.id=i.submission_id LEFT JOIN client_mineral_targets t ON t.client_id=s.client_id LEFT JOIN client_regional_nutrient_settings cr ON cr.client_id=s.client_id LEFT JOIN submission_regional_nutrient_settings sr ON sr.submission_id=s.id WHERE i.submission_id=${submissionId}::uuid`;return rows[0]??null;}return null;}
  async approve(input:{clientId:string;submissionId:string;nutrientKey:string;sourceIntakeVersion:number;targetVersion:number;explanationHash:string;explanationCiphertext:Uint8Array;approvedBy:string;expectedVersion:number;requestId:string}){return this.prisma.$transaction(async tx=>{let rows:Row[];if(input.expectedVersion===0)rows=await tx.$queryRaw<Row[]>`INSERT INTO nutrient_client_explanation_approvals(client_id,submission_id,nutrient_key,source_intake_version,target_version,explanation_hash,explanation_ciphertext,approved_by,version) VALUES(${input.clientId}::uuid,${input.submissionId}::uuid,${input.nutrientKey},${input.sourceIntakeVersion},${input.targetVersion},${input.explanationHash},${Buffer.from(input.explanationCiphertext)},${input.approvedBy}::uuid,1) ON CONFLICT(submission_id,nutrient_key) DO NOTHING RETURNING *`;else rows=await tx.$queryRaw<Row[]>`UPDATE nutrient_client_explanation_approvals SET source_intake_version=${input.sourceIntakeVersion},target_version=${input.targetVersion},explanation_hash=${input.explanationHash},explanation_ciphertext=${Buffer.from(input.explanationCiphertext)},approved_by=${input.approvedBy}::uuid,approved_at=now(),version=version+1,updated_at=now() WHERE submission_id=${input.submissionId}::uuid AND nutrient_key=${input.nutrientKey} AND version=${input.expectedVersion} RETURNING *`;if(!rows[0])return null;const saved=map(rows[0]);await tx.$executeRaw`INSERT INTO audit_events(request_id,actor_user_id,actor_role,action,resource_type,resource_id,client_id,decision,reason_code) VALUES(${input.requestId},${input.approvedBy}::uuid,'consultant','nutrient_client_explanation.approve','nutrient_client_explanation',${saved.id}::uuid,${input.clientId}::uuid,'SUCCESS','NUTRIENT_CLIENT_EXPLANATION_APPROVED')`;return saved;});}
}
