import {assessProcessedMeatMateriality} from './processed-meat.materiality';
import {assessSaltCoffeeMateriality} from './salt-coffee.materiality';
import {explainProfessionalPriorities,rankProfessionalPriorities,type PriorityContext} from './professional-priority-ranker';

const attentionStatuses=new Set(['red_flag','below_guide','research_attention','research_attention_total_carbohydrate','above_reference_range']);
const balanceDeviations=new Set(['below_range','above_range','below_reference_range','above_reference_range']);
const priorityRank={data:300,balance:200,quality:100,oxalateCalcium:90,purine:85,phosphateAdditives:75,pral:70,additionalData:60,processedMeat:50,saltCoffee:40};
const formatRu=(value:unknown)=>String(value).replace('.',',');

export function calculateNutritionSummary(protein:any,fat:any,carbohydrate:any=null,additional:any={},priorityContext:PriorityContext={}){
  const proteinSummary=protein?.summary,fatSummary=fat?.summary,carbohydrateSummary=carbohydrate?.summary,carbohydrateSignals=carbohydrateSummary?.signals||{};
  const proteinBalance=proteinSummary?.range_status??(protein?.version?'incomplete_data':'not_started'),fatBalance=fatSummary?.fat_balance?.status??(fat?.source_intake_version?'insufficient_data':'not_started'),fatSignals=Object.entries(fatSummary?.signals||{}).filter(([,status])=>attentionStatuses.has(String(status)));
  const processedMateriality=assessProcessedMeatMateriality(protein?.processed_meat,proteinSummary?.completeness_percent);
  const saltCoffeeMateriality=assessSaltCoffeeMateriality(protein?.salt_coffee);
  const saltCoffee=protein?.salt_coffee,saltRecorded=Boolean(saltCoffee?.items?.some((item:any)=>item.is_salt))||Number(saltCoffee?.totals?.added_salt_g)>0,saltCoffeeFacts:string[]=[];
  const hasAdditionalContext=Object.keys(additional).length>0,pral=additional.pral?.assessment,oxalate=additional.oxalate_calcium?.assessment,calciumPhosphorus=additional.calcium_phosphorus?.assessment,purine=additional.purine_load?.assessment;
  const phosphateStatus=calciumPhosphorus?.phosphateAdditives?.status;
  if(saltRecorded)saltCoffeeFacts.push(`Добавленная соль: ${saltCoffee.totals.added_salt_g===null?`не менее ${saltCoffee.totals.added_salt_lower_estimate_g} г; количество не уточнено`:`${saltCoffee.totals.added_salt_g} г`}; натрий из количественно учтённой соли: ${saltCoffee.totals.sodium_mg===null?`не менее ${saltCoffee.totals.sodium_lower_estimate_mg}`:saltCoffee.totals.sodium_mg} мг; йод: ${saltCoffee.totals.iodine_ug===null?`нижняя оценка ${saltCoffee.totals.iodine_lower_estimate_ug} мкг`:`${saltCoffee.totals.iodine_ug} мкг`}.`);
  if(Number(saltCoffee?.totals?.coffee_ml)>0)saltCoffeeFacts.push(`Кофе без добавок: ${saltCoffee.totals.coffee_ml} мл; кофеин: ${saltCoffee.totals.caffeine_mg===null?`частичная ориентировочная оценка ${saltCoffee.totals.caffeine_partial_estimate_mg} мг`:`ориентировочно ${saltCoffee.totals.caffeine_mg} мг`}. Добавки учитываются отдельными компонентами.`);
  const modules=[
    {key:'protein',title:'Белок',data_status:!protein?.version?'not_started':proteinSummary?.completeness_percent<100?'incomplete':'complete',balance_status:proteinBalance,attention_count:proteinSummary?.plant_share_status==='below_guide'?1:0,client_publication_status:protein?.client_approval?.status??'draft'},
    {key:'fat',title:'Жиры',data_status:!fat?.source_intake_version?'not_started':fatSummary?.completeness&&Object.values(fatSummary.completeness).some((v:any)=>v<100)?'incomplete':'complete',balance_status:fatBalance,attention_count:fatSignals.length,client_publication_status:fat?.client_approval?.status??'draft'},
    {key:'carbohydrate',title:'Углеводы',data_status:!carbohydrate?.source_intake_version?'not_started':carbohydrateSummary?.data_status==='reliable'?'complete':'incomplete',balance_status:carbohydrateSignals.carbohydrate??'insufficient_data',attention_count:[carbohydrateSignals.fibre,carbohydrateSignals.freeSugars,carbohydrateSignals.eveningWeightLossSignal,carbohydrateSignals.refined].filter(v=>['markedly_insufficient','below_minimum','above_recommended','professional_signal','refined_dominant'].includes(String(v))).length,client_publication_status:carbohydrate?.client_approval?.status??carbohydrate?.client_publication_status??'draft'},
    {key:'processed_meat',title:'Переработанное мясо',data_status:processedMateriality.status==='insufficient_data'?'incomplete':protein?.version?'complete':'not_started',balance_status:processedMateriality.status,attention_count:processedMateriality.status==='material'?1:0,client_publication_status:'not_applicable'},
    {key:'salt_coffee',title:'Добавленная соль и кофе',data_status:protein?.version?(protein?.salt_coffee?.status==='available'&&((protein.salt_coffee.completeness?.salt_iodine_percent<100&&saltRecorded)||(protein.salt_coffee.completeness?.coffee_caffeine_percent<100&&protein.salt_coffee.totals?.coffee_ml>0))?'incomplete':'complete'):'not_started',balance_status:saltCoffeeMateriality.status,attention_count:saltCoffeeMateriality.status==='material'?1:0,client_publication_status:'not_applicable',consultant_facts:saltCoffeeFacts},
  ];
  if(hasAdditionalContext)modules.push(
    {key:'pral',title:'Потенциальная почечная кислотная нагрузка (PRAL)',data_status:!pral?'not_started':pral.qualityGate?.status==='passed'?'complete':'incomplete',balance_status:pral?.interpretation??'not_started',attention_count:pral?.qualityGate?.status==='passed'&&pral?.interpretation==='acidifying'?1:0,client_publication_status:'not_applicable',consultant_facts:pral?[`PRAL: ${pral.pralMeqPerDay>0?'+':''}${formatRu(pral.pralMeqPerDay)} мЭкв/сутки; характеристика рациона, не диагноз.`]:[]},
    {key:'oxalate_calcium',title:'Оксалатная нагрузка и кальций',data_status:!oxalate?'not_started':oxalate.qualityGate?.status==='passed'?'complete':'incomplete',balance_status:oxalate?.status??'not_started',attention_count:['combined_factors_review','source_review_portion_frequency'].includes(oxalate?.status)?1:0,client_publication_status:'not_applicable',consultant_facts:oxalate?[oxalate.consultantFact]:[]},
    {key:'calcium_phosphorus',title:'Кальций–фосфор и фосфатные добавки',data_status:!calciumPhosphorus?'not_started':calciumPhosphorus.qualityGate?.status==='passed'?'complete':'incomplete',balance_status:phosphateStatus??'not_started',attention_count:['detected','probable_by_category'].includes(phosphateStatus)?1:0,client_publication_status:'not_applicable',consultant_facts:calciumPhosphorus?[`Ca:P ${calciumPhosphorus.ratioDisplay}; отношение информационное, без цветового порога.`,phosphateStatus==='detected'?`Подтверждённые фосфатные добавки: ${calciumPhosphorus.phosphateAdditives.codes.join(', ')}.`:phosphateStatus==='probable_by_category'?'Есть вероятные категорийные источники фосфатных добавок без этикетки.':'В доступном тексте фосфатные E-коды не найдены; это не подтверждает их отсутствие.']:[]},
    {key:'purine_load',title:'Пуриновая нагрузка',data_status:!purine?'not_started':purine.qualityGate?.status==='passed'?'complete':'incomplete',balance_status:purine?.status??'not_started',attention_count:['high_source_present','review_sources_and_portions'].includes(purine?.status)?1:0,client_publication_status:'not_applicable',consultant_facts:purine?[`Ориентировочно ${purine.knownTotalIsLowerEstimate?'не менее ':''}${formatRu(purine.totalKnownMg)} мг: животные источники ${formatRu(purine.animalKnownMg)} мг, растительные ${formatRu(purine.plantKnownMg)} мг.`]:[]},
  );
  const candidates:any[]=modules.slice(0,3).map((m,index)=>{if(m.data_status==='not_started')return{module_key:m.key,level:'data',code:'not_started',message:`Раздел «${m.title}» ещё не рассчитан.`,rank:priorityRank.data,index};if(m.data_status==='incomplete')return{module_key:m.key,level:'data',code:'incomplete_data',message:`В разделе «${m.title}» есть неполные или пограничные данные.`,rank:priorityRank.data,index};if(balanceDeviations.has(m.balance_status)){const below=m.balance_status.startsWith('below');return{module_key:m.key,level:'balance',code:m.balance_status,message:`Показатель количества в разделе «${m.title}» находится ${below?'ниже':'выше'} рабочего диапазона.`,rank:priorityRank.balance,index};}if(m.attention_count)return{module_key:m.key,level:'quality',code:'quality_attention',message:`В разделе «${m.title}» есть ${m.attention_count===1?'значимый сигнал качества':`значимые сигналы качества: ${m.attention_count}`}.`,rank:priorityRank.quality,index};return null;}).filter(Boolean);
  if(processedMateriality.status==='material')candidates.push({module_key:'processed_meat',level:'quality',code:'processed_meat_material',message:processedMateriality.message,rank:priorityRank.processedMeat,index:3,materiality_rule:processedMateriality.rule});
  if(saltCoffeeMateriality.status==='material')candidates.push({module_key:'salt_coffee',level:'data',code:'salt_iodine_lower_estimate',message:saltCoffeeMateriality.message,rank:priorityRank.saltCoffee,index:4,materiality_rule:saltCoffeeMateriality.rule});
  const additionalCandidates=[
    !pral?null:pral.qualityGate?.status!=='passed'?{module_key:'pral',level:'data',code:'pral_incomplete',message:'PRAL не включён в вывод: недостаточно полных данных по компонентам формулы.',rank:priorityRank.additionalData,index:5}:pral.interpretation==='acidifying'?{module_key:'pral',level:'context',code:'pral_positive',message:`PRAL положительный (${pral.pralMeqPerDay>0?'+':''}${formatRu(pral.pralMeqPerDay)} мЭкв/сутки); оцените структуру и повторяемость рациона.`,rank:priorityRank.pral,index:5}:null,
    !oxalate?null:oxalate.qualityGate?.status!=='passed'?{module_key:'oxalate_calcium',level:'data',code:'oxalate_calcium_incomplete',message:'Оксалатно-кальциевый сигнал заблокирован полнотой данных.',rank:priorityRank.additionalData,index:6}:oxalate.status==='combined_factors_review'?{module_key:'oxalate_calcium',level:'quality',code:'oxalate_calcium_combined',message:oxalate.consultantFact,rank:priorityRank.oxalateCalcium,index:6}:oxalate.status==='source_review_portion_frequency'?{module_key:'oxalate_calcium',level:'quality',code:'oxalate_source_review',message:oxalate.consultantFact,rank:priorityRank.oxalateCalcium,index:6}:null,
    !calciumPhosphorus?null:calciumPhosphorus.qualityGate?.status!=='passed'?{module_key:'calcium_phosphorus',level:'data',code:'calcium_phosphorus_incomplete',message:'Отношение Ca:P не рассчитано: недостаточно совместных данных по кальцию и фосфору.',rank:priorityRank.additionalData,index:7}:phosphateStatus==='detected'?{module_key:'calcium_phosphorus',level:'quality',code:'phosphate_additives_detected',message:`Найдены фосфатные добавки: ${calciumPhosphorus.phosphateAdditives.codes.join(', ')}.`,rank:priorityRank.phosphateAdditives,index:7}:phosphateStatus==='probable_by_category'?{module_key:'calcium_phosphorus',level:'context',code:'phosphate_additives_probable',message:'Есть вероятные категорийные источники фосфатных добавок без этикетки; количественная прибавка к фосфору не создаётся.',rank:priorityRank.phosphateAdditives,index:7}:null,
    !purine?null:purine.qualityGate?.status!=='passed'?{module_key:'purine_load',level:'data',code:'purine_incomplete',message:'Пуриновая нагрузка не включена в вывод: недостаточно распознанных продуктов.',rank:priorityRank.additionalData,index:8}:purine.status==='high_source_present'?{module_key:'purine_load',level:'quality',code:'purine_high_source',message:'Есть продукт из высокопуриновой категории; оцените порцию и повторяемость.',rank:priorityRank.purine,index:8}:purine.status==='review_sources_and_portions'?{module_key:'purine_load',level:'context',code:'purine_sources_review',message:'Есть умеренные источники пуринов; оцените их сочетание, порции и повторяемость.',rank:priorityRank.purine,index:8}:null,
  ].filter(Boolean);
  if(hasAdditionalContext)candidates.push(...additionalCandidates);
  const availablePriorities=rankProfessionalPriorities(candidates,priorityContext,Number.POSITIVE_INFINITY),priorities=availablePriorities.slice(0,3);
  return{modules,priorities,priority_ranking:{limit:3,context:{goal:priorityContext.goal??null,repeated_signals:(priorityContext.repeatedModuleKeys??[]).length,clinical_context:(priorityContext.clinicalContextKeys??[]).length},available_priorities:availablePriorities,explanations:explainProfessionalPriorities(priorities,priorityContext),client_publication_status:'not_applicable'},totals:{modules:modules.length,complete:modules.filter(m=>m.data_status==='complete').length,with_attention:modules.filter(m=>m.attention_count>0||balanceDeviations.has(m.balance_status)).length,approved_for_client:modules.filter(m=>m.client_publication_status==='approved').length,publication_pending:modules.filter(m=>m.client_publication_status==='draft').length}};
}
