import type{FoodMineralValue}from'./food-mineral-intake.calculator';
export type OxalateCalciumCard={foodKey:string;displayName:string;calcium?:FoodMineralValue};
export type OxalateCalciumPortion={foodKey:string;mealKey:string;massG:number};
const oxalatePatterns=[/шпинат/i,/щавел/i,/ревен/i,/свекольн.*ботв/i,/какао/i,/шоколад/i];
const calciumSourcePatterns=[/молок/i,/йогурт/i,/(^|[ ,])сыр($|[ ,])/i,/творог/i,/кефир/i];
const round=(v:number,d=1)=>Number(v.toFixed(d));
export function calculateOxalateCalcium(portions:OxalateCalciumPortion[],cards:OxalateCalciumCard[],calciumTargetMg=1100){
  const byKey=new Map(cards.map(x=>[x.foodKey,x])),oxalateSources:any[]=[],calciumSources:any[]=[],unresolved:any[]=[];let calciumMg=0,resolvedMassG=0,validMassG=0;
  for(const p of portions){if(!Number.isFinite(p.massG)||p.massG<=0||p.massG>5000){unresolved.push({...p,reason:'MASS_INVALID'});continue;}validMassG+=p.massG;const card=byKey.get(p.foodKey);if(!card){unresolved.push({...p,reason:'CARD_NOT_FOUND'});continue;}if(oxalatePatterns.some(x=>x.test(card.displayName)))oxalateSources.push({foodKey:p.foodKey,displayName:card.displayName,mealKey:p.mealKey,massG:round(p.massG,3),quantitativeOxalateCalculated:false});if(calciumSourcePatterns.some(x=>x.test(card.displayName)))calciumSources.push({foodKey:p.foodKey,displayName:card.displayName,mealKey:p.mealKey,massG:round(p.massG,3)});const v=card.calcium;if(!v||v.status==='missing'){unresolved.push({...p,reason:'CALCIUM_MISSING'});continue;}const per100=v.status==='trace'?0:Number(v.valuePer100g)*(v.unit==='ug'?.001:1);if(!Number.isFinite(per100)||per100<0){unresolved.push({...p,reason:'CALCIUM_INVALID'});continue;}calciumMg+=per100*p.massG/100;resolvedMassG+=p.massG;}
  const rowCoveragePercent=portions.length?round((portions.length-unresolved.length)/portions.length*100):0,massCoveragePercent=validMassG?round(resolvedMassG/validMassG*100):0,qualityPassed=portions.length>0&&rowCoveragePercent>=70&&massCoveragePercent>=70&&unresolved.every(x=>x.reason!=='MASS_INVALID');
  const oxalateMeals=[...new Set(oxalateSources.map(x=>x.mealKey))],sameMealCalciumSources=calciumSources.filter(x=>oxalateMeals.includes(x.mealKey)),calciumTotalMg=round(calciumMg),calciumBelowTarget=qualityPassed&&calciumTotalMg<calciumTargetMg;
  const status=!qualityPassed?'insufficient_data':!oxalateSources.length?'oxalate_source_not_detected':calciumBelowTarget&&!sameMealCalciumSources.length?'combined_factors_review':sameMealCalciumSources.length?'source_with_same_meal_calcium':'source_review_portion_frequency';
  const consultantFact=status==='combined_factors_review'?'Выявлен конкретный потенциально высокооксалатный продукт; суточный кальций ниже рабочего ориентира, а подтверждённый пищевой источник кальция в том же приёме не найден. Уточните повторяемость, порцию и клинический контекст.':status==='source_with_same_meal_calcium'?'Выявлен потенциально высокооксалатный продукт и пищевой источник кальция в том же приёме. Уточните порцию и повторяемость.':status==='source_review_portion_frequency'?'Выявлен потенциально высокооксалатный продукт. Уточните порцию, частоту и способ приготовления.':status==='oxalate_source_not_detected'?'В представленном рационе приоритетный источник оксалатов не выявлен.':'Надёжная качественная оценка заблокирована полнотой данных.';
  return{status,consultantFact,calciumTotalMg,calciumTargetMg,calciumBelowTarget,oxalateSources,calciumSources,sameMealCalciumSources,qualityGate:{status:qualityPassed?'passed':'blocked',rowCoveragePercent,massCoveragePercent,reasons:qualityPassed?[]:['Недостаточно данных по кальцию или порциям.']},limitations:['Числовое содержание оксалатов не рассчитывается без отдельной валидированной базы.','Один день не характеризует обычный рацион.'],diagnosisGenerated:false,clientRecommendationGenerated:false};
}
