import{HttpStatus,Injectable}from'@nestjs/common';import{createHash}from'node:crypto';import type{AuthenticatedUser}from'../auth/auth.types';import{AuthorizationPolicy}from'../authorization/authorization.policy';import{AppError,unavailable}from'../common/app-error';import{AssignmentRepository}from'./assignment.repository';import{PayloadCryptoService}from'./payload-crypto.service';import{ProfessionalPriorityReviewRepository,type PriorityReviewRecord}from'./professional-priority-review.repository';import{SubmissionStore}from'./submission.store';
export const prioritySourceHash=(candidates:Array<Record<string,any>>)=>createHash('sha256').update(JSON.stringify(candidates.map(x=>({module_key:x.module_key,code:x.code,related_codes:x.related_codes??[]})))).digest('hex');
@Injectable()export class ProfessionalPriorityReviewService{constructor(private readonly store:SubmissionStore,private readonly assignments:AssignmentRepository,private readonly policy:AuthorizationPolicy,private readonly repo:ProfessionalPriorityReviewRepository,private readonly crypto:PayloadCryptoService){}
 private async requireSubmission(submissionId:string,clientId:string,user:AuthenticatedUser){this.policy.requireRole(user,'consultant');const s=await this.store.findById(submissionId);if(!s||s.clientId!==clientId)throw unavailable('SUBMISSION_NOT_FOUND');this.policy.requireActiveAssignment(user,await this.assignments.activeConsultant(clientId));if(s.status!=='accepted')throw unavailable('SUBMISSION_NOT_ACCEPTED');}
 async read(submissionId:string,sourceHash:string){const record=await this.repo.find(submissionId);if(!record)return{status:'automatic',version:0,selected_keys:[],reason:'',updated_at:null};const reason=await this.decrypt(record);return{status:record.sourceHash===sourceHash?'applied':'stale',version:record.version,selected_keys:record.selectedKeys,reason,updated_at:record.updatedAt.toISOString()};}
 async save(submissionId:string,clientId:string,user:AuthenticatedUser,requestId:string,expectedVersion:number,input:any,candidates:Array<Record<string,any>>){await this.requireSubmission(submissionId,clientId,user);if(!requestId)throw new AppError('REQUEST_ID_REQUIRED',HttpStatus.BAD_REQUEST);const keys:string[]=Array.isArray(input?.selected_keys)?input.selected_keys.map(String):[],reason=typeof input?.reason==='string'?input.reason.replace(/\r\n/g,'\n').trim():'';if(!reason||reason.length>2000||keys.length>3||new Set(keys).size!==keys.length)throw new AppError('PROFESSIONAL_PRIORITY_REVIEW_INVALID',HttpStatus.BAD_REQUEST);const available=new Set(candidates.map(x=>String(x.module_key)));if(keys.some((key:string)=>!available.has(key)))throw new AppError('PROFESSIONAL_PRIORITY_REVIEW_CANDIDATE_INVALID',HttpStatus.BAD_REQUEST);const saved=await this.repo.save({clientId,submissionId,updatedBy:user.id,sourceHash:prioritySourceHash(candidates),selectedKeys:keys,reasonCiphertext:await this.crypto.encrypt(Buffer.from(reason,'utf8')),expectedVersion,requestId});if(!saved)throw new AppError('PROFESSIONAL_PRIORITY_REVIEW_VERSION_CONFLICT',HttpStatus.CONFLICT);return this.dto(saved,reason);}
 private dto(x:PriorityReviewRecord,reason:string){return{status:'applied',version:x.version,selected_keys:x.selectedKeys,reason,updated_at:x.updatedAt.toISOString()};}
 private async decrypt(x:PriorityReviewRecord){try{return Buffer.from(await this.crypto.decrypt(x.reasonCiphertext)).toString('utf8');}catch{throw new AppError('PROFESSIONAL_PRIORITY_REVIEW_INTEGRITY_FAILED',HttpStatus.CONFLICT);}}
}
