import{describe,expect,it}from'vitest';import{explainProfessionalPriorities,rankProfessionalPriorities}from'./professional-priority-ranker';
const c=(module_key:string,rank:number,index:number)=>({module_key,level:'quality',code:`${module_key}_signal`,message:module_key,rank,index});
describe('professional priority ranker',()=>{
  it('always returns no more than three priorities',()=>expect(rankProfessionalPriorities([c('a',50,0),c('b',40,1),c('c',30,2),c('d',20,3)])).toHaveLength(3));
  it('combines calcium and oxalate findings into one place',()=>{const x=rankProfessionalPriorities([c('oxalate_calcium',90,0),c('calcium_phosphorus',75,1),c('purine_load',85,2)]);expect(x).toHaveLength(2);expect(x[0]).toMatchObject({module_key:'oxalate_calcium',related_module_keys:['calcium_phosphorus']});});
  it('uses confirmed goal, repetition and clinical context without inventing missing context',()=>{const input=[c('fat',100,0),c('purine_load',85,1)];expect(rankProfessionalPriorities(input).map(x=>x.module_key)).toEqual(['fat','purine_load']);expect(rankProfessionalPriorities(input,{goal:'gout',repeatedModuleKeys:['purine_load'],clinicalContextKeys:['gout']}).map(x=>x.module_key)).toEqual(['purine_load','fat']);});
  it('combines a processed-meat signal with an existing fat signal',()=>{const x=rankProfessionalPriorities([c('fat',100,0),c('processed_meat',90,1),c('carbohydrate',80,2)]);expect(x.map(y=>y.module_key)).toEqual(['fat','carbohydrate']);expect(x[0]).toMatchObject({related_module_keys:['processed_meat']});});
  it('explains applied and unavailable factors without inventing evidence',()=>{const priorities=rankProfessionalPriorities([c('purine_load',85,0)],{goal:'gout',repeatedModuleKeys:['purine_load'],clinicalContextKeys:['gout']});expect(explainProfessionalPriorities(priorities,{goal:'gout',repeatedModuleKeys:['purine_load'],clinicalContextKeys:['gout']})[0]).toMatchObject({position:1,module_key:'purine_load',factors:[{key:'signal_strength',status:'applied'},{key:'data_quality',status:'passed'},{key:'client_goal',status:'applied'},{key:'repetition',status:'applied'},{key:'clinical_context',status:'applied'}]});const absent=explainProfessionalPriorities(rankProfessionalPriorities([c('fat',100,0)]))[0];expect(absent.factors.find(x=>x.key==='clinical_context')?.status).toBe('not_available');});
});
