import{describe,expect,it}from'vitest';import{buildProfessionalConclusion}from'./professional-conclusion.calculator';
const base={priorities:[{module_key:'purine_load',code:'purine_sources_review',message:'Проверить источники.'}],modules:[{key:'purine_load',title:'Пурины',data_status:'complete',consultant_facts:['434,5 мг.']}],totals:{modules:9,complete:9},priority_ranking:{context:{goal:'gout'},explanations:[{position:1,factors:[{key:'clinical_context',status:'applied'}]}]},priority_review:{status:'applied',version:1,reason:'Подтверждённый контекст'}};
describe('professional conclusion structure',()=>{
 it('builds six professional-only sections from the approved priority order',()=>{const x=buildProfessionalConclusion(base);expect(x).toMatchObject({version:2,audience:'consultant',client_publication_status:'not_applicable',status:'draft'});expect(x.sections.map((s:any)=>s.key)).toEqual(['assessment_basis','priority_findings','supporting_findings','data_limitations','consultant_decision','readiness']);expect(x.sections[1].items[0]).toMatchObject({position:1,module_key:'purine_load',fact:'Проверить источники.'});});
 it('creates a cohesive consultant-only draft without changing publication state',()=>{const x=buildProfessionalConclusion(base);expect(x.generated_draft).toMatchObject({audience:'consultant',publication_status:'not_applicable'});expect(x.generated_draft.paragraphs).toHaveLength(6);expect(x.generated_draft.paragraphs.join(' ')).toContain('Проверить источники.');expect(x.generated_draft.paragraphs.at(-1)).toContain('не предназначен для публикации клиенту');});
 it('includes limitations and stale review in the generated narrative',()=>{const x=buildProfessionalConclusion({...base,modules:[...base.modules,{key:'fat',title:'Жиры',data_status:'incomplete'}],priority_review:{status:'stale',version:1,reason:'Старое решение'}});const text=x.generated_draft.paragraphs.join(' ');expect(text).toContain('Жиры');expect(text).toContain('устарело');expect(text).toContain('устранить указанные блокеры');});
 it('preserves the consultant order in both findings and narrative',()=>{const x=buildProfessionalConclusion({...base,priorities:[{module_key:'fat',code:'above_range',message:'Сначала проверить жиры.'},{module_key:'purine_load',code:'purine_sources_review',message:'Затем проверить пурины.'}],priority_review:{status:'applied',version:2,reason:'Цель клиента'}});expect(x.sections[1].items.map((item:any)=>item.module_key)).toEqual(['fat','purine_load']);expect(x.generated_draft.paragraphs[1]).toMatch(/Сначала проверить жиры\. Затем проверить пурины\./);expect(x.generated_draft.paragraphs[4]).toContain('Цель клиента');});
 it('keeps a merged calcium-oxalate signal in one priority slot',()=>{const x=buildProfessionalConclusion({...base,priorities:[{module_key:'oxalate_calcium',related_module_keys:['calcium_phosphorus'],code:'oxalate_calcium_combined',message:'Низкий кальций сочетается с оксалатным источником.'}]});expect(x.sections[1].items).toHaveLength(1);expect(x.sections[1].items[0].related_module_keys).toEqual(['calcium_phosphorus']);expect(x.generated_draft.paragraphs[1]).toContain('Низкий кальций сочетается с оксалатным источником.');});
 it('renders known goals in Russian in the professional narrative',()=>{const text=buildProfessionalConclusion(base).generated_draft.paragraphs[0];expect(text).toContain('контроль факторов, связанных с подагрой');expect(text).not.toContain('gout');});
 it('marks a stale manual decision as requiring review',()=>{const x=buildProfessionalConclusion({...base,priority_review:{status:'stale',version:1,reason:'Старое решение'}});expect(x.sections.at(-1)!.content!.status).toBe('priority_review_required');});
 it('keeps incomplete modules as limitations instead of unsupported findings',()=>{const x=buildProfessionalConclusion({...base,modules:[...base.modules,{key:'fat',title:'Жиры',data_status:'incomplete'}]});expect(x.sections.find((s:any)=>s.key==='data_limitations')!.items).toEqual([{module_key:'fat',title:'Жиры',status:'incomplete',impact:'Интерпретация раздела ограничена полнотой данных.'}]);});
});
