import {HttpStatus,Injectable} from '@nestjs/common';import type {AuthenticatedUser} from '../auth/auth.types';import {AuthorizationPolicy} from '../authorization/authorization.policy';import {AppError,unavailable} from '../common/app-error';import {AssignmentRepository} from './assignment.repository';import {FoodProductRepository} from './food-product.repository';import {calculateProteinIntake,type IntakeInput} from './protein-intake.calculator';import {ProteinIntakeRepository,type ProteinIntakeRecord} from './protein-intake.repository';import {PayloadCryptoService} from './payload-crypto.service';import {ProteinTargetRepository} from './protein-target.repository';import {SubmissionStore} from './submission.store';
const MEALS=new Set(['breakfast','snack_1','lunch','snack_2','dinner','bedtime','other']);const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
@Injectable() export class ProteinIntakeService {constructor(private readonly store:SubmissionStore,private readonly assignments:AssignmentRepository,private readonly policy:AuthorizationPolicy,private readonly products:FoodProductRepository,private readonly assessments:ProteinIntakeRepository,private readonly targets:ProteinTargetRepository,private readonly crypto:PayloadCryptoService){}
  private async requireSubmission(submissionId:string,clientId:string,user:AuthenticatedUser){this.policy.requireRole(user,'consultant');const s=await this.store.findById(submissionId);if(!s||s.clientId!==clientId)throw unavailable('SUBMISSION_NOT_FOUND');this.policy.requireActiveAssignment(user,await this.assignments.activeConsultant(clientId));if(s.status!=='accepted')throw unavailable('SUBMISSION_NOT_ACCEPTED');}
  async listProducts(clientId:string,user:AuthenticatedUser){this.policy.requireRole(user,'consultant');this.policy.requireActiveAssignment(user,await this.assignments.activeConsultant(clientId));return {items:await this.products.listVerified()};}
  async get(submissionId:string,clientId:string,user:AuthenticatedUser){await this.requireSubmission(submissionId,clientId,user);const a=await this.assessments.findBySubmission(submissionId);if(!a)return {submission_id:submissionId,items:[],summary:null,version:0,updated_at:null};return this.dto(a,await this.decrypt(a),await this.targets.findBySubmission(submissionId));}
  async save(submissionId:string,clientId:string,user:AuthenticatedUser,requestId:string,expectedVersion:number,body:{items?:unknown}){await this.requireSubmission(submissionId,clientId,user);if(!Array.isArray(body.items)||body.items.length>100)throw this.invalid();const inputs:IntakeInput[]=body.items.map(value=>{if(!value||typeof value!=='object')throw this.invalid();const v=value as Record<string,unknown>,mealKey=String(v.meal_key??''),productCardId=String(v.product_card_id??''),massG=Number(v.mass_g);if(!MEALS.has(mealKey)||!UUID.test(productCardId)||!Number.isFinite(massG)||massG<=0||massG>5000)throw this.invalid();return {mealKey,productCardId,massG};});
    const productMap=await this.products.verifiedByIds([...new Set(inputs.map(i=>i.productCardId))]),calculation=calculateProteinIntake(inputs,productMap);const payload={items:inputs,calculation};const saved=await this.assessments.save({clientId,submissionId,updatedBy:user.id,payloadCiphertext:await this.crypto.encrypt(Buffer.from(JSON.stringify(payload))),totalProteinG:calculation.totalProteinG,plantProteinG:calculation.plantProteinG,animalProteinG:calculation.animalProteinG,completenessPercent:calculation.completenessPercent,expectedVersion,requestId});if(!saved)throw new AppError('PROTEIN_INTAKE_VERSION_CONFLICT',HttpStatus.CONFLICT);return this.dto(saved,payload,await this.targets.findBySubmission(submissionId));}
  private dto(a:ProteinIntakeRecord,payload:any,target:any){const c=payload.calculation,total=a.totalProteinG,plantShare=total?a.plantProteinG/total*100:null;let rangeStatus='target_not_set';if(a.completenessPercent<100)rangeStatus='incomplete_data';else if(target)rangeStatus=total<target.targetMinG?'below_range':total>target.targetMaxG?'above_range':'within_range';return {submission_id:a.submissionId,items:payload.items,lines:c.lines,unresolved:c.unresolved,summary:{total_protein_g:this.round(total),plant_protein_g:this.round(a.plantProteinG),animal_protein_g:this.round(a.animalProteinG),plant_share_percent:plantShare===null?null:this.round(plantShare),plant_share_status:plantShare===null?'unavailable':plantShare>=50?'meets_guide':'below_guide',completeness_percent:a.completenessPercent,meal_totals:c.mealTotals.map((m:any)=>({meal_key:m.mealKey,protein_g:this.round(m.proteinG)})),target_min_g:target?.targetMinG??null,target_max_g:target?.targetMaxG??null,range_status:rangeStatus},version:a.version,updated_at:a.updatedAt.toISOString()};}
  private async decrypt(a:ProteinIntakeRecord){try{return JSON.parse(Buffer.from(await this.crypto.decrypt(a.payloadCiphertext)).toString('utf8'));}catch{throw new AppError('PROTEIN_INTAKE_INTEGRITY_FAILED',HttpStatus.CONFLICT);}}
  private round(value:number){return Number(value.toFixed(2));}private invalid(){return new AppError('PROTEIN_INTAKE_INVALID',HttpStatus.BAD_REQUEST);}
}
