import { createHash } from 'node:crypto';
import { describe,expect,it } from 'vitest';
import type { AuthenticatedUser } from '../auth/auth.types';import { AuthorizationPolicy } from '../authorization/authorization.policy';import { ProteinTargetService } from './protein-target.service';
const user:AuthenticatedUser={id:'00000000-0000-0000-0000-000000000001',authSubject:'synthetic',role:'consultant',status:'active',sessionIssuedAt:new Date(),sessionRevokedAt:null};
const clientId='00000000-0000-0000-0000-000000000099',submissionId='00000000-0000-0000-0000-000000000020';
const values=Array(76).fill('');values[3]='170';values[4]='106,93';values[50]='Женский';const plaintext=Buffer.from(JSON.stringify(values));
const submission={id:submissionId,clientId,status:'accepted' as const,schemaId:'forms_v2_76_columns' as const,sourceResponseId:undefined,idempotencyKey:'k',headerFingerprint:'h',payloadHash:createHash('sha256').update(plaintext).digest('hex'),payloadCiphertext:plaintext,consentStatus:'verified' as const};
function setup(options:{save?:boolean;assigned?:string|null}={}){const inputs:unknown[]=[];const service=new ProteinTargetService({findById:async()=>submission} as never,{activeConsultant:async()=>options.assigned===undefined?user.id:options.assigned} as never,new AuthorizationPolicy(),{findBySubmission:async()=>null,save:async(input:any)=>{inputs.push(input);return options.save===false?null:{id:'00000000-0000-0000-0000-000000000030',...input,version:1,updatedAt:new Date('2026-08-16T10:00:00Z')};}} as never,{encrypt:async(v:Uint8Array)=>v,decrypt:async(v:Uint8Array)=>v} as never);return {service,inputs};}
describe('protein target service',()=>{
  it('calculates and saves a built-in target from the accepted payload',async()=>{const {service,inputs}=setup();const out=await service.save(submissionId,clientId,user,'req',0,{source:'built_in',reason:''});expect(out).toMatchObject({bmi_rounded:37,protein_factor_g:115,target_min_g:100,target_max_g:125});expect(JSON.stringify(inputs)).not.toContain('Скрытое');});
  it('saves a manually calculated range',async()=>expect(await setup().service.save(submissionId,clientId,user,'req',0,{source:'manual',protein_factor_g:180,target_min_g:180,target_max_g:205,reason:'Индивидуальный расчёт'})).toMatchObject({protein_factor_g:180,target_max_g:205}));
  it('requires manual calculation for an automatic factor above 175',async()=>{const high=[...values];high[3]='188';high[4]='159,05';high[50]='Мужской';const highPlain=Buffer.from(JSON.stringify(high));const highSubmission={...submission,payloadHash:createHash('sha256').update(highPlain).digest('hex'),payloadCiphertext:highPlain};const service=new ProteinTargetService({findById:async()=>highSubmission} as never,{activeConsultant:async()=>user.id} as never,new AuthorizationPolicy(),{} as never,{decrypt:async(v:Uint8Array)=>v} as never);await expect(service.save(submissionId,clientId,user,'req',0,{source:'built_in',reason:''})).rejects.toThrow('PROTEIN_TARGET_MANUAL_REQUIRED');});
  it('reports a concurrent update and enforces assignment',async()=>{await expect(setup({save:false}).service.save(submissionId,clientId,user,'req',1,{source:'manual',protein_factor_g:100,target_min_g:100,target_max_g:125,reason:''})).rejects.toThrow('PROTEIN_TARGET_VERSION_CONFLICT');await expect(setup({assigned:null}).service.get(submissionId,clientId,user)).rejects.toThrow('RESOURCE_UNAVAILABLE');});
});
