import {Injectable} from '@nestjs/common';import {PrismaService} from '../database/prisma.service';
export type ProteinIntakeRecord={id:string;clientId:string;submissionId:string;updatedBy:string;payloadCiphertext:Uint8Array;totalProteinG:number;plantProteinG:number;animalProteinG:number;completenessPercent:number;version:number;updatedAt:Date};
type Row={id:string;client_id:string;submission_id:string;updated_by:string;payload_ciphertext:Uint8Array;total_protein_g:unknown;plant_protein_g:unknown;animal_protein_g:unknown;completeness_percent:number;version:number;updated_at:Date};
const map=(r:Row):ProteinIntakeRecord=>({id:r.id,clientId:r.client_id,submissionId:r.submission_id,updatedBy:r.updated_by,payloadCiphertext:r.payload_ciphertext,totalProteinG:Number(r.total_protein_g),plantProteinG:Number(r.plant_protein_g),animalProteinG:Number(r.animal_protein_g),completenessPercent:r.completeness_percent,version:r.version,updatedAt:r.updated_at});
@Injectable() export class ProteinIntakeRepository {constructor(private readonly prisma:PrismaService){}
  async findBySubmission(submissionId:string){const rows=await this.prisma.$queryRaw<Row[]>`SELECT id,client_id,submission_id,updated_by,payload_ciphertext,total_protein_g,plant_protein_g,animal_protein_g,completeness_percent,version,updated_at FROM protein_intake_assessments WHERE submission_id=${submissionId}::uuid LIMIT 1`;return rows[0]?map(rows[0]):null;}
  async save(input:{clientId:string;submissionId:string;updatedBy:string;payloadCiphertext:Uint8Array;totalProteinG:number;plantProteinG:number;animalProteinG:number;completenessPercent:number;expectedVersion:number;requestId:string}){return this.prisma.$transaction(async tx=>{let rows:Row[];
    if(input.expectedVersion===0)rows=await tx.$queryRaw<Row[]>`INSERT INTO protein_intake_assessments(client_id,submission_id,updated_by,payload_ciphertext,total_protein_g,plant_protein_g,animal_protein_g,completeness_percent,version) VALUES(${input.clientId}::uuid,${input.submissionId}::uuid,${input.updatedBy}::uuid,${Buffer.from(input.payloadCiphertext)},${input.totalProteinG},${input.plantProteinG},${input.animalProteinG},${input.completenessPercent},1) ON CONFLICT(submission_id) DO NOTHING RETURNING id,client_id,submission_id,updated_by,payload_ciphertext,total_protein_g,plant_protein_g,animal_protein_g,completeness_percent,version,updated_at`;
    else rows=await tx.$queryRaw<Row[]>`UPDATE protein_intake_assessments SET updated_by=${input.updatedBy}::uuid,payload_ciphertext=${Buffer.from(input.payloadCiphertext)},total_protein_g=${input.totalProteinG},plant_protein_g=${input.plantProteinG},animal_protein_g=${input.animalProteinG},completeness_percent=${input.completenessPercent},version=version+1,updated_at=now() WHERE submission_id=${input.submissionId}::uuid AND version=${input.expectedVersion} RETURNING id,client_id,submission_id,updated_by,payload_ciphertext,total_protein_g,plant_protein_g,animal_protein_g,completeness_percent,version,updated_at`;
    if(!rows[0])return null;const a=map(rows[0]);await tx.$executeRaw`INSERT INTO protein_intake_assessment_versions(assessment_id,client_id,submission_id,updated_by,payload_ciphertext,total_protein_g,plant_protein_g,animal_protein_g,completeness_percent,version) VALUES(${a.id}::uuid,${a.clientId}::uuid,${a.submissionId}::uuid,${a.updatedBy}::uuid,${Buffer.from(a.payloadCiphertext)},${a.totalProteinG},${a.plantProteinG},${a.animalProteinG},${a.completenessPercent},${a.version})`;
    await tx.$executeRaw`INSERT INTO audit_events(request_id,actor_user_id,actor_role,action,resource_type,resource_id,client_id,decision,reason_code) VALUES(${input.requestId},${input.updatedBy}::uuid,'consultant','protein_intake.save','protein_intake_assessment',${a.id}::uuid,${a.clientId}::uuid,'SUCCESS','PROTEIN_INTAKE_SAVED')`;return a;},{maxWait:5_000});}
}
