import {describe,expect,it} from 'vitest';import type {AuthenticatedUser} from '../auth/auth.types';import {AuthorizationPolicy} from '../authorization/authorization.policy';import {ProteinIntakeService} from './protein-intake.service';
const user:AuthenticatedUser={id:'00000000-0000-4000-8000-000000000001',authSubject:'synthetic',role:'consultant',status:'active',sessionIssuedAt:new Date(),sessionRevokedAt:null};
const clientId='00000000-0000-4000-8000-000000000099',submissionId='00000000-0000-4000-8000-000000000020',plantId='00000000-0000-4000-8000-000000000031',animalId='00000000-0000-4000-8000-000000000032';
const submission={id:submissionId,clientId,status:'accepted',schemaId:'forms_v3_77_columns'};
const cards=[{id:plantId,name:'Синтетический растительный продукт',proteinPer100g:10,origin:'plant',plantSharePercent:100,sourceLabel:'SYNTHETIC_TEST_ONLY',sourceReference:null,version:1},{id:animalId,name:'Синтетический животный продукт',proteinPer100g:20,origin:'animal',plantSharePercent:0,sourceLabel:'SYNTHETIC_TEST_ONLY',sourceReference:null,version:1}];
function setup(options:{save?:boolean;assigned?:string|null;missingAnimal?:boolean}={}){let savedInput:any;const service=new ProteinIntakeService({findById:async()=>submission} as never,{activeConsultant:async()=>options.assigned===undefined?user.id:options.assigned} as never,new AuthorizationPolicy(),{listVerified:async()=>cards,verifiedByIds:async()=>new Map(cards.filter(c=>!options.missingAnimal||c.id!==animalId).map(c=>[c.id,c]))} as never,{findBySubmission:async()=>null,save:async(input:any)=>{savedInput=input;if(options.save===false)return null;return {id:'00000000-0000-4000-8000-000000000040',...input,version:1,updatedAt:new Date('2026-08-16T18:00:00Z')};}} as never,{findBySubmission:async()=>({targetMinG:30,targetMaxG:50,version:1})} as never,{encrypt:async(v:Uint8Array)=>v,decrypt:async(v:Uint8Array)=>v} as never,{find:async()=>null,approve:async()=>null} as never);return {service,getSaved:()=>savedInput};}
describe('protein intake service',()=>{
  it('preserves an explicit generic fish identity without changing the protein card',async()=>{const {service,getSaved}=setup();const out=await service.save(submissionId,clientId,user,'req-fish',0,{items:[{meal_key:'lunch',product_card_id:animalId,mass_g:150,food_identity:'generic_fish'}]});expect(out.items[0]).toMatchObject({product_card_id:animalId,food_identity:'generic_fish'});expect(Buffer.from(getSaved().payloadCiphertext).toString()).toContain('generic_fish');expect(out.summary.total_protein_g).toBe(30);});
  it('calculates from verified product cards and compares with target',async()=>{const {service,getSaved}=setup();const out=await service.save(submissionId,clientId,user,'req',0,{items:[{meal_key:'breakfast',product_card_id:plantId,mass_g:100},{meal_key:'lunch',product_card_id:animalId,mass_g:150}]});expect(out.summary).toMatchObject({total_protein_g:40,plant_protein_g:10,animal_protein_g:30,plant_share_percent:25,plant_share_status:'below_guide',range_status:'within_range',completeness_percent:100});expect(Buffer.from(getSaved().payloadCiphertext).toString()).toContain('SYNTHETIC_TEST_ONLY');});
  it('marks missing product cards as incomplete instead of inventing nutrients',async()=>{const out=await setup({missingAnimal:true}).service.save(submissionId,clientId,user,'req',0,{items:[{meal_key:'lunch',product_card_id:animalId,mass_g:150}]});expect(out.summary).toMatchObject({total_protein_g:0,completeness_percent:0,range_status:'incomplete_data'});expect(out.unresolved).toEqual([{index:0,reason:'PRODUCT_NOT_VERIFIED'}]);});
  it('rejects stale versions and inactive assignments',async()=>{await expect(setup({save:false}).service.save(submissionId,clientId,user,'req',1,{items:[]})).rejects.toThrow('PROTEIN_INTAKE_VERSION_CONFLICT');await expect(setup({assigned:null}).service.get(submissionId,clientId,user)).rejects.toThrow('RESOURCE_UNAVAILABLE');});
  it('rejects client-supplied nutrient totals',async()=>{await expect(setup().service.save(submissionId,clientId,user,'req',0,{items:[{meal_key:'breakfast',product_card_id:plantId,mass_g:100,protein_g:999}]})).resolves.toMatchObject({summary:{total_protein_g:10}});});
  it('persists and returns salt and coffee as separately measured components',async()=>{const out=await setup().service.save(submissionId,clientId,user,'req',0,{items:[],salt_coffee_items:[{meal_key:'breakfast',catalog_key:'SC-COFFEE-FILTER',volume_ml:200},{meal_key:'lunch',catalog_key:'SC-SALT-UNSPECIFIED',mass_g:2}]});expect(out.salt_coffee.totals).toMatchObject({coffee_ml:200,caffeine_mg:90,added_salt_g:2,sodium_mg:786,iodine_ug:null});expect(out.salt_coffee.client_recommendations_generated).toBe(false);});
  it('rejects iodized salt without confirmed versioned label data',async()=>{await expect(setup().service.save(submissionId,clientId,user,'req',0,{items:[],salt_coffee_items:[{meal_key:'lunch',catalog_key:'SC-SALT-IODIZED-LABEL',mass_g:2,iodine_ug_per_g:20}]})).rejects.toThrow('PROTEIN_INTAKE_INVALID');});
  it('preserves an unknown salt amount as a qualitative lower-bound marker',async()=>{const out=await setup().service.save(submissionId,clientId,user,'req',0,{items:[],salt_coffee_items:[{meal_key:'lunch',catalog_key:'SC-SALT-UNSPECIFIED',amount_unknown:true}]});expect(out.salt_coffee.totals).toMatchObject({added_salt_g:null,sodium_mg:null,sodium_lower_estimate_mg:0,iodine_ug:null});expect(out.salt_coffee.items[0].amount_unknown).toBe(true);});
});
