import {describe,expect,it} from 'vitest';import {RegionalNutrientService} from './regional-nutrient.service';import {AuthorizationPolicy} from '../authorization/authorization.policy';
const user={id:'consultant',role:'consultant',status:'active'} as never,submission={id:'submission',clientId:'client',status:'accepted'};
function service(saltCoffeeItems:any[]){const payload=Buffer.from(JSON.stringify({items:[],saltCoffeeItems}));return new RegionalNutrientService({findById:async()=>submission} as never,{activeConsultant:async()=> 'consultant'} as never,new AuthorizationPolicy(),{findBySubmission:async()=>({version:3,payloadCiphertext:payload})} as never,{verifiedByIds:async()=>new Map()} as never,{decrypt:async()=>payload} as never,{get:async()=>({client:null,submission:null})} as never);}
const query={nutrient:'iodine' as const,marketCountry:'UA',targetUg:150,upperLevelUg:600,period:'single_day' as const};
describe('regional iodine and added salt integration',()=>{
  it('includes confirmed versioned label iodine in the total',async()=>{const out=await service([{catalogKey:'SC-SALT-IODIZED-LABEL',massG:2,iodineUgPerG:20,labelSource:'Фото упаковки',labelVersion:'2026-09-11'}]).get('submission','client',user,query);expect(out.assessment?.totalUg).toEqual({low:40,central:40,high:40});expect(out.assessment?.lines[0].source).toMatchObject({valueType:'label',sourceVersion:'2026-09-11',confidence:'high'});expect(out.assessment?.knownTotalIsLowerEstimate).toBe(false);});
  it('keeps unknown iodization unresolved and marks the known total as lower estimate',async()=>{const out=await service([{catalogKey:'SC-SALT-UNSPECIFIED',massG:2}]).get('submission','client',user,query);expect(out.assessment).toMatchObject({status:'insufficient_data',decisionBlockedByUncertainty:true,knownTotalIsLowerEstimate:true,completenessPercent:0,totalUg:{low:0,central:0,high:0}});expect(out.assessment?.unresolved[0]).toMatchObject({displayName:'Добавленная соль — йодирование неизвестно',reason:'SOURCE_NOT_FOUND'});});
  it('does not inject coffee or its additions into regional iodine',async()=>{const out=await service([{catalogKey:'SC-COFFEE-FILTER',volumeMl:200},{catalogKey:'SC-COFFEE-UNKNOWN',volumeMl:250}]).get('submission','client',user,query);expect(out.assessment).toMatchObject({status:'insufficient_data',completenessPercent:0});expect(out.assessment?.lines).toHaveLength(0);expect(out.assessment?.unresolved).toHaveLength(0);});
  it('defensively rejects a legacy salt row without confirmed mass',async()=>{const out=await service([{catalogKey:'SC-SALT-UNSPECIFIED'}]).get('submission','client',user,query);expect(out.assessment).toMatchObject({status:'insufficient_data',knownTotalIsLowerEstimate:true});expect(out.assessment?.unresolved[0].reason).toBe('MASS_INVALID');});
});
