import {calculateSaltCoffee} from './salt-coffee.calculator';
import {describe,expect,it} from 'vitest';
describe('salt and coffee calculator',()=>{
  it('distinguishes salt from sodium and keeps unknown iodization out of iodine total',()=>{const x=calculateSaltCoffee([{mealKey:'lunch',catalogKey:'SC-SALT-UNSPECIFIED',massG:2}]);expect(x.totals).toMatchObject({added_salt_g:2,sodium_mg:786,iodine_ug:null,iodine_lower_estimate_ug:0});expect(x.limitations.join(' ')).toContain('нижняя оценка');});
  it('requires versioned label evidence for iodized salt',()=>expect(()=>calculateSaltCoffee([{mealKey:'lunch',catalogKey:'SC-SALT-IODIZED-LABEL',massG:2,iodineUgPerG:20}])).toThrow('IODIZED_SALT_LABEL_REQUIRED'));
  it('uses confirmed label concentration for iodized salt',()=>expect(calculateSaltCoffee([{mealKey:'lunch',catalogKey:'SC-SALT-IODIZED-LABEL',massG:2,iodineUgPerG:20,labelSource:'Фото пачки',labelVersion:'2026-09-11'}]).totals).toMatchObject({sodium_mg:786,iodine_ug:40}));
  it('keeps approximate and unknown caffeine distinct',()=>{const x=calculateSaltCoffee([{mealKey:'breakfast',catalogKey:'SC-COFFEE-FILTER',volumeMl:200},{mealKey:'lunch',catalogKey:'SC-COFFEE-INSTANT',volumeMl:250}]);expect(x.totals).toMatchObject({coffee_ml:450,caffeine_mg:null,caffeine_partial_estimate_mg:90});expect(x.completeness.coffee_caffeine_percent).toBe(50);});
  it('requires coffee volume and rejects implausible salt mass',()=>{expect(()=>calculateSaltCoffee([{mealKey:'breakfast',catalogKey:'SC-COFFEE-ESPRESSO'}])).toThrow('SALT_COFFEE_AMOUNT_INVALID');expect(()=>calculateSaltCoffee([{mealKey:'lunch',catalogKey:'SC-SALT-UNSPECIFIED',massG:101}])).toThrow('SALT_COFFEE_AMOUNT_INVALID');});
  it('records mentioned salt with unknown mass without inventing salt or sodium',()=>{const x=calculateSaltCoffee([{mealKey:'lunch',catalogKey:'SC-SALT-UNSPECIFIED',amountUnknown:true}]);expect(x.totals).toMatchObject({added_salt_g:null,added_salt_lower_estimate_g:0,sodium_mg:null,sodium_lower_estimate_mg:0,iodine_ug:null});expect(x.completeness).toMatchObject({salt_amount_percent:0,salt_sodium_percent:0,salt_iodine_percent:0});expect(x.limitations.join(' ')).toContain('Количество добавленной соли неизвестно');});
  it('keeps all four approved coffee forms and their evidence quality distinct',()=>{const x=calculateSaltCoffee([{mealKey:'breakfast',catalogKey:'SC-COFFEE-FILTER',volumeMl:200},{mealKey:'breakfast',catalogKey:'SC-COFFEE-ESPRESSO',volumeMl:60},{mealKey:'lunch',catalogKey:'SC-COFFEE-INSTANT',volumeMl:200},{mealKey:'lunch',catalogKey:'SC-COFFEE-UNKNOWN',volumeMl:200}]);expect(x.items.map(i=>[i.kind,i.quality,i.caffeine_mg])).toEqual([['coffee_filter','approximate_guideline',90],['coffee_espresso','approximate_guideline',80],['coffee_instant','composition_unknown',null],['coffee_unknown','composition_unknown',null]]);expect(x.totals).toMatchObject({coffee_ml:660,caffeine_mg:null,caffeine_partial_estimate_mg:170});});
});
