export type SaltCoffeeKind='salt_unspecified'|'salt_iodized_label'|'coffee_filter'|'coffee_espresso'|'coffee_instant'|'coffee_unknown';
export type SaltCoffeeProfile={kind:SaltCoffeeKind;catalogKey:string;name:string;measure:'mass_g'|'volume_ml';sodiumMgPerG:number|null;caffeineMgPerMl:number|null;quality:'direct_analysis'|'approximate_guideline'|'label_required'|'composition_unknown';source:string;limitations:string[]};
export const SALT_COFFEE_PROFILES:SaltCoffeeProfile[]=[
  {kind:'salt_unspecified',catalogKey:'SC-SALT-UNSPECIFIED',name:'Соль добавленная — йодирование неизвестно',measure:'mass_g',sodiumMgPerG:393,caffeineMgPerMl:null,quality:'direct_analysis',source:'CoFID 2021 17-367',limitations:['Йодирование не подтверждено: йод не считается нулём и не включается в числовой итог.']},
  {kind:'salt_iodized_label',catalogKey:'SC-SALT-IODIZED-LABEL',name:'Соль йодированная — по этикетке',measure:'mass_g',sodiumMgPerG:393,caffeineMgPerMl:null,quality:'label_required',source:'CoFID 2021 17-367 + подтверждённая этикетка',limitations:['Йод рассчитывается только по указанной концентрации, источнику и версии этикетки.']},
  {kind:'coffee_filter',catalogKey:'SC-COFFEE-FILTER',name:'Кофе фильтрованный, без добавок',measure:'volume_ml',sodiumMgPerG:null,caffeineMgPerMl:.45,quality:'approximate_guideline',source:'EFSA caffeine guidance: 90 mg / 200 ml',limitations:['Кофеин — ориентировочная оценка: содержание зависит от зерна и приготовления.']},
  {kind:'coffee_espresso',catalogKey:'SC-COFFEE-ESPRESSO',name:'Эспрессо, без добавок',measure:'volume_ml',sodiumMgPerG:null,caffeineMgPerMl:80/60,quality:'approximate_guideline',source:'EFSA caffeine guidance: 80 mg / 60 ml',limitations:['Кофеин — ориентировочная оценка: содержание зависит от зерна и приготовления.']},
  {kind:'coffee_instant',catalogKey:'SC-COFFEE-INSTANT',name:'Кофе растворимый, приготовленный с водой',measure:'volume_ml',sodiumMgPerG:null,caffeineMgPerMl:null,quality:'composition_unknown',source:'CoFID 2021 17-159',limitations:['CoFID подтверждает форму напитка, но не содержит кофеин: числовая оценка кофеина не строится.']},
  {kind:'coffee_unknown',catalogKey:'SC-COFFEE-UNKNOWN',name:'Кофе — способ приготовления неизвестен',measure:'volume_ml',sodiumMgPerG:null,caffeineMgPerMl:null,quality:'composition_unknown',source:'Форма, утверждённая для неполной записи',limitations:['Без способа приготовления содержание кофеина не оценивается.']},
];
export const saltCoffeeByKey=new Map(SALT_COFFEE_PROFILES.map(x=>[x.catalogKey,x]));
