(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const state = { submissionId:null, analysisSubmissionId:null, noteVersion:0, noteSavedBody:'', accessToken:null, authConfig:null };
  const client=$('client'),file=$('csv-file'),form=$('upload-form'),submit=$('submit-button'),notice=$('notice');
  const loopback=['localhost','127.0.0.1','::1'].includes(location.hostname);
  const authHeaders=()=>state.accessToken?{Authorization:`Bearer ${state.accessToken}`}:{ };
  const idempotencyKey=()=>globalThis.crypto.randomUUID();
  const setNotice=(message,success=false)=>{notice.textContent=message;notice.hidden=!message;notice.classList.toggle('success',success);};
  const safeError=async response=>{try{return (await response.json())?.error?.code||'REQUEST_FAILED';}catch{return 'REQUEST_FAILED';}};
  const api=async(url,options={})=>{const response=await fetch(url,{...options,headers:{...authHeaders(),...(options.headers||{})},credentials:'same-origin'});if(response.status===401){state.accessToken=null;renderSession(false);}if(!response.ok)throw new Error(await safeError(response));return response.json();};
  const base64Url=bytes=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
  const randomValue=()=>base64Url(crypto.getRandomValues(new Uint8Array(32)));
  const challenge=async verifier=>base64Url(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))));

  function renderSession(authenticated,label='Консультант'){
    $('session-title').textContent=authenticated?label:(state.authConfig?.enabled?'Вход не выполнен':'OIDC-вход не настроен');
    $('session-meta').textContent=authenticated?'Защищённый сеанс · токен только в памяти':(state.authConfig?.enabled?'Войдите через провайдера организации':'Добавьте публичные OIDC-параметры в .env');
    $('login-button').hidden=authenticated||!state.authConfig?.enabled;$('logout-button').hidden=!authenticated;
    if(!authenticated){client.disabled=true;client.replaceChildren(new Option('Сначала выполните вход',''));clearHistory('Войдите, чтобы увидеть загрузки.');}
  }
  async function startLogin(prompt='login'){prompt=typeof prompt==='string'?prompt:'login';const c=state.authConfig,verifier=randomValue(),oidcState=randomValue(),nonce=randomValue();sessionStorage.setItem('oidc_transaction',JSON.stringify({verifier,state:oidcState,nonce,createdAt:Date.now()}));const p=new URLSearchParams({client_id:c.client_id,response_type:'code',redirect_uri:c.redirect_uri,scope:c.scope,state:oidcState,nonce,code_challenge:await challenge(verifier),code_challenge_method:'S256',prompt});if(c.audience)p.set('audience',c.audience);location.assign(`${c.authorization_endpoint}?${p}`);}
  async function finishLogin(c){const p=new URLSearchParams(location.search),code=p.get('code'),returnedState=p.get('state'),error=p.get('error');if(error){history.replaceState({},'',location.pathname);if(error==='login_required'){sessionStorage.removeItem('oidc_session_seen');return false;}throw new Error('OIDC_AUTHORIZATION_FAILED');}if(!code){if(sessionStorage.getItem('oidc_session_seen')==='1')await startLogin('none');return false;}let tx;try{tx=JSON.parse(sessionStorage.getItem('oidc_transaction')||'null');}catch{tx=null;}sessionStorage.removeItem('oidc_transaction');history.replaceState({},'',location.pathname);if(!tx||tx.state!==returnedState||Date.now()-tx.createdAt>600000)throw new Error('OIDC_STATE_INVALID');const body=new URLSearchParams({grant_type:'authorization_code',client_id:c.client_id,code,redirect_uri:c.redirect_uri,code_verifier:tx.verifier});const response=await fetch(c.token_endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!response.ok)throw new Error('OIDC_TOKEN_EXCHANGE_FAILED');const tokens=await response.json();if(typeof tokens.access_token!=='string')throw new Error('OIDC_ACCESS_TOKEN_MISSING');state.accessToken=tokens.access_token;sessionStorage.setItem('oidc_session_seen','1');return true;}
  async function initializeAuth(){try{state.authConfig=await (await fetch('/api/v1/auth/config',{credentials:'same-origin'})).json();if(state.authConfig.enabled)await finishLogin(state.authConfig);else if(loopback&&new URLSearchParams(location.search).get('synthetic_test')==='1')state.accessToken='synthetic-ui-token';if(!state.accessToken){renderSession(false);return;}const me=await api('/api/v1/me');renderSession(true,me.display_name||'Консультант');await loadClients();}catch{state.accessToken=null;renderSession(false);setNotice('Не удалось завершить защищённый вход. Попробуйте войти снова.');}}
  async function loadClients(){try{const body=await api('/api/v1/clients');client.replaceChildren(new Option('Выберите клиента',''));body.items.forEach(item=>client.add(new Option(item.label,item.id)));client.disabled=false;}catch{setNotice('Не удалось получить доступных клиентов.');}}
  const refreshSubmit=()=>{submit.disabled=!state.accessToken||!client.value||!file.files.length;};
  function clearHistory(message){$('history-list').hidden=true;$('history-list').replaceChildren();$('history-empty').textContent=message;$('history-empty').hidden=false;$('refresh-history').disabled=true;}
  async function loadHistory(){if(!client.value)return clearHistory('Выберите клиента, чтобы увидеть последние загрузки.');$('refresh-history').disabled=true;try{const body=await api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions?limit=20`),list=$('history-list');list.replaceChildren();body.items.forEach(item=>{const row=document.createElement('article');row.className='history-item';const info=document.createElement('div'),title=document.createElement('strong'),date=document.createElement('small');title.textContent=item.schema_id;date.textContent=new Intl.DateTimeFormat('ru',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.created_at));info.append(title,date);const controls=document.createElement('div');controls.className='history-controls';const badge=document.createElement('span');badge.className=`badge ${item.status==='blocked'?'blocked':''}`;badge.textContent=item.status;controls.append(badge);if(item.status==='accepted'){const open=document.createElement('button');open.type='button';open.className='analysis-open';open.textContent='Открыть анализ';open.addEventListener('click',()=>loadAnalysis(item.submission_id));controls.append(open);}row.append(info,controls);list.append(row);});$('history-empty').textContent=body.items.length?'':'Загрузок пока нет.';$('history-empty').hidden=body.items.length>0;list.hidden=body.items.length===0;}catch{clearHistory('Не удалось загрузить историю. Повторите попытку.');}finally{$('refresh-history').disabled=!client.value;}}
  async function loadAnalysis(submissionId){setNotice('');state.analysisSubmissionId=submissionId;const panel=$('analysis'),container=$('analysis-sections');container.replaceChildren();panel.hidden=false;$('analysis-disclaimer').textContent='Загружаем ответы…';$('note-body').value='';$('note-body').disabled=true;$('save-note').disabled=true;$('note-status').textContent='Загружаем заметку…';panel.scrollIntoView({behavior:'smooth',block:'start'});try{const [body,note]=await Promise.all([api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions/${encodeURIComponent(submissionId)}/analysis`),api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions/${encodeURIComponent(submissionId)}/note`)]);$('analysis-disclaimer').textContent=body.disclaimer;body.sections.forEach(section=>{const block=document.createElement('section');block.className='analysis-section';const title=document.createElement('h3');title.textContent=section.title;const fields=document.createElement('dl');section.fields.forEach(field=>{const row=document.createElement('div'),term=document.createElement('dt'),value=document.createElement('dd');term.textContent=field.label;value.textContent=field.value;row.append(term,value);fields.append(row);});block.append(title,fields);container.append(block);});state.noteVersion=note.version;state.noteSavedBody=note.body;$('note-body').value=note.body;$('note-body').disabled=false;$('note-version').textContent=`Версия ${note.version}`;$('note-status').textContent=note.version?'Заметка сохранена.':'Заметка ещё не создана.';}catch(error){clearAnalysis();setNotice(`Анализ не загружен: ${error.message}.`);}}
  function clearAnalysis(){state.analysisSubmissionId=null;state.noteVersion=0;state.noteSavedBody='';$('analysis').hidden=true;$('analysis-sections').replaceChildren();$('note-body').value='';$('note-body').disabled=true;$('save-note').disabled=true;$('note-status').textContent='';}
  async function saveNote(){if(!state.analysisSubmissionId)return;const button=$('save-note'),body=$('note-body').value;button.disabled=true;$('note-status').textContent='Сохраняем…';try{const note=await api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions/${encodeURIComponent(state.analysisSubmissionId)}/note`,{method:'PATCH',headers:{'Content-Type':'application/json','If-Match':`"${state.noteVersion}"`},body:JSON.stringify({body})});state.noteVersion=note.version;state.noteSavedBody=note.body;$('note-body').value=note.body;$('note-version').textContent=`Версия ${note.version}`;$('note-status').textContent='Изменения сохранены.';}catch(error){if(error.message==='CONSULTANT_NOTE_VERSION_CONFLICT')$('note-status').textContent='Заметка изменена в другом окне. Закройте и откройте анализ заново; ваш текст оставлен в поле.';else $('note-status').textContent=`Не удалось сохранить: ${error.message}.`;button.disabled=false;}}
  function renderPreview(data){state.submissionId=data.submission_id;$('schema-value').textContent=data.schema_id;$('consent-value').textContent=data.consent_status==='verified'?'Подтверждено':'Не подтверждено';$('status-value').textContent=data.status;$('block-value').textContent=data.block_code||'Нет';const badge=$('status-badge');badge.textContent=data.status;badge.className=`badge ${data.status==='blocked'?'blocked':''}`;$('accept-button').disabled=data.status!=='verified'||data.consent_status!=='verified'||Boolean(data.block_code);$('reject-button').disabled=data.status==='accepted'||data.status==='blocked';$('preview').hidden=false;$('preview').scrollIntoView({behavior:'smooth',block:'nearest'});}
  function updateFile(){const selected=file.files[0];$('file-title').textContent=selected?selected.name:'Выберите файл или перетащите сюда';$('file-meta').textContent=selected?`${Math.ceil(selected.size/1024)} КБ · файл хранится только до отправки`:'CSV · одна анкета · не более 2 МБ';refreshSubmit();}
  async function upload(event){event.preventDefault();setNotice('');submit.disabled=true;submit.querySelector('span').textContent='Проверяем…';const data=new FormData();data.append('file',file.files[0]);try{renderPreview(await api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions/import-preview/csv`,{method:'POST',headers:{'Idempotency-Key':idempotencyKey()},body:data}));file.value='';updateFile();await loadHistory();}catch(error){setNotice(`Проверка не выполнена: ${error.message}. Можно выбрать файл и повторить.`);}finally{submit.querySelector('span').textContent='Проверить анкету';refreshSubmit();}}
  async function decide(action){if(!state.submissionId)return;setNotice('');const options={method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey()}};if(action==='reject')options.body=JSON.stringify({reason_code:'CONSULTANT_REJECTED'});try{renderPreview(await api(`/api/v1/submissions/${encodeURIComponent(state.submissionId)}/${action}`,options));setNotice(action==='accept'?'Анкета принята в работу.':'Анкета отклонена.',true);await loadHistory();}catch(error){setNotice(`Решение не сохранено: ${error.message}. Повторите попытку.`);}}
  $('login-button').addEventListener('click',startLogin);$('logout-button').addEventListener('click',()=>{state.accessToken=null;renderSession(false);setNotice('Сеанс завершён.',true);});client.addEventListener('change',()=>{clearAnalysis();refreshSubmit();loadHistory();});file.addEventListener('change',updateFile);form.addEventListener('submit',upload);$('refresh-history').addEventListener('click',loadHistory);$('accept-button').addEventListener('click',()=>decide('accept'));$('reject-button').addEventListener('click',()=>decide('reject'));$('close-analysis').addEventListener('click',clearAnalysis);$('save-note').addEventListener('click',saveNote);$('note-body').addEventListener('input',()=>{$('save-note').disabled=$('note-body').value===state.noteSavedBody;$('note-status').textContent=$('save-note').disabled?'Изменений нет.':'Есть несохранённые изменения.';});
  $('logout-button').addEventListener('click',event=>{event.stopImmediatePropagation();const c=state.authConfig;state.accessToken=null;sessionStorage.removeItem('oidc_session_seen');sessionStorage.removeItem('oidc_transaction');if(c?.logout_endpoint){const p=new URLSearchParams({client_id:c.client_id,returnTo:c.redirect_uri});location.assign(`${c.logout_endpoint}?${p}`);return;}renderSession(false);},true);
  ['dragenter','dragover'].forEach(name=>$('dropzone').addEventListener(name,()=>$('dropzone').classList.add('drag')));['dragleave','drop'].forEach(name=>$('dropzone').addEventListener(name,()=>$('dropzone').classList.remove('drag')));addEventListener('beforeunload',()=>{state.accessToken=null;file.value='';state.submissionId=null;});initializeAuth();
})();
