(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const state = { submissionId:null, analysisSubmissionId:null, noteVersion:0, noteSavedBody:'', bookingVersion:0, bookingSaved:'', proteinTargetVersion:0, proteinTargetSaved:'', proteinIntakeVersion:0,proteinIntakeItems:[],proteinIntakeSaved:'',foodProducts:[],accessToken:null, authConfig:null };
  const client=$('client'),file=$('csv-file'),form=$('upload-form'),submit=$('submit-button'),notice=$('notice');
  const loopback=['localhost','127.0.0.1','::1'].includes(location.hostname);
  const authHeaders=()=>state.accessToken?{Authorization:`Bearer ${state.accessToken}`}:{ };
  const idempotencyKey=()=>globalThis.crypto.randomUUID();
  const setNotice=(message,success=false)=>{notice.textContent=message;notice.hidden=!message;notice.classList.toggle('success',success);};
  const safeError=async response=>{try{return (await response.json())?.error?.code||'REQUEST_FAILED';}catch{return 'REQUEST_FAILED';}};
  const api=async(url,options={})=>{const response=await fetch(url,{...options,headers:{...authHeaders(),...(options.headers||{})},credentials:'same-origin'});if(response.status===401){state.accessToken=null;renderSession(false);}if(!response.ok)throw new Error(await safeError(response));return response.json();};
  const base64Url=bytes=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
  const randomValue=()=>base64Url(crypto.getRandomValues(new Uint8Array(32)));
  const challenge=async verifier=>base64Url(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))));

  function renderSession(authenticated,label='Консультант'){
    $('session-title').textContent=authenticated?label:(state.authConfig?.enabled?'Вход не выполнен':'OIDC-вход не настроен');
    $('session-meta').textContent=authenticated?'Защищённый сеанс · токен только в памяти':(state.authConfig?.enabled?'Войдите через провайдера организации':'Добавьте публичные OIDC-параметры в .env');
    $('login-button').hidden=authenticated||!state.authConfig?.enabled;$('logout-button').hidden=!authenticated;
    if(!authenticated){client.disabled=true;client.replaceChildren(new Option('Сначала выполните вход',''));clearHistory('Войдите, чтобы увидеть загрузки.');}
  }
  async function startLogin(prompt='login'){prompt=typeof prompt==='string'?prompt:'login';const c=state.authConfig,verifier=randomValue(),oidcState=randomValue(),nonce=randomValue();sessionStorage.setItem('oidc_transaction',JSON.stringify({verifier,state:oidcState,nonce,createdAt:Date.now()}));const p=new URLSearchParams({client_id:c.client_id,response_type:'code',redirect_uri:c.redirect_uri,scope:c.scope,state:oidcState,nonce,code_challenge:await challenge(verifier),code_challenge_method:'S256',prompt});if(c.audience)p.set('audience',c.audience);location.assign(`${c.authorization_endpoint}?${p}`);}
  async function finishLogin(c){const p=new URLSearchParams(location.search),code=p.get('code'),returnedState=p.get('state'),error=p.get('error');if(error){history.replaceState({},'',location.pathname);if(error==='login_required'){sessionStorage.removeItem('oidc_session_seen');return false;}throw new Error('OIDC_AUTHORIZATION_FAILED');}if(!code){if(sessionStorage.getItem('oidc_session_seen')==='1')await startLogin('none');return false;}let tx;try{tx=JSON.parse(sessionStorage.getItem('oidc_transaction')||'null');}catch{tx=null;}sessionStorage.removeItem('oidc_transaction');history.replaceState({},'',location.pathname);if(!tx||tx.state!==returnedState||Date.now()-tx.createdAt>600000)throw new Error('OIDC_STATE_INVALID');const body=new URLSearchParams({grant_type:'authorization_code',client_id:c.client_id,code,redirect_uri:c.redirect_uri,code_verifier:tx.verifier});const response=await fetch(c.token_endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!response.ok)throw new Error('OIDC_TOKEN_EXCHANGE_FAILED');const tokens=await response.json();if(typeof tokens.access_token!=='string')throw new Error('OIDC_ACCESS_TOKEN_MISSING');state.accessToken=tokens.access_token;sessionStorage.setItem('oidc_session_seen','1');return true;}
  async function initializeAuth(){try{state.authConfig=await (await fetch('/api/v1/auth/config',{credentials:'same-origin'})).json();if(state.authConfig.enabled)await finishLogin(state.authConfig);else if(loopback&&new URLSearchParams(location.search).get('synthetic_test')==='1')state.accessToken='synthetic-ui-token';if(!state.accessToken){renderSession(false);return;}const me=await api('/api/v1/me');renderSession(true,me.display_name||'Консультант');await loadClients();}catch{state.accessToken=null;renderSession(false);setNotice('Не удалось завершить защищённый вход. Попробуйте войти снова.');}}
  async function loadClients(){try{const body=await api('/api/v1/clients');client.replaceChildren(new Option('Выберите клиента',''));body.items.forEach(item=>client.add(new Option(item.label,item.id)));client.disabled=false;}catch{setNotice('Не удалось получить доступных клиентов.');}}
  const refreshSubmit=()=>{submit.disabled=!state.accessToken||!client.value||!file.files.length;};
  function clearHistory(message){$('history-list').hidden=true;$('history-list').replaceChildren();$('history-empty').textContent=message;$('history-empty').hidden=false;$('refresh-history').disabled=true;}
  async function loadHistory(){if(!client.value)return clearHistory('Выберите клиента, чтобы увидеть последние загрузки.');$('refresh-history').disabled=true;try{const body=await api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions?limit=20`),list=$('history-list');list.replaceChildren();body.items.forEach(item=>{const row=document.createElement('article');row.className='history-item';const info=document.createElement('div'),title=document.createElement('strong'),date=document.createElement('small');title.textContent=item.schema_id;date.textContent=new Intl.DateTimeFormat('ru',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.created_at));info.append(title,date);const controls=document.createElement('div');controls.className='history-controls';const badge=document.createElement('span');badge.className=`badge ${item.status==='blocked'?'blocked':''}`;badge.textContent=item.status;controls.append(badge);if(item.status==='accepted'){const open=document.createElement('button');open.type='button';open.className='analysis-open';open.textContent='Открыть анализ';open.addEventListener('click',()=>loadAnalysis(item.submission_id));controls.append(open);}row.append(info,controls);list.append(row);});$('history-empty').textContent=body.items.length?'':'Загрузок пока нет.';$('history-empty').hidden=body.items.length>0;list.hidden=body.items.length===0;}catch{clearHistory('Не удалось загрузить историю. Повторите попытку.');}finally{$('refresh-history').disabled=!client.value;}}
  async function loadAnalysis(submissionId){setNotice('');state.analysisSubmissionId=submissionId;const panel=$('analysis'),container=$('analysis-sections');container.replaceChildren();panel.hidden=false;$('analysis-disclaimer').textContent='Загружаем ответы…';$('note-body').value='';$('note-body').disabled=true;$('save-note').disabled=true;$('note-status').textContent='Загружаем заметку…';$('booking-save-status').textContent='Загружаем статус…';$('protein-save-status').textContent='Загружаем белковый ориентир…';$('intake-save-status').textContent='Загружаем расчёт…';panel.scrollIntoView({behavior:'smooth',block:'start'});try{const [body,note,booking,proteinTarget,intake,products]=await Promise.all([api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions/${encodeURIComponent(submissionId)}/analysis`),api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions/${encodeURIComponent(submissionId)}/note`),api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions/${encodeURIComponent(submissionId)}/booking`),api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions/${encodeURIComponent(submissionId)}/protein-target`),api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions/${encodeURIComponent(submissionId)}/protein-intake`),api(`/api/v1/clients/${encodeURIComponent(client.value)}/food-products`)]);$('analysis-disclaimer').textContent=body.disclaimer;body.sections.forEach(section=>{const block=document.createElement('section');block.className='analysis-section';const title=document.createElement('h3');title.textContent=section.title;const fields=document.createElement('dl');section.fields.forEach(field=>{const row=document.createElement('div'),term=document.createElement('dt'),value=document.createElement('dd');term.textContent=field.label;value.textContent=field.value;row.append(term,value);fields.append(row);});block.append(title,fields);container.append(block);});state.noteVersion=note.version;state.noteSavedBody=note.body;$('note-body').value=note.body;$('note-body').disabled=false;$('note-version').textContent=`Версия ${note.version}`;$('note-status').textContent=note.version?'Заметка сохранена.':'Заметка ещё не создана.';renderBooking(booking);renderProteinTarget(proteinTarget);renderProteinIntake(intake,products.items);}catch(error){clearAnalysis();setNotice(`Анализ не загружен: ${error.message}.`);}}
  function clearAnalysis(){state.analysisSubmissionId=null;state.noteVersion=0;state.noteSavedBody='';state.proteinTargetVersion=0;state.proteinTargetSaved='';$('analysis').hidden=true;$('analysis-sections').replaceChildren();$('note-body').value='';$('note-body').disabled=true;$('save-note').disabled=true;$('note-status').textContent='';}
  async function saveNote(){if(!state.analysisSubmissionId)return;const button=$('save-note'),body=$('note-body').value;button.disabled=true;$('note-status').textContent='Сохраняем…';try{const note=await api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions/${encodeURIComponent(state.analysisSubmissionId)}/note`,{method:'PATCH',headers:{'Content-Type':'application/json','If-Match':`"${state.noteVersion}"`},body:JSON.stringify({body})});state.noteVersion=note.version;state.noteSavedBody=note.body;$('note-body').value=note.body;$('note-version').textContent=`Версия ${note.version}`;$('note-status').textContent='Изменения сохранены.';}catch(error){if(error.message==='CONSULTANT_NOTE_VERSION_CONFLICT')$('note-status').textContent='Заметка изменена в другом окне. Закройте и откройте анализ заново; ваш текст оставлен в поле.';else $('note-status').textContent=`Не удалось сохранить: ${error.message}.`;button.disabled=false;}}
  const bookingSnapshot=()=>JSON.stringify({status:$('booking-status').value,scheduled_at:$('booking-status').value==='scheduled'&&$('booking-at').value?new Date($('booking-at').value).toISOString():null,contact_note:$('booking-contact').value});
  const localDateTimeValue=value=>{if(!value)return '';const date=new Date(value),offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16);};
  function renderBooking(b){state.bookingVersion=b.version;$('booking-status').value=b.status;$('booking-at').value=localDateTimeValue(b.scheduled_at);$('booking-at').disabled=b.status!=='scheduled';$('booking-contact').value=b.contact_note;$('booking-version').textContent=`Версия ${b.version}`;state.bookingSaved=bookingSnapshot();$('save-booking').disabled=true;$('booking-save-status').textContent=b.version?'Статус сохранён.':'Запись ещё не согласована.';}
  function bookingChanged(){$('booking-at').disabled=$('booking-status').value!=='scheduled';if($('booking-status').value!=='scheduled')$('booking-at').value='';$('save-booking').disabled=bookingSnapshot()===state.bookingSaved;$('booking-save-status').textContent=$('save-booking').disabled?'Изменений нет.':'Есть несохранённые изменения.';}
  async function saveBooking(){if(!state.analysisSubmissionId)return;const button=$('save-booking');button.disabled=true;$('booking-save-status').textContent='Сохраняем…';try{const payload=JSON.parse(bookingSnapshot()),b=await api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions/${encodeURIComponent(state.analysisSubmissionId)}/booking`,{method:'PATCH',headers:{'Content-Type':'application/json','If-Match':`"${state.bookingVersion}"`},body:JSON.stringify(payload)});renderBooking(b);$('booking-save-status').textContent='Изменения сохранены.';}catch(error){$('booking-save-status').textContent=error.message==='CONSULTATION_BOOKING_VERSION_CONFLICT'?'Статус изменён в другом окне. Переоткройте анализ.':`Не удалось сохранить: ${error.message}.`;button.disabled=false;}}
  const proteinTargetSnapshot=()=>JSON.stringify({source:$('protein-target-source').value,protein_factor_g:Number($('protein-factor').value)||null,target_min_g:Number($('protein-min').value)||null,target_max_g:Number($('protein-max').value)||null,reason:$('protein-reason').value});
  function renderProteinTarget(target){state.proteinTargetVersion=target.version;$('protein-target-source').value=target.source||'built_in';$('protein-factor').value=target.protein_factor_g??'';$('protein-min').value=target.target_min_g??'';$('protein-max').value=target.target_max_g??'';$('protein-reason').value=target.reason||'';$('protein-target-version').textContent=`Версия ${target.version}`;$('protein-calculation').textContent=target.bmi_rounded?`Расчётный ИМТ ${String(target.bmi_exact).replace('.',',')}; для линейки округлён до ${target.bmi_rounded}.`:'';toggleProteinInputs();state.proteinTargetSaved=proteinTargetSnapshot();$('save-protein-target').disabled=target.version>0;$('protein-save-status').textContent=target.version?'Ориентир сохранён.':'Нажмите «Сохранить ориентир», чтобы выполнить встроенный расчёт.';}
  function toggleProteinInputs(){const builtIn=$('protein-target-source').value==='built_in';['protein-factor','protein-min','protein-max'].forEach(id=>$(id).disabled=builtIn);if(builtIn&&state.proteinTargetVersion===0){$('protein-factor').value='';$('protein-min').value='';$('protein-max').value='';}}
  function proteinTargetChanged(){toggleProteinInputs();$('save-protein-target').disabled=proteinTargetSnapshot()===state.proteinTargetSaved;$('protein-save-status').textContent=$('save-protein-target').disabled?'Изменений нет.':'Есть несохранённые изменения.';}
  async function saveProteinTarget(){if(!state.analysisSubmissionId)return;const button=$('save-protein-target'),payload=JSON.parse(proteinTargetSnapshot());button.disabled=true;$('protein-save-status').textContent='Сохраняем…';try{const target=await api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions/${encodeURIComponent(state.analysisSubmissionId)}/protein-target`,{method:'PATCH',headers:{'Content-Type':'application/json','If-Match':`"${state.proteinTargetVersion}"`},body:JSON.stringify(payload)});renderProteinTarget(target);$('protein-save-status').textContent='Изменения сохранены.';}catch(error){$('protein-save-status').textContent=error.message==='PROTEIN_TARGET_MANUAL_REQUIRED'?'Параметры находятся вне встроенной шкалы. Выберите ручной расчёт.':error.message==='PROTEIN_TARGET_VERSION_CONFLICT'?'Ориентир изменён в другом окне. Переоткройте анализ.':`Не удалось сохранить: ${error.message}.`;button.disabled=false;}}
  const intakeSnapshot=()=>JSON.stringify(state.proteinIntakeItems);
  const mealLabel=key=>({breakfast:'Завтрак',snack_1:'Первый перекус',lunch:'Обед',snack_2:'Второй перекус',dinner:'Ужин',bedtime:'Перед сном',other:'Другое'})[key]||'Другое';
  const rangeLabel=key=>({incomplete_data:'Данные неполные',target_not_set:'Ориентир не задан',below_range:'Ниже диапазона',within_range:'В диапазоне',above_range:'Выше диапазона'})[key]||'—';
  const plantLabel=key=>({unavailable:'Недостаточно данных',meets_guide:'Не менее 50%',below_guide:'Менее 50%'})[key]||'—';
  function renderProteinIntake(intake,products){state.foodProducts=products;state.proteinIntakeVersion=intake.version;state.proteinIntakeItems=intake.items||[];const select=$('intake-product');select.replaceChildren(new Option(products.length?'Выберите продукт':'Нет проверенных карточек',''));products.forEach(product=>select.add(new Option(`${product.name} · ${product.proteinPer100g} г/100 г`,product.id)));$('add-intake-item').disabled=true;renderIntakeItems();renderIntakeSummary(intake.summary);state.proteinIntakeSaved=intakeSnapshot();$('save-protein-intake').disabled=true;$('protein-intake-version').textContent=`Версия ${intake.version}`;$('intake-save-status').textContent=intake.version?'Расчёт сохранён.':products.length?'Добавьте позиции дневника.':'Сначала нужны проверенные карточки продуктов.';}
  function renderIntakeItems(){const box=$('intake-items');box.replaceChildren();state.proteinIntakeItems.forEach((item,index)=>{const product=state.foodProducts.find(p=>p.id===item.product_card_id),row=document.createElement('div'),name=document.createElement('strong'),meta=document.createElement('small'),remove=document.createElement('button');row.className='intake-item';name.textContent=product?.name||'Карточка недоступна';meta.textContent=`${mealLabel(item.meal_key)} · ${item.mass_g} г`;remove.type='button';remove.textContent='Убрать';remove.addEventListener('click',()=>{state.proteinIntakeItems.splice(index,1);renderIntakeItems();intakeChanged();});row.append(name,meta,remove);box.append(row);});}
  function renderIntakeSummary(summary){const dl=$('intake-summary');dl.replaceChildren();dl.hidden=!summary;if(!summary)return;[['Всего белка',`${summary.total_protein_g} г`],['Растительный',`${summary.plant_protein_g} г · ${summary.plant_share_percent??'—'}%`],['Животный',`${summary.animal_protein_g} г`],['Полнота',`${summary.completeness_percent}%`],['Сравнение',rangeLabel(summary.range_status)],['Растительная доля',plantLabel(summary.plant_share_status)]].forEach(([label,value])=>{const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;row.append(dt,dd);dl.append(row);});}
  function intakeEntryChanged(){$('add-intake-item').disabled=!$('intake-product').value||!(Number($('intake-mass').value)>0);}
  function intakeChanged(){$('save-protein-intake').disabled=intakeSnapshot()===state.proteinIntakeSaved;$('intake-save-status').textContent=$('save-protein-intake').disabled?'Изменений нет.':'Есть несохранённые изменения.';}
  function addIntakeItem(){state.proteinIntakeItems.push({meal_key:$('intake-meal').value,product_card_id:$('intake-product').value,mass_g:Number($('intake-mass').value)});$('intake-mass').value='';$('intake-product').value='';$('add-intake-item').disabled=true;renderIntakeItems();intakeChanged();}
  async function saveProteinIntake(){const button=$('save-protein-intake');button.disabled=true;$('intake-save-status').textContent='Сохраняем…';try{const intake=await api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions/${encodeURIComponent(state.analysisSubmissionId)}/protein-intake`,{method:'PATCH',headers:{'Content-Type':'application/json','If-Match':`"${state.proteinIntakeVersion}"`},body:JSON.stringify({items:state.proteinIntakeItems})});renderProteinIntake(intake,state.foodProducts);$('intake-save-status').textContent='Изменения сохранены.';}catch(error){$('intake-save-status').textContent=error.message==='PROTEIN_INTAKE_VERSION_CONFLICT'?'Расчёт изменён в другом окне. Переоткройте анализ.':`Не удалось сохранить: ${error.message}.`;button.disabled=false;}}
  function renderPreview(data){state.submissionId=data.submission_id;$('schema-value').textContent=data.schema_id;$('consent-value').textContent=data.consent_status==='verified'?'Подтверждено':'Не подтверждено';$('status-value').textContent=data.status;$('block-value').textContent=data.block_code||'Нет';const badge=$('status-badge');badge.textContent=data.status;badge.className=`badge ${data.status==='blocked'?'blocked':''}`;$('accept-button').disabled=data.status!=='verified'||data.consent_status!=='verified'||Boolean(data.block_code);$('reject-button').disabled=data.status==='accepted'||data.status==='blocked';$('preview').hidden=false;$('preview').scrollIntoView({behavior:'smooth',block:'nearest'});}
  function updateFile(){const selected=file.files[0];$('file-title').textContent=selected?selected.name:'Выберите файл или перетащите сюда';$('file-meta').textContent=selected?`${Math.ceil(selected.size/1024)} КБ · файл хранится только до отправки`:'CSV · одна анкета · не более 2 МБ';refreshSubmit();}
  async function upload(event){event.preventDefault();setNotice('');submit.disabled=true;submit.querySelector('span').textContent='Проверяем…';const data=new FormData();data.append('file',file.files[0]);try{renderPreview(await api(`/api/v1/clients/${encodeURIComponent(client.value)}/submissions/import-preview/csv`,{method:'POST',headers:{'Idempotency-Key':idempotencyKey()},body:data}));file.value='';updateFile();await loadHistory();}catch(error){setNotice(`Проверка не выполнена: ${error.message}. Можно выбрать файл и повторить.`);}finally{submit.querySelector('span').textContent='Проверить анкету';refreshSubmit();}}
  async function decide(action){if(!state.submissionId)return;setNotice('');const options={method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey()}};if(action==='reject')options.body=JSON.stringify({reason_code:'CONSULTANT_REJECTED'});try{renderPreview(await api(`/api/v1/submissions/${encodeURIComponent(state.submissionId)}/${action}`,options));setNotice(action==='accept'?'Анкета принята в работу.':'Анкета отклонена.',true);await loadHistory();}catch(error){setNotice(`Решение не сохранено: ${error.message}. Повторите попытку.`);}}
  $('login-button').addEventListener('click',startLogin);$('logout-button').addEventListener('click',()=>{state.accessToken=null;renderSession(false);setNotice('Сеанс завершён.',true);});client.addEventListener('change',()=>{clearAnalysis();refreshSubmit();loadHistory();});file.addEventListener('change',updateFile);form.addEventListener('submit',upload);$('refresh-history').addEventListener('click',loadHistory);$('accept-button').addEventListener('click',()=>decide('accept'));$('reject-button').addEventListener('click',()=>decide('reject'));$('close-analysis').addEventListener('click',clearAnalysis);$('save-note').addEventListener('click',saveNote);$('note-body').addEventListener('input',()=>{$('save-note').disabled=$('note-body').value===state.noteSavedBody;$('note-status').textContent=$('save-note').disabled?'Изменений нет.':'Есть несохранённые изменения.';});
  $('booking-status').addEventListener('change',bookingChanged);$('booking-at').addEventListener('input',bookingChanged);$('booking-contact').addEventListener('input',bookingChanged);$('save-booking').addEventListener('click',saveBooking);
  $('protein-target-source').addEventListener('change',proteinTargetChanged);['protein-factor','protein-min','protein-max','protein-reason'].forEach(id=>$(id).addEventListener('input',proteinTargetChanged));$('save-protein-target').addEventListener('click',saveProteinTarget);
  $('intake-product').addEventListener('change',intakeEntryChanged);$('intake-mass').addEventListener('input',intakeEntryChanged);$('add-intake-item').addEventListener('click',addIntakeItem);$('save-protein-intake').addEventListener('click',saveProteinIntake);
  $('logout-button').addEventListener('click',event=>{event.stopImmediatePropagation();const c=state.authConfig;state.accessToken=null;sessionStorage.removeItem('oidc_session_seen');sessionStorage.removeItem('oidc_transaction');if(c?.logout_endpoint){const p=new URLSearchParams({client_id:c.client_id,returnTo:c.redirect_uri});location.assign(`${c.logout_endpoint}?${p}`);return;}renderSession(false);},true);
  ['dragenter','dragover'].forEach(name=>$('dropzone').addEventListener(name,()=>$('dropzone').classList.add('drag')));['dragleave','drop'].forEach(name=>$('dropzone').addEventListener(name,()=>$('dropzone').classList.remove('drag')));addEventListener('beforeunload',()=>{state.accessToken=null;file.value='';state.submissionId=null;});initializeAuth();
})();
